// 중1 수학 II 문자와 식, 레슨 4 항·계수·차수와 일차식 단원 종합 평가 풀(22문항).
// 교과서에서는 개념 조합과 함정만 참고하고 수치·문구·소재 결합은 새로 설계했다.
// 유형 14(mcq+multi)/6(num)/2(word), diff 1/2/3 = 8/9/5.
import type { ExamItem } from "./types";

const L = "m1u2l4";

export const POOL_M1U2L4: ExamItem[] = [
  {
    id: "m1u2e067",
    lessonId: L,
    type: "mcq",
    prompt: "음향 트랙의 편집 시간을 나타낸 식이 −7<i class='mv'>t</i>+19일 때, 이 식의 항을 바르게 나타낸 것은?",
    options: ["7<i class='mv'>t</i>, 19", "−7<i class='mv'>t</i>, −19", "−7<i class='mv'>t</i>, 19", "7, <i class='mv'>t</i>, 19", "−7, <i class='mv'>t</i>, 19"],
    answer: 2,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>뺄셈을 덧셈으로 고쳐 보면 −7<i class='mv'>t</i>+19는 (−7<i class='mv'>t</i>)+19예요. 따라서 항은 부호까지 붙인 <b>−7<i class='mv'>t</i>, 19</b> 두 개예요.<span class='xh'>오답 하나씩 격파</span>'7<i class='mv'>t</i>, 19'는 첫 항의 음수 부호를 잃었고, '−7<i class='mv'>t</i>, −19'는 양수인 상수항의 부호를 바꿨어요. '7, <i class='mv'>t</i>, 19'와 '−7, <i class='mv'>t</i>, 19'는 곱으로 이어진 −7과 <i class='mv'>t</i>를 서로 다른 항으로 쪼갠 오류예요. 항은 덧셈으로 이어진 한 덩어리이며, 앞의 부호도 그 항의 일부로 함께 읽어야 해요. 식을 괄호로 묶어 다시 쓰면 경계가 또렷해져요.",
    core: "항은 덧셈으로 나뉘고 부호까지 한 덩어리예요!",
  },
  {
    id: "m1u2e068",
    lessonId: L,
    type: "mcq",
    prompt: "기록 보관 상자의 분류 번호를 나타낸 식이 12<i class='mv'>p</i>−17이에요. <i class='mv'>p</i>의 계수와 상수항을 차례로 바르게 짝 지은 것은?",
    options: ["12, 17", "−12, 17", "−12, −17", "17, 12", "12, −17"],
    answer: 4,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>문자 <i class='mv'>p</i>에 곱해진 수는 12이므로 <i class='mv'>p</i>의 계수는 12예요. 문자 없이 수만 있는 항은 −17이므로 상수항은 <b>−17</b>이고, 짝은 <b>12, −17</b>이에요.<span class='xh'>오답 하나씩 격파</span>'12, 17'은 상수항의 음수 부호를 빠뜨렸어요. '−12, 17'과 '−12, −17'은 뺄셈 기호가 문자항 앞에 있다고 착각했지만, 식의 첫 항은 양수 12<i class='mv'>p</i>예요. '17, 12'는 상수항과 계수의 역할을 뒤집었고요. 계수는 문자에 붙은 곱셈의 수, 상수항은 문자가 전혀 없는 항이에요. 각 항을 부호까지 먼저 나눈 뒤 이름표를 붙이면 혼동이 줄어요.",
    core: "12p−17에서 계수는 12, 상수항은 −17!",
  },
  {
    id: "m1u2e069",
    lessonId: L,
    type: "mcq",
    prompt: "드론의 적재 상태를 나타낸 다항식 −4<i class='mv'>d</i>²+9<i class='mv'>d</i>−6은 모두 몇 개의 항으로 이루어져 있나요?",
    options: ["2개", "3개", "4개", "5개", "6개"],
    answer: 1,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>식을 덧셈 꼴로 보면 (−4<i class='mv'>d</i>²)+9<i class='mv'>d</i>+(−6)이에요. 덧셈으로 이어진 덩어리가 <b>−4<i class='mv'>d</i>², 9<i class='mv'>d</i>, −6</b>이므로 항은 3개예요.<span class='xh'>오답 하나씩 격파</span>2개라고 하면 마지막 상수항 −6이나 가운데 항 9<i class='mv'>d</i>를 놓친 거예요. 4개 이상으로 세면 −4와 <i class='mv'>d</i>², 또는 9와 <i class='mv'>d</i>를 따로 떼어 센 경우가 많아요. 곱셈으로 붙은 수와 문자는 한 항 안의 부품이지 서로 다른 항이 아니에요. 더하기와 빼기 기호를 경계로 보되, 빼는 항의 음수 부호는 뒤 항에 붙여 세면 정확히 3개가 나와요.",
    core: "−4d², 9d, −6으로 나뉘므로 항은 3개!",
  },
  {
    id: "m1u2e070",
    lessonId: L,
    type: "mcq",
    prompt: "전시 패널의 밝기 변화를 나타낸 단항식 −8<i class='mv'>s</i>⁴의 차수는?",
    options: ["1", "2", "3", "4", "8"],
    answer: 3,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>차수는 항에서 문자가 곱해진 개수예요. <i class='mv'>s</i>⁴은 <i class='mv'>s</i>가 네 번 곱해진 것이므로 −8<i class='mv'>s</i>⁴의 차수는 <b>4</b>예요. 앞의 −8은 계수라 차수를 바꾸지 않아요.<span class='xh'>오답 하나씩 격파</span>1은 문자의 종류가 한 가지라는 사실을 차수와 혼동한 값이에요. 2나 3은 지수 4를 잘못 읽었고요. 8은 계수의 크기를 차수라고 본 오류예요. 음수 부호도 계수의 부호일 뿐 문자가 곱해진 횟수에는 영향을 주지 않아요. <i class='mv'>s</i>⁴=<i class='mv'>s</i>×<i class='mv'>s</i>×<i class='mv'>s</i>×<i class='mv'>s</i>로 풀어 쓰면 네 개가 분명히 보여요. 계수와 지수를 따로 표시해 검산해요.",
    core: "s⁴는 s가 네 번 곱해졌으므로 차수는 4!",
  },
  {
    id: "m1u2e071",
    lessonId: L,
    type: "multi",
    prompt: "다음 중 단항식을 <b>모두 고르세요.</b>",
    options: ["9<i class='mv'>x</i>", "3<i class='mv'>x</i>+7", "−5", "7÷<i class='mv'>x</i>", "4<i class='mv'>y</i>²"],
    answer: [0, 2, 4],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>수 또는 문자의 곱으로 이루어진 항 하나만 있는 식이 단항식이에요. 9<i class='mv'>x</i>, 수 하나인 −5, 4<i class='mv'>y</i>²은 각각 항이 하나이므로 단항식이에요.<span class='xh'>오답 하나씩 격파</span>3<i class='mv'>x</i>+7은 3<i class='mv'>x</i>와 7이라는 두 항의 합이므로 다항식이지만 단항식은 아니에요. 7÷<i class='mv'>x</i>는 7/<i class='mv'>x</i>처럼 문자가 분모에 있어 수와 문자의 곱으로 된 항으로 보지 않아요. 문자가 없다고 단항식이 아닌 것이 아니라, −5처럼 수만 있는 식도 항 하나예요. 반대로 문자가 하나 보인다고 모두 단항식인 것도 아니므로 덧셈 경계와 분모의 문자를 함께 확인해야 해요.",
    core: "항이 하나이고 분모에 문자가 없으면 단항식 후보예요!",
  },
  {
    id: "m1u2e072",
    lessonId: L,
    type: "mcq",
    prompt: "다음 중 다항식이 <b>아닌 것</b>은?",
    options: ["−6<i class='mv'>r</i>+13", "4<i class='mv'>r</i>²−7<i class='mv'>r</i>", "11÷<i class='mv'>r</i>+2", "9", "0.3<i class='mv'>r</i>−8"],
    answer: 2,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>11÷<i class='mv'>r</i>+2는 11/<i class='mv'>r</i>+2와 같아 문자가 분모에 있어 다항식이 아니에요. 다항식의 각 항은 수와 문자의 곱으로 나타낼 수 있어야 해요.<span class='xh'>오답 하나씩 격파</span>−6<i class='mv'>r</i>+13과 0.3<i class='mv'>r</i>−8은 일차항과 상수항의 합이라 다항식이에요. 4<i class='mv'>r</i>²−7<i class='mv'>r</i>도 차수가 2일 뿐 두 항으로 된 다항식이고요. 수 9는 문자 없는 한 항으로 이루어진 단항식이며 단항식도 다항식에 포함돼요. 분수 모양 자체가 금지되는 것이 아니라, 분모에 문자가 있는지를 확인해야 해요. 예를 들어 <i class='mv'>r</i>÷11은 (1/11)<i class='mv'>r</i>이라 다항식이에요.",
    core: "11÷r처럼 문자가 분모에 있으면 다항식이 아니에요!",
  },
  {
    id: "m1u2e073",
    lessonId: L,
    type: "mcq",
    prompt: "센서 신호식 −3<i class='mv'>a</i>³+8<i class='mv'>a</i>−14에 대한 설명으로 옳지 않은 것은?",
    options: ["항은 4개이다", "<i class='mv'>a</i>³의 계수는 −3이다", "<i class='mv'>a</i>의 계수는 8이다", "상수항은 −14이다", "식의 차수는 3이다"],
    answer: 0,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>항은 −3<i class='mv'>a</i>³, 8<i class='mv'>a</i>, −14의 세 개예요. 따라서 '항은 4개이다'가 옳지 않은 설명이에요. 가장 높은 차수는 3이므로 식의 차수도 3이에요.<span class='xh'>오답 하나씩 격파</span>−3<i class='mv'>a</i>³에서 <i class='mv'>a</i>³에 곱해진 수는 부호까지 −3이므로 그 계수 설명은 맞아요. 8<i class='mv'>a</i>에서 <i class='mv'>a</i>의 계수는 8이고, 문자 없는 −14가 상수항이라는 설명도 맞고요. 8과 <i class='mv'>a</i>를 따로 세거나 −3과 <i class='mv'>a</i>³을 나누어 세면 항이 네 개 이상으로 불어나요. 곱셈은 한 항 안에서 묶고 덧셈 경계만 따라가야 해요.",
    core: "항은 세 개, 최고 차수는 3이에요!",
  },
  {
    id: "m1u2e074",
    lessonId: L,
    type: "multi",
    prompt: "다음 중 <i class='mv'>x</i>에 대한 일차식을 <b>모두 고르세요.</b>",
    options: ["−9<i class='mv'>x</i>+16", "<i class='mv'>x</i>²+4", "<i class='mv'>x</i>÷7−3", "5−2<i class='mv'>x</i>", "8÷<i class='mv'>x</i>+1"],
    answer: [0, 2, 3],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>−9<i class='mv'>x</i>+16과 5−2<i class='mv'>x</i>는 최고 차수가 1인 다항식이에요. <i class='mv'>x</i>÷7−3도 (1÷7)<i class='mv'>x</i>−3이므로 일차식이에요.<span class='xh'>오답 하나씩 격파</span><i class='mv'>x</i>²+4는 <i class='mv'>x</i>²항의 차수가 2라서 일차식이 아니에요. 8÷<i class='mv'>x</i>+1은 문자가 분모에 있어 다항식이 아니므로 일차식도 될 수 없고요. 나눗셈 기호가 있다고 무조건 탈락하는 것은 아니에요. 문자를 수로 나눈 <i class='mv'>x</i>÷7은 수 1÷7과 <i class='mv'>x</i>의 곱으로 바꿀 수 있지만, 수를 문자로 나눈 8÷<i class='mv'>x</i>는 그렇게 바꿀 수 없다는 차이를 확인해요.",
    core: "최고 차수 1이고 분모에 문자가 없어야 일차식이에요!",
  },
  {
    id: "m1u2e075",
    lessonId: L,
    type: "mcq",
    prompt: "식 (<i class='mv'>k</i>−6)<i class='mv'>x</i>+11이 <i class='mv'>x</i>에 대한 일차식이 되지 않게 하는 <i class='mv'>k</i>의 값은?",
    options: ["1", "4", "5", "7", "6"],
    answer: 4,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>일차식이려면 <i class='mv'>x</i>의 계수 <i class='mv'>k</i>−6이 0이 아니어야 해요. <i class='mv'>k</i>=6이면 <i class='mv'>k</i>−6=0이 되어 식은 0<i class='mv'>x</i>+11=11로 정리되므로 일차식이 아니에요.<span class='xh'>오답 하나씩 격파</span><i class='mv'>k</i>=1, 4, 5, 7을 넣으면 <i class='mv'>x</i>의 계수는 각각 −5, −2, −1, 1이에요. 모두 0이 아니므로 <i class='mv'>x</i>항이 남고 최고 차수가 1이에요. 계수가 음수라고 일차식에서 탈락하는 것이 아니며, 계수의 부호보다 0인지가 핵심이에요. 0<i class='mv'>x</i>는 어떤 <i class='mv'>x</i>에서도 0이라 문자항 자체가 사라진다는 점을 확인해요.",
    core: "x의 계수가 0이면 문자항이 사라져 일차식이 아니에요!",
  },
  {
    id: "m1u2e076",
    lessonId: L,
    type: "mcq",
    prompt: "센서 신호를 나타낸 다항식 −2<i class='mv'>s</i>³+5<i class='mv'>s</i>²−<i class='mv'>s</i>+12에 대한 설명으로 옳은 것은?",
    options: ["항은 3개이다", "<i class='mv'>s</i>의 계수는 −1이다", "<i class='mv'>s</i>³의 계수는 2이다", "상수항은 −12이다", "식의 차수는 2이다"],
    answer: 1,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>−<i class='mv'>s</i>는 −1×<i class='mv'>s</i>를 줄여 쓴 것이므로 <i class='mv'>s</i>의 계수는 <b>−1</b>이에요. 보이지 않는 1도 부호와 함께 복원해야 해요.<span class='xh'>오답 하나씩 격파</span>항은 −2<i class='mv'>s</i>³, 5<i class='mv'>s</i>², −<i class='mv'>s</i>, 12의 네 개예요. <i class='mv'>s</i>³의 계수는 음수 부호까지 −2이고, 상수항은 양수 12예요. 가장 높은 차수의 항이 <i class='mv'>s</i>³이므로 식의 차수는 3이고요. 지수, 계수, 항의 부호를 한꺼번에 읽지 말고 먼저 항을 네 덩어리로 나눈 뒤 각 덩어리의 부품을 확인하면 실수를 줄일 수 있어요. 특히 −<i class='mv'>s</i>의 생략된 1을 놓치지 마세요.",
    core: "−s는 −1×s이므로 s의 계수는 −1!",
  },
  {
    id: "m1u2e077",
    lessonId: L,
    type: "multi",
    prompt: "전시 패널의 부품 관계식 6<i class='mv'>m</i>²−11<i class='mv'>m</i>+4에 대한 설명으로 옳은 것을 <b>모두 고르세요.</b>",
    options: ["식의 차수는 2이다", "<i class='mv'>m</i>의 계수는 −11이다", "<i class='mv'>m</i>²의 계수는 −6이다", "상수항은 4이다", "항은 2개이다"],
    answer: [0, 1, 3],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>가장 높은 차수는 6<i class='mv'>m</i>²의 2이므로 식의 차수는 2예요. −11<i class='mv'>m</i>에서 <i class='mv'>m</i>의 계수는 −11이고, 문자 없는 4는 상수항이에요.<span class='xh'>오답 하나씩 격파</span>6<i class='mv'>m</i>²은 양수 항이므로 <i class='mv'>m</i>²의 계수는 −6이 아니라 6이에요. 식은 6<i class='mv'>m</i>², −11<i class='mv'>m</i>, 4의 세 항으로 이루어져 있어 '항은 2개'도 틀려요. 차수 2를 항의 개수 2와 연결하면 안 돼요. 차수는 문자가 곱해진 횟수 중 가장 큰 값이고, 항의 개수는 덧셈으로 나뉜 덩어리 수라는 서로 다른 정보예요.",
    core: "차수 2, m의 계수 −11, 상수항 4를 구별해요!",
  },
  {
    id: "m1u2e078",
    lessonId: L,
    type: "mcq",
    prompt: "다음 설명 중 옳은 것은?",
    options: ["수 −13은 차수가 0인 단항식이다", "5<i class='mv'>x</i>²은 일차식이다", "2÷<i class='mv'>x</i>는 다항식이다", "0<i class='mv'>x</i>+8은 일차식이다", "<i class='mv'>x</i>+7은 단항식이다"],
    answer: 0,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>−13은 수 하나로 이루어진 항이므로 단항식이고, 문자가 없어서 차수는 0이에요. 단항식은 한 항으로 된 다항식에도 포함돼요.<span class='xh'>오답 하나씩 격파</span>5<i class='mv'>x</i>²은 차수가 2이므로 일차식이 아니에요. 2÷<i class='mv'>x</i>는 문자가 분모에 있어 다항식이 아니고요. 0<i class='mv'>x</i>+8은 문자항이 사라져 상수 8만 남으므로 일차식이 아니에요. <i class='mv'>x</i>+7은 <i class='mv'>x</i>와 7의 두 항으로 이루어져 단항식이 아니라 다항식이에요. 문자 유무만으로 이름을 정하지 말고 항의 개수, 분모의 문자, 최고 차수를 차례로 확인해요.",
    core: "수 하나도 차수 0인 단항식이 될 수 있어요!",
  },
  {
    id: "m1u2e079",
    lessonId: L,
    type: "multi",
    prompt: "분모에 문자가 있는지 살펴볼 때, 다음 식 가운데 <i class='mv'>q</i>에 대한 일차식인 것을 <b>모두 고르세요.</b>",
    options: ["<i class='mv'>q</i>÷8+3", "8÷<i class='mv'>q</i>+3", "(<i class='mv'>q</i>+6)÷5", "4÷(<i class='mv'>q</i>−1)", "−0.7<i class='mv'>q</i>"],
    answer: [0, 2, 4],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>q</i>÷8+3은 (1÷8)<i class='mv'>q</i>+3, (<i class='mv'>q</i>+6)÷5는 (1÷5)<i class='mv'>q</i>+6÷5로 나타낼 수 있어 최고 차수가 1이에요. −0.7<i class='mv'>q</i>도 한 항으로 된 일차식이에요.<span class='xh'>오답 하나씩 격파</span>8÷<i class='mv'>q</i>+3은 <i class='mv'>q</i>가 분모에 있어 다항식이 아니에요. 4÷(<i class='mv'>q</i>−1)도 문자가 든 식 전체가 분모에 있으므로 일차식이 될 수 없고요. 분수나 소수가 보인다고 탈락시키면 안 돼요. 분모가 8이나 5처럼 수이면 계수가 분수인 일차식이지만, 분모에 <i class='mv'>q</i>가 들어가면 다항식이 아니라는 기준을 적용해요.",
    core: "수로 나눈 문자는 가능하지만 문자가 분모에 있으면 탈락해요!",
  },
  {
    id: "m1u2e080",
    lessonId: L,
    type: "mcq",
    prompt: "기록 보관 패널의 칸 수를 0<i class='mv'>n</i>+27로 나타냈어요. 이 식에 대한 설명으로 옳은 것은?",
    options: ["<i class='mv'>n</i>의 계수는 27이다", "항은 반드시 두 개이다", "식의 차수는 1이다", "27로 정리되므로 일차식이 아니다", "<i class='mv'>n</i>=0일 때만 27이 된다"],
    answer: 3,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>0<i class='mv'>n</i>은 <i class='mv'>n</i>의 값과 관계없이 0이에요. 따라서 0<i class='mv'>n</i>+27=27로 정리되고 문자항이 남지 않으므로 <b>일차식이 아니에요.</b><span class='xh'>오답 하나씩 격파</span><i class='mv'>n</i>의 계수는 27이 아니라 0이에요. 0<i class='mv'>n</i>은 정리하면 사라지므로 실제로 남는 항은 상수항 27 하나이고, 차수도 1이 아니라 0이에요. 또한 <i class='mv'>n</i>=0일 때만 27이 되는 것이 아니라 어떤 수를 넣어도 0×<i class='mv'>n</i>+27=27이에요. 식의 겉모양에 문자가 있다고 바로 일차식이라 판단하지 말고, 문자항의 계수가 0인지까지 확인한 뒤 가장 높은 차수를 정해야 해요.",
    core: "0n은 사라져 27만 남으므로 일차식이 아니에요!",
  },
  {
    id: "m1u2e081",
    lessonId: L,
    type: "num",
    prompt: "음향 트랙의 조정값을 나타낸 일차식 −12<i class='mv'>x</i>+23에서 <i class='mv'>x</i>의 계수를 구하세요.",
    answer: "-12",
    numKind: "int",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>−12<i class='mv'>x</i>는 (−12)×<i class='mv'>x</i>를 줄여 쓴 항이에요. 문자 <i class='mv'>x</i>에 곱해진 수를 부호까지 읽으면 계수는 <b>−12</b>예요.<span class='xh'>오답 경로 격파</span>12라고 입력하면 문자항 앞의 음수 부호를 빠뜨린 거예요. 23은 문자 없이 수만 있는 상수항이므로 <i class='mv'>x</i>의 계수가 아니에요. −23은 상수항의 수에 문자항의 부호를 잘못 붙인 값이고, 2는 항의 개수라고 착각한 값일 수 있어요. 계수를 찾을 때는 먼저 해당 문자가 든 항 하나만 떼고, 문자를 가린 뒤 남는 수와 부호를 함께 읽어요. −12<i class='mv'>x</i>에서 <i class='mv'>x</i>를 가리면 −12가 그대로 남아요.",
    core: "−12x에서 x에 곱해진 계수는 −12!",
  },
  {
    id: "m1u2e082",
    lessonId: L,
    type: "num",
    prompt: "드론 적재식 7<i class='mv'>p</i>²−4<i class='mv'>p</i>−9의 상수항을 구하세요.",
    answer: "-9",
    numKind: "int",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>상수항은 문자가 전혀 들어 있지 않고 수만으로 이루어진 항이에요. 7<i class='mv'>p</i>²−4<i class='mv'>p</i>−9에서 그런 항은 부호까지 <b>−9</b>예요.<span class='xh'>오답 경로 격파</span>9라고 입력하면 상수항 앞의 음수 부호를 놓친 거예요. 7은 <i class='mv'>p</i>²의 계수이고 −4는 <i class='mv'>p</i>의 계수라서 둘 다 문자항의 부품이에요. 3은 항의 개수, 2는 가장 높은 지수이므로 상수항과 다른 정보고요. 식을 7<i class='mv'>p</i>²+(−4<i class='mv'>p</i>)+(−9)로 바꾸어 쓰면 문자 없는 마지막 항의 부호가 분명해져요. 상수항도 하나의 항이므로 앞의 부호를 떼지 않고 답해야 해요.",
    core: "문자 없는 항은 부호까지 −9예요!",
  },
  {
    id: "m1u2e083",
    lessonId: L,
    type: "num",
    prompt: "다항식 5<i class='mv'>a</i>³−2<i class='mv'>a</i>²+<i class='mv'>a</i>−8은 모두 몇 개의 항으로 이루어져 있나요?",
    answer: "4",
    numKind: "int",
    unitLabel: "개",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>덧셈 꼴로 고쳐 보면 5<i class='mv'>a</i>³+(−2<i class='mv'>a</i>²)+<i class='mv'>a</i>+(−8)이에요. 항은 5<i class='mv'>a</i>³, −2<i class='mv'>a</i>², <i class='mv'>a</i>, −8이므로 모두 <b>4개</b>예요.<span class='xh'>오답 경로 격파</span>3개라고 세면 상수항 −8이나 계수가 생략된 <i class='mv'>a</i>항을 놓친 경우가 많아요. 5개 이상이면 계수와 문자를 따로 항으로 센 오류예요. 지수 3을 보고 항도 3개라고 답하거나, 최고 차수와 항의 개수를 같은 정보로 생각해서도 안 돼요. 항은 더하기와 빼기의 경계를 따라 세고, 곱으로 붙은 수·문자·지수는 한 덩어리로 유지해요.",
    core: "네 덩어리로 나뉘므로 항은 4개!",
  },
  {
    id: "m1u2e084",
    lessonId: L,
    type: "num",
    prompt: "센서 신호식 15<i class='mv'>m</i>⁵−2<i class='mv'>m</i>²+7의 차수를 구하세요.",
    answer: "5",
    numKind: "int",
    unitLabel: "차",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>각 항의 차수는 15<i class='mv'>m</i>⁵가 5, −2<i class='mv'>m</i>²가 2, 상수항 7이 0이에요. 다항식의 차수는 가장 큰 항의 차수이므로 <b>5차</b>예요.<span class='xh'>오답 경로 격파</span>2라고 답하면 마지막으로 보인 문자항의 지수만 읽고 최고 차수 5를 놓친 거예요. 7이나 15는 각각 상수항과 계수의 크기이지 차수가 아니에요. 3은 항의 개수를 차수로 착각한 값이고요. 차수는 계수가 얼마나 큰지와 관계없이 문자가 몇 번 곱해졌는지를 나타내요. 모든 항의 지수를 적어 5, 2, 0 중 가장 큰 값을 고르면 계수와 항 개수에 흔들리지 않아요.",
    core: "항의 차수 5, 2, 0 중 가장 큰 5가 식의 차수!",
  },
  {
    id: "m1u2e085",
    lessonId: L,
    type: "num",
    prompt: "다항식 6<i class='mv'>x</i>²+<i class='mv'>k</i><i class='mv'>x</i>−11에서 <i class='mv'>x</i>의 계수가 −8일 때, <i class='mv'>k</i>의 값을 구하세요.",
    answer: "-8",
    numKind: "int",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>x</i>항은 <i class='mv'>k</i><i class='mv'>x</i>이고, 여기서 <i class='mv'>x</i>에 곱해진 수가 바로 <i class='mv'>k</i>예요. 그 계수가 −8이라고 했으므로 <b><i class='mv'>k</i>=−8</b>이에요.<span class='xh'>오답 경로 격파</span>8은 주어진 계수의 음수 부호를 빠뜨린 값이에요. 6은 <i class='mv'>x</i>²의 계수라서 묻는 <i class='mv'>x</i>의 계수와 다르고, −11은 문자 없는 상수항이에요. 2는 <i class='mv'>x</i>²의 차수일 뿐 <i class='mv'>k</i>의 값과 관계없어요. 같은 문자가 보여도 지수가 2인 항과 지수가 1인 항은 따로 읽어야 해요. 식에 <i class='mv'>k</i>=−8을 넣으면 6<i class='mv'>x</i>²−8<i class='mv'>x</i>−11이 되어 <i class='mv'>x</i>항의 계수가 실제로 −8인지 바로 검산할 수 있어요.",
    core: "kx에서 x의 계수는 k이므로 k=−8!",
  },
  {
    id: "m1u2e086",
    lessonId: L,
    type: "num",
    prompt: "전시 패널의 부품식을 나타낸 7<i class='mv'>q</i>⁴−6<i class='mv'>q</i>²+3<i class='mv'>q</i>−20에서 <i class='mv'>q</i>의 계수를 구하세요.",
    answer: "3",
    numKind: "int",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>q</i>의 계수를 물었으므로 지수가 1인 <i class='mv'>q</i>항을 찾아야 해요. 그 항은 3<i class='mv'>q</i>이고 <i class='mv'>q</i>에 곱해진 수는 <b>3</b>이에요.<span class='xh'>오답 경로 격파</span>7은 <i class='mv'>q</i>⁴의 계수이고 −6은 <i class='mv'>q</i>²의 계수라서 문자 이름은 같아도 차수가 다른 항의 부품이에요. −20은 문자 없는 상수항이고, 4는 식의 차수예요. 식에 <i class='mv'>q</i>가 여러 번 보여도 묻는 항의 지수를 먼저 확인해야 해요. 지수가 표시되지 않은 <i class='mv'>q</i>의 지수는 1이에요. 3<i class='mv'>q</i>는 3×<i class='mv'>q</i>이므로 <i class='mv'>q</i>만 가리면 3이 남는다는 방법으로도 검산할 수 있어요.",
    core: "지수 1인 3q를 찾아 계수 3을 읽어요!",
  },
  {
    id: "m1u2e087",
    lessonId: L,
    type: "word",
    prompt: "다항식을 이루는 각각의 부분 가운데 수 또는 문자의 곱으로 이루어진 한 덩어리를 무엇이라고 하나요?",
    answer: "항",
    bank: ["항", "계수", "차수", "상수항", "다항식", "일차식", "식의 값", "등식"],
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>다항식에서 덧셈으로 이어진 각각의 덩어리를 <b>항</b>이라고 해요. 예를 들어 2<i class='mv'>x</i>²−7<i class='mv'>x</i>+10의 항은 부호까지 2<i class='mv'>x</i>², −7<i class='mv'>x</i>, 10이에요.<span class='xh'>오답 칩 격파</span>'계수'는 문자에 곱해진 수이고, '차수'는 문자가 곱해진 횟수예요. '상수항'은 항 가운데 문자가 없는 특별한 항이고요. '다항식'은 하나 이상의 항을 더한 식 전체, '일차식'은 차수가 1인 다항식이에요. '식의 값'은 문자에 수를 넣어 계산한 결과이고 '등식'은 등호로 두 양이 같음을 나타낸 식이에요. 질문은 식 전체가 아니라 그 식을 이루는 한 덩어리의 이름을 묻고 있어요.",
    core: "식에서 덧셈으로 나뉜 한 덩어리는 항!",
  },
  {
    id: "m1u2e088",
    lessonId: L,
    type: "word",
    prompt: "다항식의 항 가운데 문자가 들어 있지 않고 수만으로 이루어진 항을 무엇이라고 하나요?",
    answer: "상수항",
    bank: ["상수항", "계수", "차수", "항", "단항식", "다항식", "일차식", "항등식"],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>다항식에서 문자가 들어 있지 않고 수만으로 이루어진 항을 <b>상수항</b>이라고 해요. 예를 들어 −4<i class='mv'>x</i>+13에서는 13이 상수항이고, 부호도 항의 일부예요.<span class='xh'>오답 칩 격파</span>'계수'는 문자에 곱해진 수, '차수'는 문자가 곱해진 횟수예요. '항'은 식을 이루는 모든 덩어리를 가리키는 더 넓은 이름이고요. '단항식'과 '다항식'은 항의 개수와 모양에 따라 식 전체를 부르는 이름이에요. '일차식'은 최고 차수가 1인 다항식이며, '항등식'은 어떤 수를 넣어도 참인 등식이에요. 수만 남은 항을 찾은 뒤 그 앞의 부호까지 붙여 읽는 것이 상수항 판별의 핵심이에요.",
    core: "문자 없이 수만으로 된 항은 상수항!",
  },
];
