// 중1 수학 II 문자와 식, 레슨 7 등식의 성질 단원 종합 평가 풀(22문항).
// 교과서에서는 성질과 함정 구조만 참고하고 수치·문구·소재 결합은 새로 설계했다.
// 유형 13(mcq+multi)/7(num)/2(word), diff 1/2/3 = 9/9/4.
import type { ExamItem } from "./types";

const L = "m1u2l7";

export const POOL_M1U2L7: ExamItem[] = [
  {
    id: "m1u2e133",
    lessonId: L,
    type: "mcq",
    prompt: "등식 <i class='mv'>a</i>=<i class='mv'>b</i>의 양변에 9를 더해 얻은 등식은?",
    options: ["<i class='mv'>a</i>+9=<i class='mv'>b</i>", "<i class='mv'>a</i>=<i class='mv'>b</i>+9", "<i class='mv'>a</i>+9=<i class='mv'>b</i>+9", "<i class='mv'>a</i>+9=<i class='mv'>b</i>−9", "9<i class='mv'>a</i>=9+<i class='mv'>b</i>"],
    answer: 2,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>a</i>=<i class='mv'>b</i>에서 양변에 같은 수 9를 더하면 <b><i class='mv'>a</i>+9=<i class='mv'>b</i>+9</b>가 되어 같음이 유지돼요.<span class='xh'>오답 하나씩 격파</span><i class='mv'>a</i>+9=<i class='mv'>b</i>와 <i class='mv'>a</i>=<i class='mv'>b</i>+9는 한쪽에만 9를 더해 균형을 깨뜨렸어요. <i class='mv'>a</i>+9=<i class='mv'>b</i>−9는 왼쪽에는 더하고 오른쪽에서는 빼서 같은 조작이 아니고요. 9<i class='mv'>a</i>=9+<i class='mv'>b</i>는 왼쪽에는 9를 곱하고 오른쪽에는 9를 더했어요. 예를 들어 <i class='mv'>a</i>=<i class='mv'>b</i>=4를 넣으면 정답 식은 13=13이지만 한쪽만 바꾼 식은 13=4가 돼요. 연산 기호와 수가 양쪽에서 모두 같은지 한 항씩 짝지어 확인해야 해요.",
    core: "양변에 9를 더하면 a+9=b+9!",
  },
  {
    id: "m1u2e134",
    lessonId: L,
    type: "mcq",
    prompt: "등식 <i class='mv'>u</i>−14=25에서 <i class='mv'>u</i>=39를 얻기 위해 양변에 한 조작은?",
    options: ["양변에서 14를 뺐다", "양변에 25를 더했다", "양변에 14를 곱했다", "양변을 14로 나누었다", "양변에 14를 더했다"],
    answer: 4,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>u</i>−14에서 −14를 없애려면 반대 연산인 +14를 사용해요. 양변에 14를 더하면 <i class='mv'>u</i>−14+14=25+14이므로 <b><i class='mv'>u</i>=39</b>가 돼요.<span class='xh'>오답 하나씩 격파</span>양변에서 14를 빼면 왼쪽은 <i class='mv'>u</i>−28이 되어 문자가 홀로 남지 않아요. 25를 더하거나 14를 곱하고 나누는 조작도 −14를 없애지 못하고요. 오른쪽의 25만 보고 더할 수를 정하는 것이 아니라, 문자와 함께 있는 −14의 반대 연산을 골라야 해요. 마지막에는 양쪽에 정확히 같은 14를 더했는지 확인해요.",
    core: "−14를 없애려면 양변에 14를 더해요!",
  },
  {
    id: "m1u2e135",
    lessonId: L,
    type: "mcq",
    prompt: "등식 <i class='mv'>p</i>÷4=11에서 <i class='mv'>p</i>=44를 얻을 때 사용한 등식의 성질은?",
    options: ["양변에 4를 더한다", "양변에 4를 곱한다", "양변에서 4를 뺀다", "양변을 11로 나눈다", "왼쪽에만 4를 곱한다"],
    answer: 1,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>p</i>÷4의 나누기 4를 없애려면 반대 연산인 곱하기 4를 양변에 해요. (<i class='mv'>p</i>÷4)×4=11×4에서 <b><i class='mv'>p</i>=44</b>를 얻어요.<span class='xh'>오답 하나씩 격파</span>4를 더하거나 빼면 <i class='mv'>p</i>÷4가 그대로 남아 문자를 홀로 만들 수 없어요. 양변을 11로 나누면 오른쪽은 1이 되지만 왼쪽은 <i class='mv'>p</i>÷44가 되어 목표와 멀어지고요. 왼쪽에만 4를 곱하면 오른쪽 11은 그대로라 원래의 같음이 깨져요. 나눗셈을 없애는 곱셈을 고른 뒤 반드시 양쪽에 함께 적용해요. 44÷4=11로 되돌려 검산할 수도 있어요.",
    core: "p÷4의 나누기를 없애려면 양변에 4를 곱해요!",
  },
  {
    id: "m1u2e136",
    lessonId: L,
    type: "mcq",
    prompt: "등식 7<i class='mv'>q</i>=63에서 <i class='mv'>q</i>=9를 얻기 위해 양변에 한 조작은?",
    options: ["양변에 7을 더했다", "양변에서 7을 뺐다", "양변에 7을 곱했다", "양변을 7로 나누었다", "오른쪽만 7로 나누었다"],
    answer: 3,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>7<i class='mv'>q</i>는 7×<i class='mv'>q</i>이므로 곱하기 7의 반대 연산인 나누기 7을 사용해요. 양변을 7로 나누면 7<i class='mv'>q</i>÷7=63÷7에서 <b><i class='mv'>q</i>=9</b>가 돼요.<span class='xh'>오답 하나씩 격파</span>7을 더하거나 빼면 <i class='mv'>q</i>의 계수 7이 사라지지 않아요. 7을 다시 곱하면 49<i class='mv'>q</i>=441로 식만 커지고요. 오른쪽만 7로 나누면 왼쪽은 7<i class='mv'>q</i>인 채로 오른쪽만 9가 되어 원래 등식과 다른 식이 돼요. 계수를 없앨 때는 그 계수로 양쪽을 함께 나눈다는 두 조건을 모두 지켜요. 7×9=63으로 검산하면 계산도 맞아요.",
    core: "7q의 계수 7을 없애려면 양변을 7로 나눠요!",
  },
  {
    id: "m1u2e137",
    lessonId: L,
    type: "mcq",
    prompt: "등식 <i class='mv'>c</i>=<i class='mv'>d</i>에서 사용할 수 <b>없는</b> 조작은?",
    options: ["양변을 0으로 나눈다", "양변에 0을 더한다", "양변에서 −3을 뺀다", "양변에 0을 곱한다", "양변을 −5로 나눈다"],
    answer: 0,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>0으로 나누기는 값이 정해지지 않는 연산이므로 등식의 성질로 사용할 수 없어요. 양변을 나눌 때는 반드시 <b>0이 아닌 같은 수</b>로 나누어야 해요.<span class='xh'>오답 하나씩 격파</span>양변에 0을 더하면 원래 식 그대로라 같음이 유지돼요. 양변에서 −3을 빼는 것은 양변에 3을 더하는 것과 같아 가능하고요. 양변에 0을 곱하면 0=0이 되어 정보는 사라지지만 등식 자체는 참이에요. −5는 0이 아니므로 양변을 −5로 나누는 것도 가능해요. 곱하기 0과 나누기 0을 같은 금지로 착각하지 말고, 나누기에만 0이 아닌 수라는 조건이 붙는다는 점을 기억해요.",
    core: "등식의 양변을 0으로 나눌 수는 없어요!",
  },
  {
    id: "m1u2e138",
    lessonId: L,
    type: "multi",
    prompt: "<i class='mv'>c</i>=<i class='mv'>d</i>일 때 항상 성립하는 등식을 <b>모두 고르세요.</b>",
    options: ["<i class='mv'>c</i>+13=<i class='mv'>d</i>+13", "<i class='mv'>c</i>−8=<i class='mv'>d</i>−8", "−4<i class='mv'>c</i>=−4<i class='mv'>d</i>", "<i class='mv'>c</i>+6=<i class='mv'>d</i>−6", "<i class='mv'>c</i>÷0=<i class='mv'>d</i>÷0"],
    answer: [0, 1, 2],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>양변에 13을 더하거나 양변에서 8을 빼면 같음이 유지돼요. 양변에 같은 수 −4를 곱한 −4<i class='mv'>c</i>=−4<i class='mv'>d</i>도 항상 성립해요.<span class='xh'>오답 하나씩 격파</span><i class='mv'>c</i>+6=<i class='mv'>d</i>−6은 왼쪽에는 6을 더하고 오른쪽에서는 6을 빼 서로 다른 조작을 했어요. <i class='mv'>c</i>÷0=<i class='mv'>d</i>÷0은 양쪽에 같은 기호를 썼더라도 0으로 나누기 자체가 정의되지 않아 등식의 성질이 될 수 없어요. '같은 일을 한다'는 말에는 연산과 수가 같아야 한다는 조건뿐 아니라, 그 연산이 실제로 가능한 연산이어야 한다는 조건도 포함돼요.",
    core: "같은 연산과 같은 수를 양변에 적용해야 해요!",
  },
  {
    id: "m1u2e139",
    lessonId: L,
    type: "mcq",
    prompt: "등식 <i class='mv'>m</i>+18=31에서 만든 식 가운데 원래 등식과 같은 해를 갖지 않는 것은?",
    options: ["<i class='mv'>m</i>+18−18=31−18", "<i class='mv'>m</i>=13", "2(<i class='mv'>m</i>+18)=62", "(<i class='mv'>m</i>+18)÷2=31÷2", "<i class='mv'>m</i>+18+5=31−5"],
    answer: 4,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>m</i>+18+5=31−5는 왼쪽에는 5를 더하고 오른쪽에서는 5를 빼 양변에 같은 일을 하지 않았어요. 원래 해 <i class='mv'>m</i>=13을 넣으면 36=26이 되어 거짓이에요.<span class='xh'>오답 하나씩 격파</span>양변에서 18을 빼면 <i class='mv'>m</i>=13이 되므로 두 식은 같은 해를 가져요. 양변에 2를 곱한 2(<i class='mv'>m</i>+18)=62도 가능하고, 양변을 0이 아닌 수 2로 나눈 식도 가능해요. 결과식 <i class='mv'>m</i>=13 역시 원래 식을 올바르게 정리한 식이에요. 변형 과정에서는 양쪽의 연산 기호와 수를 나란히 비교해요.",
    core: "한쪽은 +5, 다른 쪽은 −5이면 같은 해가 유지되지 않아요!",
  },
  {
    id: "m1u2e140",
    lessonId: L,
    type: "mcq",
    prompt: "포장 상자 3개의 질량과 완충재 15 kg의 합이 72 kg라서 3<i class='mv'>x</i>+15=72라는 등식을 세웠어요. 양쪽에서 완충재 질량을 같은 만큼 빼어 얻은 식은?",
    options: ["3<i class='mv'>x</i>=72−3", "3<i class='mv'>x</i>=72−15", "3<i class='mv'>x</i>+15−15=72", "3<i class='mv'>x</i>=72+15", "<i class='mv'>x</i>=72−15"],
    answer: 1,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>완충재 15 kg을 없애려면 양변에서 15를 빼요. 3<i class='mv'>x</i>+15−15=72−15이므로 <b>3<i class='mv'>x</i>=72−15</b>, 곧 3<i class='mv'>x</i>=57이에요.<span class='xh'>오답 하나씩 격파</span>72−3은 상자 개수 3을 뺀 것으로 완충재 질량을 없애지 못해요. 왼쪽에서만 15를 뺀 3<i class='mv'>x</i>+15−15=72는 오른쪽이 그대로라 등식의 성질을 어겼고요. 72+15는 반대 방향의 연산이에요. <i class='mv'>x</i>=72−15는 3<i class='mv'>x</i>를 바로 <i class='mv'>x</i>로 바꾸어 상자 세 개를 한 개로 줄이는 나눗셈을 빠뜨렸어요. 지금 단계에서는 양쪽에서 15만 빼야 해요.",
    core: "3x+15=72의 양변에서 15를 빼면 3x=57!",
  },
  {
    id: "m1u2e141",
    lessonId: L,
    type: "mcq",
    prompt: "팀 점수 관계를 나타낸 등식 <i class='mv'>y</i>−16=27에서 <i class='mv'>y</i>를 구한 과정으로 옳은 것은?",
    options: ["왼쪽에만 16을 더해 <i class='mv'>y</i>=27", "양변에서 16을 빼서 <i class='mv'>y</i>=11", "양변을 16으로 나누어 <i class='mv'>y</i>=27÷16", "양변에 16을 더해 <i class='mv'>y</i>=43", "양변에 27을 더해 <i class='mv'>y</i>=70"],
    answer: 3,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>y</i>−16에서 −16을 없애기 위해 양변에 16을 더해요. <i class='mv'>y</i>−16+16=27+16이므로 <b><i class='mv'>y</i>=43</b>이에요.<span class='xh'>오답 하나씩 격파</span>왼쪽에만 16을 더하면 오른쪽도 함께 변해야 한다는 성질을 어겨요. 양변에서 16을 빼면 왼쪽은 <i class='mv'>y</i>−32가 되어 <i class='mv'>y</i>가 홀로 남지 않고요. 16으로 나누는 것은 뺄셈을 없애는 반대 연산이 아니에요. 27을 양변에 더해도 −16이 그대로 남아요. 구한 43을 원래 식에 넣어 43−16=27이 되는지 확인하면 조작과 계산을 함께 검산할 수 있어요.",
    core: "y−16=27의 양변에 16을 더하면 y=43!",
  },
  {
    id: "m1u2e142",
    lessonId: L,
    type: "mcq",
    prompt: "등식 −5<i class='mv'>x</i>=35에서 <i class='mv'>x</i>를 홀로 남기는 과정으로 옳은 것은?",
    options: ["양변을 −5로 나누어 <i class='mv'>x</i>=−7", "양변을 5로 나누어 <i class='mv'>x</i>=7", "양변에 5를 더해 <i class='mv'>x</i>=40", "왼쪽만 −5로 나누어 <i class='mv'>x</i>=35", "양변에 −5를 곱해 <i class='mv'>x</i>=−175"],
    answer: 0,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>−5<i class='mv'>x</i>에서 계수 −5를 없애려면 양변을 −5로 나눠요. (−5<i class='mv'>x</i>)÷(−5)=35÷(−5)이므로 <b><i class='mv'>x</i>=−7</b>이에요.<span class='xh'>오답 하나씩 격파</span>양변을 양수 5로 나누면 왼쪽은 −<i class='mv'>x</i>, 오른쪽은 7이라서 <i class='mv'>x</i>=7이 아니에요. 5를 더하는 조작은 곱해진 −5를 없애지 못하고요. 왼쪽만 나누면 등식의 균형이 깨져요. −5를 다시 곱하면 계수가 25로 커질 뿐 문자가 홀로 남지 않아요. 나누는 수의 부호까지 계수와 같아야 해요. 답 −7을 원래 식에 넣으면 −5×(−7)=35로 양변이 같아져요.",
    core: "−5x=35의 양변을 −5로 나누면 x=−7!",
  },
  {
    id: "m1u2e143",
    lessonId: L,
    type: "mcq",
    prompt: "2<i class='mv'>a</i>=5<i class='mv'>b</i>일 때 항상 성립하지는 않는 등식은?",
    options: ["2<i class='mv'>a</i>+9=5<i class='mv'>b</i>+9", "6<i class='mv'>a</i>=15<i class='mv'>b</i>", "2(<i class='mv'>a</i>−4)=5(<i class='mv'>b</i>−4)", "<i class='mv'>a</i>=5<i class='mv'>b</i>÷2", "−2<i class='mv'>a</i>=−5<i class='mv'>b</i>"],
    answer: 2,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>2(<i class='mv'>a</i>−4)=2<i class='mv'>a</i>−8이고 5(<i class='mv'>b</i>−4)=5<i class='mv'>b</i>−20이에요. 원래 양변에서 서로 다른 8과 20을 뺀 셈이므로 항상 같지 않아요.<span class='xh'>오답 하나씩 격파</span>양변에 9를 더한 식은 성립해요. 6<i class='mv'>a</i>=15<i class='mv'>b</i>는 원래 양변에 3을 곱한 식이고, <i class='mv'>a</i>=5<i class='mv'>b</i>÷2는 양변을 2로 나눈 식이에요. −2<i class='mv'>a</i>=−5<i class='mv'>b</i>는 양변에 −1을 곱한 식이고요. 괄호가 보이면 먼저 분배법칙으로 풀어 실제 변화량을 확인해요. 괄호 바깥 계수가 다를 때 안에 같은 수를 넣는 것만으로는 양변에 같은 수를 빼는 조작이 되지 않아요.",
    core: "괄호를 풀어 양변에서 실제로 빠진 수를 비교해요!",
  },
  {
    id: "m1u2e144",
    lessonId: L,
    type: "multi",
    prompt: "등식의 양변에 0을 곱하거나 0으로 나누는 것에 대한 설명으로 옳은 것을 <b>모두 고르세요.</b>",
    options: ["<i class='mv'>a</i>=<i class='mv'>b</i>이면 0<i class='mv'>a</i>=0<i class='mv'>b</i>도 참이다", "양변에 0을 곱한 뒤에는 0으로 나누어 원래 등식을 되살릴 수 없다", "양변을 0으로 나누어도 등식의 성질을 적용한 것이다", "양변을 같은 0이 아닌 수로 나누면 같음이 유지된다", "왼쪽에만 0을 곱해도 언제나 등식이 유지된다"],
    answer: [0, 1, 3],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>a</i>=<i class='mv'>b</i>의 양변에 0을 곱하면 0=0이므로 등식은 참이지만 원래 정보는 사라져요. 0으로 나눌 수 없으므로 이 조작을 거꾸로 되돌릴 수 없어요. 0이 아닌 같은 수로 나누는 것은 가능해요.<span class='xh'>오답 하나씩 격파</span>양변을 0으로 나누는 것은 결과가 정해지지 않아 등식의 성질이 아니에요. 왼쪽에만 0을 곱하면 오른쪽은 <i class='mv'>b</i>인 채 남으므로 0=<i class='mv'>b</i>가 언제나 참일 수 없고요. '양변에 같은 수'라는 조건만 보고 0 나눗셈까지 허용하면 안 돼요. 곱셈은 0도 가능하지만 나눗셈의 같은 수에는 반드시 0이 아니라는 조건이 붙어요.",
    core: "0을 곱할 수는 있지만 0으로 나눌 수는 없어요!",
  },
  {
    id: "m1u2e145",
    lessonId: L,
    type: "multi",
    prompt: "자원 상자 A 6개의 가치와 자원 상자 B 9개의 가치가 같아 6<i class='mv'>a</i>=9<i class='mv'>b</i>라고 했어요. 항상 성립하는 등식을 <b>모두 고르세요.</b>",
    options: ["2<i class='mv'>a</i>=3<i class='mv'>b</i>", "6(<i class='mv'>a</i>+5)=9(<i class='mv'>b</i>+5)", "12<i class='mv'>a</i>=18<i class='mv'>b</i>", "6<i class='mv'>a</i>−4=9<i class='mv'>b</i>+4", "−2<i class='mv'>a</i>=−3<i class='mv'>b</i>"],
    answer: [0, 2, 4],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>6<i class='mv'>a</i>=9<i class='mv'>b</i>의 양변을 3으로 나누면 2<i class='mv'>a</i>=3<i class='mv'>b</i>, 양변에 2를 곱하면 12<i class='mv'>a</i>=18<i class='mv'>b</i>예요. 양변을 −3으로 나누면 −2<i class='mv'>a</i>=−3<i class='mv'>b</i>도 성립해요.<span class='xh'>오답 하나씩 격파</span>6(<i class='mv'>a</i>+5)는 6<i class='mv'>a</i>에 30을 더하지만 9(<i class='mv'>b</i>+5)는 9<i class='mv'>b</i>에 45를 더해 서로 다른 조작이에요. 6<i class='mv'>a</i>−4=9<i class='mv'>b</i>+4도 왼쪽은 4를 빼고 오른쪽은 4를 더해 균형을 깨뜨려요. 나누는 수 −3은 0이 아니므로 음수여도 사용할 수 있어요. 겉으로 같은 숫자가 보여도 전개 뒤 양변에 실제로 적용된 변화를 비교해요.",
    core: "양변을 같은 수로 곱하거나 나눈 식만 골라요!",
  },
  {
    id: "m1u2e146",
    lessonId: L,
    type: "num",
    prompt: "장비 대여 수량의 관계식 <i class='mv'>x</i>+27=45에서 양변에 같은 수를 빼 <i class='mv'>x</i>의 값을 구하세요.",
    answer: "18",
    numKind: "int",
    unitLabel: "대",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>x</i>에 더해진 27을 없애기 위해 양변에서 27을 빼요.<br>① <i class='mv'>x</i>+27−27=45−27<br>② <i class='mv'>x</i>=<b>18</b><br>따라서 대여 수량은 18대예요.<span class='xh'>오답 경로 격파</span>72는 45에 27을 더해 반대 연산을 한 값이에요. 27은 오른쪽에서만 18을 뺀 것처럼 원래 식을 이용하지 않은 값이고요. 45÷27처럼 나누면 덧셈 27을 없애지 못해요. 한쪽에서만 27을 빼서 <i class='mv'>x</i>=45로 만드는 것도 등식의 성질을 어겨요. 답을 원래 식에 넣으면 18+27=45가 되어 양변이 정확히 같아져요.",
    core: "x+27=45의 양변에서 27을 빼면 x=18!",
  },
  {
    id: "m1u2e147",
    lessonId: L,
    type: "num",
    prompt: "팀 점수 관계식 <i class='mv'>x</i>−19=34에서 양변에 같은 수를 더해 <i class='mv'>x</i>의 값을 구하세요.",
    answer: "53",
    numKind: "int",
    unitLabel: "점",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>x</i>에서 빠진 19를 되돌리려면 양변에 19를 더해요.<br>① <i class='mv'>x</i>−19+19=34+19<br>② <i class='mv'>x</i>=<b>53</b><br>따라서 원래 점수는 53점이에요.<span class='xh'>오답 경로 격파</span>15는 34에서 19를 한 번 더 뺀 값이라 −19를 없애지 못해요. 34나 19를 그대로 답하면 문자와 수의 관계를 계산하지 않은 것이고요. 34×19는 덧셈 관계를 곱셈으로 바꾼 오류예요. 왼쪽에만 19를 더하면 오른쪽도 같은 만큼 변해야 한다는 조건을 놓쳐요. 검산하면 53−19=34로 원래 등식이 참이 돼요.",
    core: "x−19=34의 양변에 19를 더하면 x=53!",
  },
  {
    id: "m1u2e148",
    lessonId: L,
    type: "num",
    prompt: "자원 묶음 수의 관계식 <i class='mv'>x</i>÷6=13에서 양변에 같은 수를 곱해 <i class='mv'>x</i>의 값을 구하세요.",
    answer: "78",
    numKind: "int",
    unitLabel: "개",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>x</i>를 6으로 나눈 연산을 없애려면 양변에 6을 곱해요.<br>① (<i class='mv'>x</i>÷6)×6=13×6<br>② <i class='mv'>x</i>=<b>78</b><br>자원은 78개예요.<span class='xh'>오답 경로 격파</span>19는 13에 6을 더한 값이라 나누기 6의 반대 연산을 사용하지 않았어요. 7은 13에서 6을 뺀 값이고, 13÷6은 오른쪽을 다시 나누어 문자와 더 멀어진 계산이에요. 13을 그대로 답하면 묶음 한 단위의 결과만 본 셈이고요. 78을 다시 6으로 나누면 13이 되므로 원래 관계로 되돌아가는지 곱셈과 나눗셈으로 검산할 수 있어요.",
    core: "x÷6=13의 양변에 6을 곱하면 x=78!",
  },
  {
    id: "m1u2e149",
    lessonId: L,
    type: "num",
    prompt: "같은 포장 상자 8개의 전체 질량이 72 kg라서 8<i class='mv'>x</i>=72예요. 양변을 같은 수로 나누어 <i class='mv'>x</i>를 구하세요.",
    answer: "9",
    numKind: "int",
    unitLabel: "kg",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>8<i class='mv'>x</i>에서 상자 한 개의 질량 <i class='mv'>x</i>만 남기려면 양변을 8로 나눠요.<br>① 8<i class='mv'>x</i>÷8=72÷8<br>② <i class='mv'>x</i>=<b>9</b><br>상자 한 개는 9 kg이에요.<span class='xh'>오답 경로 격파</span>64는 72에서 8을 빼 덧셈 관계로 잘못 읽은 값이에요. 80은 72에 8을 더한 값이고요. 576은 양변에 8을 곱해 계수를 더 크게 만든 계산이에요. 72나 8을 그대로 답하면 전체 질량과 상자 수를 한 개의 질량으로 구분하지 못한 거예요. 9 kg짜리 상자 8개가 72 kg인지 8×9=72로 확인해요.",
    core: "8x=72의 양변을 8로 나누면 x=9 kg!",
  },
  {
    id: "m1u2e150",
    lessonId: L,
    type: "num",
    prompt: "등식 −6<i class='mv'>x</i>=54의 양변을 같은 수로 나누어 <i class='mv'>x</i>의 값을 구하세요.",
    answer: "-9",
    numKind: "int",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>−6<i class='mv'>x</i>에서 계수 −6을 없애려면 양변을 −6으로 나눠요.<br>① (−6<i class='mv'>x</i>)÷(−6)=54÷(−6)<br>② <i class='mv'>x</i>=<b>−9</b><span class='xh'>오답 경로 격파</span>9는 음수로 나눈 결과의 부호를 놓친 값이에요. −6은 계수를 그대로 답한 것이고 54는 우변을 옮기지 않은 값이에요. 48은 54에서 6을 빼 곱셈을 덧셈으로 잘못 다룬 결과예요. 양변을 양수 6으로 나누면 −<i class='mv'>x</i>=9까지이므로 <i class='mv'>x</i>=9가 아니에요. 음수 하나와 양수 하나의 나눗셈 결과는 음수예요. 검산하면 −6×(−9)=54로 원래 등식이 참이에요.",
    core: "−6x=54의 양변을 −6으로 나누면 x=−9!",
  },
  {
    id: "m1u2e151",
    lessonId: L,
    type: "num",
    prompt: "등식 5<i class='mv'>x</i>=16의 양변을 같은 수로 나누어 <i class='mv'>x</i>의 값을 <b>소수로</b> 구하세요.",
    answer: "3.2",
    numKind: "dec",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>5<i class='mv'>x</i>에서 계수 5를 없애려면 양변을 5로 나눠요.<br>① 5<i class='mv'>x</i>÷5=16÷5<br>② <i class='mv'>x</i>=<b>3.2</b><span class='xh'>오답 경로 격파</span>11이나 21은 16에서 5를 빼거나 더해 곱셈 관계를 덧셈으로 다룬 값이에요. 0.3125는 5÷16처럼 나누는 순서를 뒤집었을 때 나올 수 있고요. 3은 16÷5의 나머지를 버린 값이라 정확하지 않아요. 양변을 같은 수 5로 나눈 뒤, 소수 답 3.2를 원래 식에 넣어 5×3.2=16이 되는지 확인하면 나눗셈 순서와 소수점 위치를 함께 검산할 수 있어요.",
    core: "5x=16의 양변을 5로 나누면 x=3.2!",
  },
  {
    id: "m1u2e152",
    lessonId: L,
    type: "num",
    prompt: "포장 상자 4개의 질량과 받침 20 kg의 합이 76 kg라서 4<i class='mv'>x</i>+20=76이에요. 등식의 성질을 차례로 사용해 <i class='mv'>x</i>를 구하세요.",
    answer: "14",
    numKind: "int",
    unitLabel: "kg",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>먼저 양변에서 20을 빼고, 이어서 양변을 4로 나눠요.<br>① 4<i class='mv'>x</i>+20−20=76−20, 4<i class='mv'>x</i>=56<br>② 4<i class='mv'>x</i>÷4=56÷4, <i class='mv'>x</i>=<b>14</b><br>상자 한 개는 14 kg이에요.<span class='xh'>오답 경로 격파</span>24는 76−20을 4로 잘못 나눈 값이고, 19는 처음부터 76만 4로 나누어 받침 질량을 함께 네 등분한 오류예요. 56은 첫 단계까지만 한 값이고요. 4를 먼저 빼는 것도 계수와 덧셈항을 혼동한 조작이에요. 두 단계 모두 양변에 같은 조작을 해야 해요. 검산하면 4×14+20=56+20=76이에요.",
    core: "양변에서 20을 빼고 4로 나누면 x=14 kg!",
  },
  {
    id: "m1u2e153",
    lessonId: L,
    type: "word",
    prompt: "등식의 양변에 같은 수를 더하거나 빼고, 같은 수를 곱하거나 0이 아닌 같은 수로 나누어도 등식이 성립하는 규칙을 무엇이라고 하나요?",
    answer: "등식의 성질",
    bank: ["등식의 성질", "교환법칙", "결합법칙", "분배법칙", "이항", "대입", "동류항", "식의 값"],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>등식의 양변에 같은 연산을 해도 같음이 유지되는 규칙을 <b>등식의 성질</b>이라고 해요. 더하기·빼기·곱하기는 같은 수, 나누기는 0이 아닌 같은 수를 사용해요.<span class='xh'>오답 칩 격파</span>'교환법칙'과 '결합법칙'은 계산 순서나 묶는 방법을 바꾸는 규칙이고, '분배법칙'은 괄호 밖의 수를 안의 각 항에 곱하는 규칙이에요. '이항'은 등식의 성질을 바탕으로 항을 옮겨 쓰는 방법이고요. '대입'은 문자에 수를 넣는 것, '동류항'은 문자와 차수가 같은 항, '식의 값'은 대입하여 계산한 결과예요. 질문은 등호의 양쪽에 같은 조작을 적용하는 규칙의 이름을 묻고 있어요.",
    core: "양변에 같은 조작을 해도 같음이 유지되는 규칙은 등식의 성질!",
  },
  {
    id: "m1u2e154",
    lessonId: L,
    type: "word",
    prompt: "등식에서 등호 왼쪽의 식과 오른쪽의 식을 한꺼번에 이르는 말을 무엇이라고 하나요?",
    answer: "양변",
    bank: ["양변", "좌변", "우변", "항", "계수", "상수항", "해", "차수"],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>등호 왼쪽의 식은 좌변, 오른쪽의 식은 우변이고, 이 둘을 한꺼번에 <b>양변</b>이라고 해요. 등식의 성질에서 '양변에 같은 수를 더한다'고 할 때 바로 이 두 식을 함께 가리켜요.<span class='xh'>오답 칩 격파</span>'좌변'은 왼쪽 식 하나만, '우변'은 오른쪽 식 하나만 뜻해요. '항'은 식을 이루는 덧셈의 한 덩어리이고, '계수'는 문자에 곱해진 수, '상수항'은 문자 없는 항이에요. '해'는 방정식을 참이 되게 하는 수이고 '차수'는 문자가 곱해진 횟수예요. 질문은 어느 한쪽이나 식의 부품이 아니라 등호 양쪽을 모두 묶어 부르는 말을 찾고 있어요.",
    core: "좌변과 우변을 합쳐 양변이라고 해요!",
  },
];
