// 중1 수학 II 문자와 식, 레슨 1 문자 사용 단원 종합 평가 풀(22문항).
// 교과서에서는 표현 구조와 함정만 참고하고 수치·문구·소재 결합은 새로 설계했다.
// 유형 13(mcq+multi)/7(num)/2(word), diff 1/2/3 = 9/9/4.
import type { ExamItem } from "./types";
import { mExamSquareChainFig } from "../../ui/examFiguresMath";

const L = "m1u2l1";

export const POOL_M1U2L1: ExamItem[] = [
  {
    id: "m1u2e001",
    lessonId: L,
    type: "mcq",
    prompt: "과학관 체험실에 먼저 들어간 학생이 <i class='mv'>x</i>명이고, 뒤이어 48명이 더 들어왔어요. 체험실에 있는 학생 수를 식으로 나타낸 것은?",
    options: ["48−<i class='mv'>x</i>", "48<i class='mv'>x</i>", "<i class='mv'>x</i>+48", "<i class='mv'>x</i>÷48", "<i class='mv'>x</i>−48"],
    answer: 2,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>처음 있던 <i class='mv'>x</i>명에 새로 들어온 48명을 더하므로 식은 <b><i class='mv'>x</i>+48</b>이에요. <i class='mv'>x</i>가 어떤 수이든 같은 관계가 유지돼요.<span class='xh'>오답 하나씩 격파</span>'48−<i class='mv'>x</i>'와 '<i class='mv'>x</i>−48'은 학생이 나갔을 때의 식이라 상황과 반대예요. '48<i class='mv'>x</i>'는 48명씩 <i class='mv'>x</i>묶음이 있다는 곱셈인데 그런 조건이 없어요. '<i class='mv'>x</i>÷48'도 학생을 48묶음으로 나누는 뜻이라 맞지 않죠. 문장에서 '더 들어왔다'는 변화가 보이면 처음 수에 증가한 수를 더해요. <i class='mv'>x</i>=20을 넣으면 68명이 되는지도 확인해 보면 뜻이 더 분명해져요.",
    core: "처음 수에 더 들어온 수를 더하면 x+48!",
  },
  {
    id: "m1u2e002",
    lessonId: L,
    type: "mcq",
    prompt: "한 묶음에 색연필이 9자루씩 들어 있어요. 같은 묶음이 <i class='mv'>n</i>개일 때 색연필의 전체 자루 수를 나타낸 식은?",
    options: ["<i class='mv'>n</i>+9", "9×<i class='mv'>n</i>", "9−<i class='mv'>n</i>", "<i class='mv'>n</i>÷9", "9÷<i class='mv'>n</i>"],
    answer: 1,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>한 묶음에 9자루가 있고 그런 묶음이 <i class='mv'>n</i>개이므로 전체는 <b>9×<i class='mv'>n</i></b>자루예요. 예를 들어 <i class='mv'>n</i>=3이면 9×3=27자루가 되어 실제 묶음 세기와도 맞아요.<span class='xh'>오답 하나씩 격파</span>'<i class='mv'>n</i>+9'는 묶음 수와 한 묶음의 자루 수를 단순히 더한 값이라 전체 수가 아니에요. '9−<i class='mv'>n</i>'은 묶음이 많아질수록 전체가 줄어드는 이상한 관계가 되고요. '<i class='mv'>n</i>÷9'와 '9÷<i class='mv'>n</i>'은 전체를 나누는 상황에 쓰는 식이에요. 같은 수가 여러 묶음 반복되면 한 묶음의 수×묶음 수로 번역해요.",
    core: "같은 수가 n묶음이면 한 묶음의 수×n!",
  },
  {
    id: "m1u2e003",
    lessonId: L,
    type: "mcq",
    prompt: "사진 파일이 <i class='mv'>p</i>장 들어 있는 폴더를 6개 만들었어요. 모든 폴더에 들어 있는 사진 수를 나타낸 식은?",
    options: ["<i class='mv'>p</i>+6", "<i class='mv'>p</i>−6", "6÷<i class='mv'>p</i>", "<i class='mv'>p</i>÷6", "6×<i class='mv'>p</i>"],
    answer: 4,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>각 폴더에 <i class='mv'>p</i>장씩 있고 폴더가 6개이므로 전체 사진 수는 <b>6×<i class='mv'>p</i></b>장이에요. <i class='mv'>p</i>=10으로 작게 확인하면 폴더 여섯 개에 10장씩, 60장이 나와요.<span class='xh'>오답 하나씩 격파</span>'<i class='mv'>p</i>+6'은 사진 수와 폴더 수처럼 단위가 다른 양을 더해서 전체 사진을 구할 수 없어요. '<i class='mv'>p</i>−6'도 폴더가 늘수록 사진이 줄어드는 식이고요. '6÷<i class='mv'>p</i>'는 폴더 수를 사진 수로, '<i class='mv'>p</i>÷6'은 한 폴더의 사진을 다시 여섯으로 나누는 뜻이에요. 반복되는 같은 양은 곱셈으로 묶어요.",
    core: "p장짜리 폴더 6개는 6×p장!",
  },
  {
    id: "m1u2e004",
    lessonId: L,
    type: "mcq",
    prompt: "스티커 450장 가운데 <i class='mv'>a</i>장을 사용했어요. 남은 스티커 수를 나타낸 식은?",
    options: ["450−<i class='mv'>a</i>", "<i class='mv'>a</i>−450", "450+<i class='mv'>a</i>", "450<i class='mv'>a</i>", "450÷<i class='mv'>a</i>"],
    answer: 0,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>처음 가진 450장에서 사용한 <i class='mv'>a</i>장을 빼면 남은 수는 <b>450−<i class='mv'>a</i></b>장이에요. '남은 것=전체−사용한 것'이라는 관계를 그대로 식으로 옮긴 결과예요.<span class='xh'>오답 하나씩 격파</span>'<i class='mv'>a</i>−450'은 빼는 순서가 뒤집혀 사용량이 전체보다 작을 때 음수가 돼요. '450+<i class='mv'>a</i>'는 스티커를 더 받은 상황의 식이고, '450<i class='mv'>a</i>'는 450장짜리 묶음이 <i class='mv'>a</i>개라는 곱셈이에요. '450÷<i class='mv'>a</i>'는 전체를 <i class='mv'>a</i>묶음으로 나눌 때 한 묶음의 수죠. '남았다'는 말 앞에서는 전체와 사용량의 순서를 확인해요.",
    core: "남은 양은 전체에서 사용한 양을 뺀다!",
  },
  {
    id: "m1u2e005",
    lessonId: L,
    type: "mcq",
    prompt: "기본 이용료가 1,400원이고 체험 코인 한 개마다 350원을 더 내는 기계가 있어요. 코인 <i class='mv'>c</i>개를 사용할 때 내는 금액은?",
    options: ["1,400<i class='mv'>c</i>+350", "350(<i class='mv'>c</i>+1,400)", "1,400−350<i class='mv'>c</i>", "1,400+350<i class='mv'>c</i>", "1,750<i class='mv'>c</i>"],
    answer: 3,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>코인을 쓰지 않아도 기본 이용료 1,400원은 내고, 코인 <i class='mv'>c</i>개의 값은 350×<i class='mv'>c</i>원이에요. 따라서 전체 금액은 <b>1,400+350<i class='mv'>c</i></b>원이에요.<span class='xh'>오답 하나씩 격파</span>'1,400<i class='mv'>c</i>+350'은 기본 이용료가 코인 수만큼 반복되는 식이라 역할이 뒤바뀌었어요. '350(<i class='mv'>c</i>+1,400)'은 1,400에도 350을 곱해 기본료를 엄청 크게 만들고요. '1,400−350<i class='mv'>c</i>'은 코인을 쓸수록 금액이 줄어드는 관계예요. '1,750<i class='mv'>c</i>'은 기본료와 코인 한 개 값을 먼저 더한 뒤 모두 반복한 오류죠. 고정 금액과 개수에 따라 변하는 금액을 구분해요.",
    core: "전체 요금은 고정 금액+한 개 값×개수!",
  },
  {
    id: "m1u2e006",
    lessonId: L,
    type: "multi",
    prompt: "문장을 문자식으로 바르게 나타낸 것을 <b>모두 고르세요.</b>",
    options: [
      "<i class='mv'>x</i>보다 11 큰 수: <i class='mv'>x</i>+11",
      "<i class='mv'>y</i>의 4배보다 3 작은 수: 4(<i class='mv'>y</i>−3)",
      "700에서 <i class='mv'>m</i>을 뺀 수: 700−<i class='mv'>m</i>",
      "<i class='mv'>n</i>개를 5명에게 똑같이 나눈 수: 5÷<i class='mv'>n</i>",
      "한 변이 <i class='mv'>a</i>인 정사각형의 둘레: 4×<i class='mv'>a</i>",
    ],
    answer: [0, 2, 4],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>'<i class='mv'>x</i>보다 11 큰 수'는 <i class='mv'>x</i>+11, '700에서 <i class='mv'>m</i>을 뺀 수'는 700−<i class='mv'>m</i>, 정사각형 둘레는 같은 변 네 개의 합이므로 4×<i class='mv'>a</i>예요.<span class='xh'>오답 하나씩 격파</span>'<i class='mv'>y</i>의 4배보다 3 작은 수'는 먼저 4배를 만든 뒤 3을 빼서 4<i class='mv'>y</i>−3이에요. 4(<i class='mv'>y</i>−3)은 <i class='mv'>y</i>에서 3을 뺀 수 전체의 4배라 뜻이 달라요. '<i class='mv'>n</i>개를 5명에게 나눈 수'는 나누어지는 수가 <i class='mv'>n</i>, 나누는 수가 5이므로 <i class='mv'>n</i>÷5예요. 말의 순서를 연산 순서로 정확히 옮겨야 해요. 작은 수를 넣어 문장과 같은 결과가 나오는지 검산하면 괄호와 순서 오류를 잡을 수 있어요.",
    core: "문장의 기준량과 연산 순서를 그대로 식으로 옮긴다!",
  },
  {
    id: "m1u2e007",
    lessonId: L,
    type: "mcq",
    prompt: "같은 길이의 막대로 정사각형을 가로로 이어 만들어요. 이웃한 정사각형은 한 변의 막대를 함께 사용하므로, 정사각형 한 개를 더 붙일 때마다 막대가 3개씩 늘어요. 정사각형 <i class='mv'>n</i>개에 필요한 막대 수는?",
    figure: mExamSquareChainFig([1, 2, 3]),
    options: ["4<i class='mv'>n</i>", "3<i class='mv'>n</i>+1", "3<i class='mv'>n</i>−1", "<i class='mv'>n</i>+3", "4<i class='mv'>n</i>+1"],
    answer: 1,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>첫 정사각형에는 막대 4개가 필요하고, 이후에는 이미 놓인 한 변을 함께 쓰므로 새 막대가 3개씩 늘어요. 따라서 4+3(<i class='mv'>n</i>−1)=<b>3<i class='mv'>n</i>+1</b>이에요. <i class='mv'>n</i>=1을 넣으면 4가 되어 처음 조건과 맞아요.<span class='xh'>오답 하나씩 격파</span>'4<i class='mv'>n</i>'은 정사각형마다 막대 네 개를 따로 써서 공유하는 한 변을 두 번 센 값이에요. '3<i class='mv'>n</i>−1'은 첫째 값의 보정 방향을 반대로 잡았고요. '<i class='mv'>n</i>+3'은 증가량을 1로 잘못 본 식이에요. '4<i class='mv'>n</i>+1'도 공유 변을 처리하지 못했어요. 패턴식은 첫째 값과 한 단계 증가량을 모두 만족해야 해요.",
    core: "첫째 값 4, 증가량 3이면 3n+1!",
  },
  {
    id: "m1u2e008",
    lessonId: L,
    type: "mcq",
    prompt: "어떤 수 <i class='mv'>k</i>에 대해 세 학생이 문장을 식으로 옮겼어요. '어떤 수의 5배에서 8을 뺀 수'를 바르게 나타낸 학생은?",
    options: ["도윤: 5(<i class='mv'>k</i>−8)", "서아: 8−5<i class='mv'>k</i>", "민재: 5+<i class='mv'>k</i>−8", "하린: 5<i class='mv'>k</i>−8", "유나: (<i class='mv'>k</i>−8)÷5"],
    answer: 3,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>'어떤 수의 5배'를 먼저 만들면 5<i class='mv'>k</i>이고, 그 결과에서 8을 빼므로 <b>5<i class='mv'>k</i>−8</b>이에요. 따라서 하린의 식이 문장의 계산 순서를 정확히 담았어요.<span class='xh'>오답 하나씩 격파</span>도윤의 5(<i class='mv'>k</i>−8)은 <i class='mv'>k</i>에서 8을 먼저 뺀 뒤 전체를 5배 한 식이에요. 서아는 5배한 수를 8에서 빼서 기준과 순서가 뒤집혔고요. 민재는 '5배'를 곱셈이 아니라 5를 더하는 것으로 읽었어요. 유나는 <i class='mv'>k</i>−8을 5로 나눠 배와 나눗셈을 바꿨어요. 'A의 5배에서 B를 뺀다'는 5A−B 순서로 묶어 읽어요.",
    core: "5배를 먼저 만든 뒤 8을 빼면 5k−8!",
  },
  {
    id: "m1u2e009",
    lessonId: L,
    type: "multi",
    prompt: "문자를 사용하는 방법에 대한 설명으로 옳은 것을 <b>모두 고르세요.</b>",
    options: [
      "정해지지 않은 수는 언제나 문자 <i class='mv'>x</i>로만 나타내야 한다",
      "같은 수량을 문장 안에서 반복해 나타낼 때는 같은 문자를 쓸 수 있다",
      "서로 다른 두 수량도 반드시 같은 문자 하나로 나타내야 한다",
      "문자를 사용하면 수량이 달라져도 같은 관계를 식 하나로 나타낼 수 있다",
      "문자가 들어간 식에는 구체적인 수를 넣어 계산할 수 없다",
    ],
    answer: [1, 3],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>같은 수량이 여러 번 나오면 같은 문자를 사용해 그 동일함을 드러낼 수 있어요. 또 문자는 바뀌는 수의 자리표이므로 수량이 달라져도 관계가 같다면 식 하나로 모든 경우를 나타낼 수 있죠.<span class='xh'>오답 하나씩 격파</span>문자는 <i class='mv'>x</i>만 써야 하는 게 아니며 <i class='mv'>a</i>, <i class='mv'>n</i>, <i class='mv'>p</i> 등 어떤 글자도 가능해요. 서로 다른 두 수량을 억지로 같은 문자로 쓰면 둘이 항상 같다는 잘못된 조건이 생겨요. 문자가 든 식에도 구체적인 수를 넣을 수 있고, 그렇게 얻은 결과로 실제 상황을 예측할 수 있어요. 같은 양과 다른 양을 구별해 문자 이름을 정하는 것이 핵심이에요.",
    core: "같은 양은 같은 문자, 다른 양은 다른 문자!",
  },
  {
    id: "m1u2e010",
    lessonId: L,
    type: "mcq",
    prompt: "가로가 <i class='mv'>x</i> cm이고 세로가 12 cm인 직사각형의 둘레를 나타낸 식은?",
    options: ["12<i class='mv'>x</i>", "<i class='mv'>x</i>+12", "2(<i class='mv'>x</i>+12)", "2<i class='mv'>x</i>+12", "<i class='mv'>x</i>÷12"],
    answer: 2,
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>직사각형 둘레는 가로 두 변과 세로 두 변의 합이에요. 따라서 <i class='mv'>x</i>+12+<i class='mv'>x</i>+12=<b>2(<i class='mv'>x</i>+12)</b> cm예요. 가로와 세로를 먼저 더해 두 배 해도 같은 값이 나와요.<span class='xh'>오답 하나씩 격파</span>'12<i class='mv'>x</i>'는 가로와 세로를 곱한 넓이에 해당하고 둘레가 아니에요. '<i class='mv'>x</i>+12'는 가로 한 변과 세로 한 변만 더해 둘레의 절반만 셌어요. '2<i class='mv'>x</i>+12'는 가로는 두 번, 세로는 한 번만 포함했고요. '<i class='mv'>x</i>÷12'는 두 길이의 비를 구하는 식이에요. 도형에서는 어떤 길이를 몇 번 더하는지부터 세어 식을 만들어요.",
    core: "직사각형 둘레는 가로와 세로의 합을 두 배!",
  },
  {
    id: "m1u2e011",
    lessonId: L,
    type: "mcq",
    prompt: "지후의 나이를 <i class='mv'>a</i>살이라 할 때, 지후보다 7살 많은 누나의 나이를 나타낸 식은?",
    options: ["7−<i class='mv'>a</i>", "7<i class='mv'>a</i>", "<i class='mv'>a</i>−7", "<i class='mv'>a</i>÷7", "<i class='mv'>a</i>+7"],
    answer: 4,
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>누나는 지후의 나이 <i class='mv'>a</i>살보다 7살 많으므로 나이는 <b><i class='mv'>a</i>+7</b>살이에요. 지후가 11살이라고 시험해 보면 누나는 18살이 되어 문장과 맞아요.<span class='xh'>오답 하나씩 격파</span>'7−<i class='mv'>a</i>'는 7에서 지후 나이를 빼는 식이라 대부분 음수가 되고, '<i class='mv'>a</i>−7'은 지후보다 7살 어린 사람의 나이예요. '7<i class='mv'>a</i>'는 나이가 일곱 배라는 뜻이라 '7살 많다'와 다르고요. '<i class='mv'>a</i>÷7'은 나이를 일곱으로 나눈 값이에요. '몇 배'는 곱셈, '몇 살 많다'는 덧셈이라는 말의 차이를 구별해요.",
    core: "a보다 7 큰 수는 a+7!",
  },
  {
    id: "m1u2e012",
    lessonId: L,
    type: "multi",
    prompt: "문자식과 그 식이 나타내는 상황이 바르게 연결된 것을 <b>모두 고르세요.</b>",
    options: [
      "18<i class='mv'>x</i>: 한 장에 18점인 도장을 <i class='mv'>x</i>장 모은 총점",
      "600−<i class='mv'>y</i>: 600개에 <i class='mv'>y</i>개를 더한 수",
      "<i class='mv'>m</i>÷4: 사탕 <i class='mv'>m</i>개를 4명에게 똑같이 나눈 한 사람 몫",
      "<i class='mv'>p</i>+23: 상자에 <i class='mv'>p</i>개가 있고 23개를 더 넣은 뒤의 수",
      "5−<i class='mv'>n</i>: <i class='mv'>n</i>보다 5 큰 수",
    ],
    answer: [0, 2, 3],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>18점짜리 도장 <i class='mv'>x</i>장의 총점은 18<i class='mv'>x</i>, <i class='mv'>m</i>개를 4명에게 나눈 몫은 <i class='mv'>m</i>÷4, <i class='mv'>p</i>개에 23개를 더 넣으면 <i class='mv'>p</i>+23이에요.<span class='xh'>오답 하나씩 격파</span>'600−<i class='mv'>y</i>'는 600개에서 <i class='mv'>y</i>개를 뺀 남은 수예요. 더한 수라면 600+<i class='mv'>y</i>가 되어야 하죠. '5−<i class='mv'>n</i>'은 5에서 <i class='mv'>n</i>을 뺀 수이고, <i class='mv'>n</i>보다 5 큰 수는 기준이 <i class='mv'>n</i>이므로 <i class='mv'>n</i>+5예요. 식을 말로 읽을 때도 무엇이 기준이고 무엇이 변하는지 순서를 보존해야 해요. 각 식에 2나 3처럼 작은 수를 넣어 실제 상황과 맞는지 시험하면 연결 오류가 빠르게 드러나요.",
    core: "식의 연산과 상황의 변화 방향을 맞춘다!",
  },
  {
    id: "m1u2e013",
    lessonId: L,
    type: "mcq",
    prompt: "어떤 장식의 조각 수를 세었더니 1단계 6개, 2단계 10개, 3단계 14개였어요. 단계가 하나 늘 때마다 같은 수만큼 증가할 때, <i class='mv'>n</i>단계의 조각 수를 나타낸 식은?",
    options: ["4<i class='mv'>n</i>−2", "4<i class='mv'>n</i>+2", "6<i class='mv'>n</i>", "6<i class='mv'>n</i>+4", "<i class='mv'>n</i>+5"],
    answer: 1,
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>단계가 하나 늘 때 조각 수는 4개씩 증가해요. 증가량 4를 이용해 4<i class='mv'>n</i>에 보정값을 붙이고, <i class='mv'>n</i>=1일 때 6이 되려면 2를 더해야 하므로 식은 <b>4<i class='mv'>n</i>+2</b>예요. 2단계에서도 8+2=10으로 맞아요.<span class='xh'>오답 하나씩 격파</span>'4<i class='mv'>n</i>−2'는 1단계에서 2가 되어 첫째 값을 만족하지 못해요. '6<i class='mv'>n</i>'은 첫째 값 6만 보고 증가량을 6으로 착각한 식이고요. '6<i class='mv'>n</i>+4'는 첫째 값과 증가량을 모두 잘못 결합했어요. '<i class='mv'>n</i>+5'는 1단계에서는 우연히 6이지만 단계마다 1씩만 늘어요. 패턴식은 적어도 두 단계에 넣어 검산해요.",
    core: "증가량 4와 첫째 값 6을 함께 만족하면 4n+2!",
  },
  {
    id: "m1u2e014",
    lessonId: L,
    type: "num",
    prompt: "<i class='mv'>n</i>번째 줄의 구슬 수가 7<i class='mv'>n</i>+3개인 장식이 있어요. 5번째 줄의 구슬 수를 구하세요.",
    answer: "38",
    numKind: "int",
    unitLabel: "개",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>n</i>번째 줄이라는 말에서 <i class='mv'>n</i>=5를 식 7<i class='mv'>n</i>+3에 넣어요.<br>① 7×5=35<br>② 35+3=<b>38</b><br>따라서 5번째 줄에는 38개가 있어요.<span class='xh'>오답 경로 격파</span>7+5+3=15로 계산하면 7<i class='mv'>n</i>을 7+<i class='mv'>n</i>으로 잘못 읽은 거예요. 7×5=35에서 멈추면 식의 +3을 빠뜨린 것이고, 7×(5+3)=56은 괄호가 없는 식에 마음대로 괄호를 만든 계산이에요. 문자 앞의 7은 <i class='mv'>n</i>에 곱해지는 수이고, 덧셈 3은 곱셈을 마친 뒤 처리해요. 마지막에는 1번째 값 10과 규칙의 흐름도 함께 확인해요.",
    core: "n=5를 7n+3에 넣어 38개!",
  },
  {
    id: "m1u2e015",
    lessonId: L,
    type: "num",
    prompt: "인쇄용 종이 530장 가운데 <i class='mv'>a</i>장을 사용했을 때 남은 수는 530−<i class='mv'>a</i>장이에요. <i class='mv'>a</i>=185일 때 남은 종이 수를 구하세요.",
    answer: "345",
    numKind: "int",
    unitLabel: "장",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>사용한 장수 <i class='mv'>a</i>=185를 남은 수 식 530−<i class='mv'>a</i>에 넣어요.<br>① 530−<i class='mv'>a</i><br>② 530−185=<b>345</b><br>따라서 남은 종이는 345장이에요.<span class='xh'>오답 경로 격파</span>530+185=715는 사용한 종이를 오히려 더한 값이라 '남은' 상황과 반대예요. 530−180=350에서 일의 자리 5를 빼지 않으면 350이 되고요. 185−530은 전체와 사용량의 순서를 뒤집은 식이에요. 답 345를 다시 사용량 185와 더하면 530이 되어 처음 전체와 일치하므로 검산도 끝나요. 남은 양 문제는 답+사용량=전체로 확인하면 안전해요.",
    core: "530−185=345, 답과 사용량을 더해 검산!",
  },
  {
    id: "m1u2e016",
    lessonId: L,
    type: "num",
    prompt: "<i class='mv'>n</i>단계 모양에 필요한 연결 부품 수가 4<i class='mv'>n</i>+1개예요. 12단계에 필요한 연결 부품 수를 구하세요.",
    answer: "49",
    numKind: "int",
    unitLabel: "개",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>12단계이므로 <i class='mv'>n</i>=12를 4<i class='mv'>n</i>+1에 넣어요.<br>① 4×12=48<br>② 48+1=<b>49</b><br>필요한 연결 부품은 49개예요.<span class='xh'>오답 경로 격파</span>4+12+1=17은 4<i class='mv'>n</i>을 덧셈으로 읽은 오류예요. 48은 마지막 +1을 빠뜨린 값이고, 4×(12+1)=52는 식에 없는 괄호를 만든 결과예요. 12×5=60은 4<i class='mv'>n</i>+1의 1까지 매번 반복된다고 착각한 계산이고요. 작은 단계 <i class='mv'>n</i>=1에서는 5개가 나오므로, 단계마다 4개씩 증가하는 규칙과도 이어지는지 확인할 수 있어요.",
    core: "12단계는 4×12+1=49개!",
  },
  {
    id: "m1u2e017",
    lessonId: L,
    type: "num",
    prompt: "독서 기록 한 편마다 15점씩 받을 때, <i class='mv'>p</i>편의 점수는 15<i class='mv'>p</i>점이에요. <i class='mv'>p</i>=6일 때 총점을 구하세요.",
    answer: "90",
    numKind: "int",
    unitLabel: "점",
    diff: 1,
    explain:
      "<span class='xh'>정답 풀이</span>기록 수 <i class='mv'>p</i>=6을 총점 식 15<i class='mv'>p</i>에 넣어요. 15<i class='mv'>p</i>는 15×<i class='mv'>p</i>의 곱셈을 줄여 쓴 것이므로 15×6=<b>90</b>점이에요.<span class='xh'>오답 경로 격파</span>15+6=21은 한 편당 점수와 편수를 더한 값이라 총점이 아니에요. 156처럼 두 숫자를 이어 붙이는 것도 곱셈을 복원하지 않은 오류예요. 15÷6은 15점을 여섯 편에 나누는 반대 상황이고, 6×6=36은 한 편당 점수 15를 잃어버린 계산이에요. 같은 점수가 여섯 번 반복되므로 곱셈이며, 90÷6=15로 되돌아가는지 확인하면 관계까지 검산할 수 있어요.",
    core: "15p는 15×p, p=6이면 90점!",
  },
  {
    id: "m1u2e018",
    lessonId: L,
    type: "num",
    prompt: "가로가 <i class='mv'>x</i> cm이고 세로가 14 cm인 직사각형의 둘레는 2(<i class='mv'>x</i>+14) cm예요. <i class='mv'>x</i>=9일 때 둘레를 구하세요.",
    answer: "46",
    numKind: "int",
    unitLabel: "cm",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>x</i>=9를 둘레 식 2(<i class='mv'>x</i>+14)에 넣어요.<br>① 괄호 안: 9+14=23<br>② 2×23=<b>46</b><br>따라서 둘레는 46 cm예요.<span class='xh'>오답 경로 격파</span>23은 가로와 세로를 한 번씩만 더한 값이라 둘레의 절반이에요. 2×9+14=32는 2가 괄호 전체가 아니라 가로에만 곱해진 것으로 계산한 오류고요. 9×14=126은 넓이를 구한 값이에요. 2×9×14는 둘레식의 덧셈을 곱셈으로 바꾼 계산이죠. 실제로 9+14+9+14를 더해도 46이 되어 식과 같은지 확인하면 도형 관계까지 검산돼요.",
    core: "둘레 2(9+14)=46 cm!",
  },
  {
    id: "m1u2e019",
    lessonId: L,
    type: "num",
    prompt: "<i class='mv'>n</i>번째 배열의 조각 수가 5<i class='mv'>n</i>−2개예요. 조각 수가 88개인 배열은 몇 번째인지 구하세요.",
    answer: "18",
    numKind: "int",
    unitLabel: "번째",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>조각 수가 88개이므로 5<i class='mv'>n</i>−2=88로 생각해요. 양쪽에 2를 더하면 5<i class='mv'>n</i>=90이고, 5로 나누면 <i class='mv'>n</i>=<b>18</b>이에요. 따라서 18번째 배열이에요.<span class='xh'>오답 경로 격파</span>88을 그대로 답하면 조각 수와 배열 순서를 혼동한 것이에요. 17은 88을 먼저 5로 나눈 17.6에서 소수 부분을 버린 값이에요. 86은 −2를 없애지 않고 88−2만 계산한 중간값이고, 90은 2를 더한 뒤 5로 나누지 않은 값이에요. 430은 (88−2)×5처럼 나눗셈 방향까지 뒤집은 결과예요. 검산으로 5×18−2=88을 확인하면 구한 순서가 조건에 맞아요.",
    core: "5n−2=88을 풀어 조각 수 88개는 18번째!",
  },
  {
    id: "m1u2e020",
    lessonId: L,
    type: "num",
    prompt: "창고 부품 <i class='mv'>k</i>개를 8개 상자에 똑같이 나누면 한 상자에는 <i class='mv'>k</i>÷8개가 들어가요. <i class='mv'>k</i>=296일 때 한 상자에 들어가는 부품 수를 구하세요.",
    answer: "37",
    numKind: "int",
    unitLabel: "개",
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span><i class='mv'>k</i>=296을 <i class='mv'>k</i>÷8에 넣으면 296÷8이에요. 8×37=296이므로 한 상자에는 <b>37개</b>가 들어가요.<span class='xh'>오답 경로 격파</span>288은 전체에서 상자 수 8만 뺀 값이라 똑같이 나눈 수가 아니에요. 304는 296에 8을 더했고, 2,368은 296×8로 상자 수만큼 전체를 다시 늘린 값이에요. 36은 8×36=288에서 나머지 8을 놓친 몫이고요. 똑같이 나누는 상황에서는 전체를 상자 수로 나눠요. 답 37을 상자 8개에 다시 곱해 296이 되는지 확인하면 나눗셈 방향과 계산을 함께 검산할 수 있어요.",
    core: "k=296을 k÷8에 넣어 한 상자당 37개!",
  },
  {
    id: "m1u2e021",
    lessonId: L,
    type: "word",
    prompt: "아직 정해지지 않은 수나 변할 수 있는 수를 대신하여 쓰는 <b>글자</b>를 무엇이라고 하나요?",
    answer: "문자",
    bank: ["문자", "계수", "상수항", "항", "식의 값", "등식", "방정식", "차수"],
    diff: 2,
    explain:
      "<span class='xh'>정답 풀이</span>아직 정해지지 않았거나 상황에 따라 달라지는 수를 대신해 쓰는 글자는 <b>문자</b>예요. <i class='mv'>x</i>, <i class='mv'>a</i>, <i class='mv'>n</i>처럼 어떤 글자도 수의 자리표가 될 수 있어요.<span class='xh'>오답 칩 격파</span>'계수'는 문자에 곱해진 수이고, '상수항'은 문자 없이 수만으로 된 항이에요. '항'은 식을 이루는 덧셈 단위, '식의 값'은 문자에 수를 넣어 계산한 결과예요. '등식'은 등호로 두 양이 같음을 나타낸 식이고 '방정식'은 특정한 수에서 참이 되는 등식이에요. '차수'는 문자가 곱해진 횟수를 가리켜요. 수를 대신하는 글자 자체의 이름은 문자예요.",
    core: "수를 대신하는 글자의 이름은 문자!",
  },
  {
    id: "m1u2e022",
    lessonId: L,
    type: "word",
    prompt: "수량이나 수량 사이의 관계를 수 대신 <i class='mv'>x</i>, <i class='mv'>a</i> 같은 문자를 사용하여 나타낸 식을 무엇이라고 하나요?",
    answer: "문자를 사용한 식",
    bank: ["문자를 사용한 식", "수직선", "등식의 성질", "소인수분해", "최대공약수", "식의 값", "항등식", "일차방정식"],
    diff: 3,
    explain:
      "<span class='xh'>정답 풀이</span>수량이나 관계를 정해진 수 대신 문자로 나타낸 것은 <b>문자를 사용한 식</b>이에요. 예를 들어 한 개에 9점인 표 <i class='mv'>n</i>개의 총점은 9<i class='mv'>n</i>처럼 나타내며, <i class='mv'>n</i>이 달라져도 관계 하나를 계속 쓸 수 있어요.<span class='xh'>오답 칩 격파</span>'식의 값'은 문자에 특정 수를 넣어 계산한 결과이고, '항등식'과 '일차방정식'은 등호가 있는 식의 종류예요. '등식의 성질'은 양변에 같은 연산을 해도 같음이 유지되는 규칙이고요. '수직선', '소인수분해', '최대공약수'는 수와 연산 단원의 다른 개념이에요. 질문은 문자를 이용해 관계 전체를 표현한 식의 이름을 묻고 있어요.",
    core: "관계를 문자로 나타낸 식은 문자를 사용한 식!",
  },
];
