// 중1 수학 Ⅲ. 좌표평면과 그래프: 단원 종합 평가 풀, 레슨 9 정비례와 그래프의 활용 (m1u3e178~m1u3e200). 2026-07 개보수: e194 수치 재설계(레슨 앵커 회피)·급수 장치→펌프·카트→킥보드.
// 유형 13(mcq+multi)/7(num)/3(word), diff 9/9/5. 활용 그래프는 공통 수치와 MExamChangeGraphSpec에서 문항까지 파생한다.
import type { ExamItem } from "./types";
import { mExamChangeGraphFig, type MExamChangeGraphSpec } from "../../ui/examFiguresMath";

const L = "m1u3l9";
const pointsAt = (rate: number, times: number[]): Array<[number, number]> =>
  times.map((time) => [time, rate * time]);

const WALK = {
  fastRate: 150,
  steadyRate: 90,
  targetTime: 4,
  times: [0, 2, 4, 6],
} as const;
const WALK_SPEC: MExamChangeGraphSpec = {
  xMin: 0,
  xMax: 6,
  yMin: 0,
  yMax: 900,
  xTicks: [...WALK.times],
  yTicks: [0, 180, 360, 600, 900],
  xLabel: "시간(분)",
  yLabel: "거리(m)",
  series: [
    { label: "빠른 걸음", color: "#364FC7", points: pointsAt(WALK.fastRate, [...WALK.times]) },
    { label: "보통 걸음", color: "#E8547E", points: pointsAt(WALK.steadyRate, [...WALK.times]) },
  ],
};

const MACHINE = {
  aRate: 14,
  bRate: 9,
  targetTime: 4,
  times: [0, 2, 4, 6],
} as const;
const MACHINE_SPEC: MExamChangeGraphSpec = {
  xMin: 0,
  xMax: 6,
  yMin: 0,
  yMax: 84,
  xTicks: [...MACHINE.times],
  yTicks: [0, 18, 36, 56, 84],
  xLabel: "시간(분)",
  yLabel: "완성 수(개)",
  series: [
    { label: "기계 A", color: "#2F9E44", points: pointsAt(MACHINE.aRate, [...MACHINE.times]) },
    { label: "기계 B", color: "#E8547E", points: pointsAt(MACHINE.bRate, [...MACHINE.times]) },
  ],
};

const QUAKE = {
  pRate: 9,
  sRate: 6,
  targetDistance: 54,
  times: [0, 3, 6, 9, 12],
} as const;
const QUAKE_SPEC: MExamChangeGraphSpec = {
  xMin: 0,
  xMax: 12,
  yMin: 0,
  yMax: 108,
  xTicks: [...QUAKE.times],
  yTicks: [0, 27, 54, 72, 81, 108],
  xLabel: "시간(초)",
  yLabel: "거리(km)",
  series: [
    { label: "P파", color: "#364FC7", points: pointsAt(QUAKE.pRate, [...QUAKE.times]) },
    { label: "S파", color: "#E8547E", points: pointsAt(QUAKE.sRate, [...QUAKE.times]) },
  ],
};

const PUMP = {
  aRate: 12,
  bRate: 7,
  targetTime: 5,
  times: [0, 5, 10],
} as const;
const PUMP_SPEC: MExamChangeGraphSpec = {
  xMin: 0,
  xMax: 10,
  yMin: 0,
  yMax: 120,
  xTicks: [...PUMP.times],
  yTicks: [0, 35, 60, 70, 120],
  xLabel: "시간(분)",
  yLabel: "보낸 물의 양(L)",
  series: [
    { label: "펌프 A", color: "#0DA5C6", points: pointsAt(PUMP.aRate, [...PUMP.times]) },
    { label: "펌프 B", color: "#F08C2E", points: pointsAt(PUMP.bRate, [...PUMP.times]) },
  ],
};

const DELIVERY = {
  speed: 15,
  targetDistance: 45,
  times: [0, 1, 2, 3, 4],
} as const;
const DELIVERY_SPEC: MExamChangeGraphSpec = {
  xMin: 0,
  xMax: 4,
  yMin: 0,
  yMax: 60,
  xTicks: [...DELIVERY.times],
  yTicks: [0, 15, 30, 45, 60],
  xLabel: "시간(시간)",
  yLabel: "거리(km)",
  series: [
    { label: "배달차", color: "#364FC7", points: pointsAt(DELIVERY.speed, [...DELIVERY.times]) },
    {
      label: "목표 지점",
      color: "#E8547E",
      dashed: true,
      points: DELIVERY.times.map((time) => [time, DELIVERY.targetDistance]),
    },
  ],
};

const walkFastDistance = WALK.fastRate * WALK.targetTime;
const walkSteadyDistance = WALK.steadyRate * WALK.targetTime;
const machineAOutput = MACHINE.aRate * MACHINE.targetTime;
const machineBOutput = MACHINE.bRate * MACHINE.targetTime;
const quakePTime = QUAKE.targetDistance / QUAKE.pRate;
const quakeSTime = QUAKE.targetDistance / QUAKE.sRate;
const quakeGap = quakeSTime - quakePTime;
const pumpAAmount = PUMP.aRate * PUMP.targetTime;
const pumpBAmount = PUMP.bRate * PUMP.targetTime;
const deliveryTime = DELIVERY.targetDistance / DELIVERY.speed;

export const POOL_M1U3L9: ExamItem[] = [
  {
    id: "m1u3e178",
    lessonId: L,
    type: "mcq",
    prompt: `두 사람이 일정한 빠르기로 걸을 때의 그래프예요. 빠른 걸음으로 <b>${WALK.targetTime}분</b> 동안 간 거리는?`,
    figure: mExamChangeGraphFig(WALK_SPEC),
    options: [`${walkFastDistance} m`, `${walkSteadyDistance} m`, "450 m", "900 m", `${WALK.fastRate} m`],
    answer: 0,
    diff: 1,
    explain: `<span class='xh'>정답 풀이</span>빠른 걸음은 1분에 ${WALK.fastRate} m씩 가므로 거리 <i class='mv'>y</i>는 시간 <i class='mv'>x</i>에 정비례해요. ${WALK.targetTime}분일 때 <i class='mv'>y</i>=${WALK.fastRate}×${WALK.targetTime}=<b>${walkFastDistance} m</b>이고, 그래프의 점도 (${WALK.targetTime}, ${walkFastDistance})에 있어요.<span class='xh'>오답 하나씩 격파</span>'${walkSteadyDistance} m'는 보통 걸음의 거리, '450 m'는 1분에 가는 양을 3배만 한 값이에요. '900 m'는 6분 뒤 거리이고, '${WALK.fastRate} m'는 1분에 가는 양을 전체 거리로 착각한 답이에요. 시간과 해당 직선의 점을 함께 확인해요. 가로축의 ${WALK.targetTime}에서 빠른 걸음 직선의 점을 지나 세로축 눈금을 읽어도 같은 값을 얻어요.`,
    core: `빠른 걸음의 거리는 ${WALK.fastRate}×시간이며 ${WALK.targetTime}분에는 ${walkFastDistance} m예요.`,
  },
  {
    id: "m1u3e179",
    lessonId: L,
    type: "num",
    prompt: "한 자루에 <b>420원</b>인 연필을 8자루 살 때의 총액을 쓰세요. (단위: 원)",
    answer: "3360",
    numKind: "int",
    unitLabel: "원",
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>연필 한 자루의 값이 420원으로 일정하므로 자루 수가 2배, 3배가 되면 총액도 같은 배수가 돼요. 자루 수를 <i class='mv'>x</i>, 총액을 <i class='mv'>y</i>라고 하면 <i class='mv'>y</i>=420<i class='mv'>x</i>예요. <i class='mv'>x</i>=8을 넣으면 420×8=<b>3360원</b>이에요.<span class='xh'>헷갈림 격파</span>420+8로 계산하면 단가와 개수처럼 단위가 다른 두 수를 더한 셈이에요. 420×7은 한 자루를 빠뜨린 값이고, 336은 자리 하나를 빠뜨린 값이에요. 420×10−420×2로 다시 계산하면 4200−840=3360이라 검산돼요.",
    core: "총액은 단가×개수이므로 420×8=3360원이에요.",
  },
  {
    id: "m1u3e180",
    lessonId: L,
    type: "word",
    prompt: "물건 한 개에 해당하는 일정한 가격을 뜻하는 말을 고르세요.",
    answer: "단가",
    bank: ["단가", "총액", "개수", "속력", "거리", "시간", "비율", "좌표", "눈금"],
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>물건 한 개에 해당하는 가격을 <b>단가</b>라고 해요. 단가가 일정하면 개수를 <i class='mv'>x</i>, 총액을 <i class='mv'>y</i>라고 할 때 총액=단가×개수이므로 <i class='mv'>y</i>=<i class='mv'>a</i><i class='mv'>x</i> 꼴의 정비례 관계가 돼요.<span class='xh'>낱말 하나씩 격파</span>'총액'은 여러 개를 산 전체 금액, '개수'는 산 물건의 수예요. '속력', '거리', '시간'은 이동 상황의 양이고, '비율'은 두 양의 관계를 나타내는 넓은 말이에요. '좌표'와 '눈금'은 그래프를 읽을 때 쓰는 말이지 한 개의 가격을 뜻하지 않아요. 단가는 총액을 개수로 나누어도 확인할 수 있어요.",
    core: "한 개에 해당하는 일정한 가격은 단가예요.",
  },
  {
    id: "m1u3e181",
    lessonId: L,
    type: "mcq",
    prompt: "포장 기계가 1분에 <b>11상자</b>씩 일정하게 포장해요. 7분 동안 포장한 상자 수는?",
    options: ["18상자", "77상자", "70상자", "4상자", "121상자"],
    answer: 1,
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>매분 11상자씩 일정하게 늘어나므로 시간과 포장 수는 정비례해요. 7분 동안의 포장 수는 11×7=<b>77상자</b>예요. 관계식으로 쓰면 시간 <i class='mv'>x</i>분, 포장 수 <i class='mv'>y</i>상자에 대하여 <i class='mv'>y</i>=11<i class='mv'>x</i>예요.<span class='xh'>오답 하나씩 격파</span>'18상자'는 11과 7을 더한 값이고, '70상자'는 11을 10으로 바꿔 어림한 뒤 그대로 답한 값이에요. '4상자'는 두 수를 빼었고, '121상자'는 11×11로 시간 대신 단위당 양을 두 번 곱했어요. 분당 양과 실제 시간을 곱해야 해요.",
    core: "일정한 분당 생산량에 시간을 곱하면 전체 생산량이 돼요.",
  },
  {
    id: "m1u3e182",
    lessonId: L,
    type: "num",
    prompt: "자전거가 5분마다 <b>1 km</b>씩 일정하게 가요. 18분 동안 간 거리를 쓰세요. (단위: km)",
    answer: "3.6",
    numKind: "dec",
    unitLabel: "km",
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>5분에 1 km를 가므로 1분에는 1÷5=0.2 km를 가요. 일정한 속력으로 움직이므로 시간 <i class='mv'>x</i>분과 거리 <i class='mv'>y</i> km 사이에는 <i class='mv'>y</i>=0.2<i class='mv'>x</i>의 관계가 있어요. 18분에는 0.2×18=<b>3.6 km</b>예요.<span class='xh'>헷갈림 격파</span>18÷5=3.6으로 바로 계산해도 같아요. 3 km라고 쓰면 남은 3분의 이동을 버린 것이고, 90 km는 5와 18을 곱해 단위당 방향을 거꾸로 잡은 값이에요. 20분이면 4 km이므로 18분의 3.6 km는 상황에도 알맞아요. 유한소수 정답은 소수점까지 빠짐없이 입력해요.",
    core: "1분에 0.2 km이므로 18분에는 3.6 km를 가요.",
  },
  {
    id: "m1u3e183",
    lessonId: L,
    type: "mcq",
    prompt: `그래프에서 두 기계가 <b>${MACHINE.targetTime}분</b> 동안 완성한 제품 수의 차는?`,
    figure: mExamChangeGraphFig(MACHINE_SPEC),
    options: [`${machineAOutput}개`, `${machineBOutput}개`, `${machineAOutput - machineBOutput}개`, `${MACHINE.aRate + MACHINE.bRate}개`, `${MACHINE.aRate - MACHINE.bRate}개`],
    answer: 2,
    diff: 1,
    explain: `<span class='xh'>정답 풀이</span>기계 A는 1분에 ${MACHINE.aRate}개이므로 ${MACHINE.targetTime}분에 ${machineAOutput}개, 기계 B는 1분에 ${MACHINE.bRate}개이므로 같은 시간에 ${machineBOutput}개를 완성해요. 따라서 차는 ${machineAOutput}−${machineBOutput}=<b>${machineAOutput - machineBOutput}개</b>예요. 그래프의 ${MACHINE.targetTime}분 점 두 개도 이 값을 나타내요.<span class='xh'>오답 하나씩 격파</span>'${machineAOutput}개'와 '${machineBOutput}개'는 각각 한 기계의 전체 수만 읽은 답이에요. '${MACHINE.aRate + MACHINE.bRate}개'는 분당 양을 더했고, '${MACHINE.aRate - MACHINE.bRate}개'는 1분 동안의 차에서 멈췄어요. 문제의 ${MACHINE.targetTime}분을 반드시 반영해요. 두 직선의 세로 간격은 분당 차 ${MACHINE.aRate - MACHINE.bRate}개가 ${MACHINE.targetTime}번 쌓인 결과라고 보아도 돼요.`,
    core: `${MACHINE.targetTime}분 생산량 ${machineAOutput}개와 ${machineBOutput}개의 차는 ${machineAOutput - machineBOutput}개예요.`,
  },
  {
    id: "m1u3e184",
    lessonId: L,
    type: "word",
    prompt: "P파가 도착한 뒤 S파가 도착할 때까지의 시간 차를 뜻하는 말을 고르세요.",
    answer: "초기 미동 시간",
    bank: ["초기 미동 시간", "도착 거리", "진행 속력", "경보 거리", "비례상수", "원점", "좌표축", "총 이동량"],
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>P파가 먼저 도착한 뒤 S파가 도착할 때까지의 시간 차를 <b>초기 미동 시간</b>이라고 해요. 두 파가 각각 일정한 속력으로 이동한다면 같은 거리까지 걸린 시간을 구하고, 느린 S파의 도착 시각에서 빠른 P파의 도착 시각을 빼서 계산해요.<span class='xh'>낱말 하나씩 격파</span>'도착 거리'와 '경보 거리'는 거리의 크기이고, '진행 속력'은 1초에 가는 거리예요. '비례상수'는 정비례식의 일정한 수, '원점'과 '좌표축'은 그래프의 구성 요소예요. '총 이동량'도 두 도착 시각의 차를 가리키지 않아요.",
    core: "S파 도착 시각에서 P파 도착 시각을 뺀 값이 초기 미동 시간이에요.",
  },
  {
    id: "m1u3e185",
    lessonId: L,
    type: "multi",
    prompt: `P파와 S파가 일정한 속력으로 퍼지는 그래프예요. 진원에서 <b>${QUAKE.targetDistance} km</b> 떨어진 관측소에 대한 설명으로 <b>옳은 것을 모두</b> 고르세요.`,
    figure: mExamChangeGraphFig(QUAKE_SPEC),
    options: [
      `P파는 ${quakePTime}초에 도착한다`,
      `S파는 ${quakeSTime}초에 도착한다`,
      `초기 미동 시간은 ${quakeGap}초이다`,
      `${quakePTime}초일 때 두 파가 간 거리는 같다`,
      "S파가 P파보다 먼저 관측소에 도착한다",
    ],
    answer: [0, 1, 2],
    diff: 2,
    explain: `<span class='xh'>정답 풀이</span>P파는 1초에 ${QUAKE.pRate} km를 가므로 ${QUAKE.targetDistance}÷${QUAKE.pRate}=<b>${quakePTime}초</b>, S파는 1초에 ${QUAKE.sRate} km를 가므로 ${QUAKE.targetDistance}÷${QUAKE.sRate}=<b>${quakeSTime}초</b>에 도착해요. 초기 미동 시간은 ${quakeSTime}−${quakePTime}=<b>${quakeGap}초</b>이므로 앞의 세 설명이 옳아요.<span class='xh'>틀린 설명 격파</span>${quakePTime}초일 때 P파는 ${QUAKE.targetDistance} km, S파는 ${QUAKE.sRate * quakePTime} km를 가서 거리가 다르고, 속력이 더 큰 P파가 먼저 도착해요. 그래프의 같은 거리 눈금에서 두 시각을 따로 읽어야 해요. 시간축에서 ${quakePTime}초와 ${quakeSTime}초의 간격을 확인하면 뺄셈 결과 ${quakeGap}초도 다시 검산할 수 있어요. 단위는 모두 초로 맞아요.`,
    core: `${QUAKE.targetDistance} km에서 P파 ${quakePTime}초, S파 ${quakeSTime}초, 시간 차는 ${quakeGap}초예요.`,
  },
  {
    id: "m1u3e186",
    lessonId: L,
    type: "num",
    prompt: "P파가 7초 동안 63 km를 일정한 속력으로 퍼졌어요. 같은 속력으로 90 km를 가는 데 걸리는 시간을 쓰세요. (단위: 초)",
    answer: "10",
    numKind: "int",
    unitLabel: "초",
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>먼저 P파의 1초당 거리는 63÷7=9 km예요. 같은 속력으로 90 km를 가는 데 걸리는 시간은 90÷9=<b>10초</b>예요. 식으로는 거리 <i class='mv'>y</i>=9<i class='mv'>x</i>에서 90=9<i class='mv'>x</i>를 푼 것과 같아요.<span class='xh'>헷갈림 격파</span>9초는 중간에 구한 초당 거리 9를 시간으로 옮긴 값이에요. 13초는 7과 63의 일부 숫자를 더한 값이고, 630초는 거리와 시간을 곱해 단위를 맞추지 못한 결과예요. 90÷7처럼 처음 시간으로 바로 나누면 두 거리의 비를 반영하지 못해요. 검산하면 9×10=90 km로 목표 거리와 정확히 같아요.",
    core: "63÷7=9 km/s이고 90÷9=10초예요.",
  },
  {
    id: "m1u3e187",
    lessonId: L,
    type: "mcq",
    prompt: "운반 수레가 1초에 <b>1.2 m</b>씩 일정하게 움직여요. 5분 동안 간 거리는?",
    options: ["6 m", "60 m", "72 m", "300 m", "360 m"],
    answer: 4,
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>속력의 단위가 초이므로 먼저 5분을 5×60=300초로 바꿔요. 1초에 1.2 m씩 300초 동안 움직이므로 1.2×300=<b>360 m</b>를 가요. 시간과 거리의 단위를 맞춘 뒤 정비례식을 적용한 계산이에요.<span class='xh'>오답 하나씩 격파</span>'6 m'는 1.2×5로 분을 그대로 초처럼 쓴 값이고, '60 m'는 1분의 초 수만 답했어요. '72 m'는 1.2×60으로 1분 거리에서 멈췄고, '300 m'는 5분을 초로 바꾼 수를 거리로 착각했어요. 계산 전 속력과 시간의 단위를 반드시 맞춰요.",
    core: "5분은 300초이므로 1.2×300=360 m예요.",
  },
  {
    id: "m1u3e188",
    lessonId: L,
    type: "num",
    prompt: "색종이 6묶음의 총액이 <b>5100원</b>이고 묶음마다 가격이 같아요. 한 묶음의 가격을 쓰세요. (단위: 원)",
    answer: "850",
    numKind: "int",
    unitLabel: "원",
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>묶음마다 가격이 같으므로 총액을 묶음 수로 나누면 한 묶음의 가격을 구할 수 있어요. 5100÷6=<b>850원</b>이에요. 묶음 수를 <i class='mv'>x</i>, 총액을 <i class='mv'>y</i>라고 하면 <i class='mv'>y</i>=850<i class='mv'>x</i>의 정비례 관계가 돼요.<span class='xh'>헷갈림 격파</span>5100원은 여섯 묶음의 총액이라 한 묶음 값이 아니에요. 30600원은 나누지 않고 곱한 결과이고, 510원은 5100÷10처럼 묶음 수 6을 사용하지 않았어요. 856원은 가격과 묶음 수를 더한 값이라 단위의 뜻도 맞지 않아요. 850×6=5100으로 다시 곱해 검산해요.",
    core: "총액 5100원을 6묶음으로 나누면 한 묶음은 850원이에요.",
  },
  {
    id: "m1u3e189",
    lessonId: L,
    type: "mcq",
    prompt: `두 펌프가 일정한 비율로 물을 보내는 그래프예요. <b>${PUMP.targetTime}분</b> 뒤의 상황을 옳게 설명한 것은?`,
    figure: mExamChangeGraphFig(PUMP_SPEC),
    options: [
      `펌프 A는 ${PUMP.targetTime}분에 ${PUMP.aRate * 10} L를 보낸다`,
      `펌프 B는 ${PUMP.targetTime}분에 ${pumpAAmount} L를 보낸다`,
      `펌프 B가 펌프 A보다 ${pumpAAmount - pumpBAmount} L 더 보낸다`,
      `펌프 A의 시간은 ${PUMP.targetTime}배이고 물의 양은 3배이다`,
      `펌프 A가 펌프 B보다 ${pumpAAmount - pumpBAmount} L 더 보낸다`,
    ],
    answer: 4,
    diff: 2,
    explain: `<span class='xh'>정답 풀이</span>${PUMP.targetTime}분 뒤 펌프 A는 ${PUMP.aRate}×${PUMP.targetTime}=${pumpAAmount} L, 펌프 B는 ${PUMP.bRate}×${PUMP.targetTime}=${pumpBAmount} L를 보내요. 따라서 A가 B보다 ${pumpAAmount}−${pumpBAmount}=<b>${pumpAAmount - pumpBAmount} L 더</b> 보냈다는 설명이 옳아요.<span class='xh'>오답 하나씩 격파</span>'A는 ${PUMP.aRate * 10} L'는 10분 값을 읽었고, 'B는 ${pumpAAmount} L'는 A의 값을 B에 붙였어요. 'B가 더 보낸다'는 두 직선을 거꾸로 비교했고, '시간 ${PUMP.targetTime}배에 물 3배'는 정비례의 같은 배수 규칙과 맞지 않아요. 같은 시각의 두 점을 비교해요. A의 직선이 같은 시각에서 더 위에 있다는 사실도 A가 더 많은 물을 보냈다는 판단과 일치해요.`,
    core: `${PUMP.targetTime}분에 A ${pumpAAmount} L, B ${pumpBAmount} L이므로 차는 ${pumpAAmount - pumpBAmount} L예요.`,
  },
  {
    id: "m1u3e190",
    lessonId: L,
    type: "word",
    prompt: "초당 이동량이 주어졌는데 시간을 분으로 받은 문제에서, 계산하기 전에 초와 분처럼 서로 다른 단위를 같게 바꾸는 과정을 뜻하는 말을 고르세요.",
    answer: "단위 변환",
    bank: ["단위 변환", "비례상수", "초기 미동 시간", "단가", "총액", "좌표", "눈금", "원점", "사분면"],
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>초당 이동량과 분 단위 시간을 함께 계산하려면 먼저 분을 초로 바꾸거나 초당 양을 분당 양으로 바꾸어 기준을 맞춰야 해요. 이렇게 서로 다른 단위를 같은 기준으로 바꾸는 과정을 <b>단위 변환</b>이라고 해요.<span class='xh'>낱말 하나씩 격파</span>'비례상수'는 정비례식에 곱해진 일정한 수이고, '단가'는 물건 한 단위의 가격, '총액'은 전체 가격이에요. '초기 미동 시간'은 두 지진파의 도착 시각 차예요. '좌표', '사분면', '원점'은 점의 위치를 설명하고 '눈금'은 축의 간격을 나타내므로 시간 단위를 맞추는 과정의 이름이 아니에요. 계산식의 수치뿐 아니라 단위가 서로 같은지 먼저 확인해요.",
    core: "초와 분처럼 다른 단위를 같은 기준으로 바꾸는 과정이 단위 변환이에요.",
  },
  {
    id: "m1u3e191",
    lessonId: L,
    type: "mcq",
    prompt: "A는 시속 4 km, B는 시속 6 km로 각각 일정하게 걸어요. 두 사람이 각각 <b>12 km</b>를 걷는 데 걸리는 시간의 차는?",
    options: ["5시간", "2시간", "6시간", "1시간", "12시간"],
    answer: 3,
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>같은 12 km를 가는 시간을 각각 구해요. A는 12÷4=3시간, B는 12÷6=2시간이므로 시간의 차는 3−2=<b>1시간</b>이에요. 속력이 큰 B가 같은 거리에 먼저 도착한다는 상황과도 맞아요.<span class='xh'>오답 하나씩 격파</span>'5시간'은 두 도착 시간을 더한 값이고, '2시간'과 '3시간이 아닌 6시간'은 한 사람의 시간만 택하거나 속력 차를 잘못 사용한 값이에요. '12시간'은 주어진 거리를 그대로 시간으로 쓴 답이에요. 같은 거리에서는 각자의 거리÷속력을 먼저 계산한 뒤 두 시간을 빼요.",
    core: "12 km에 A는 3시간, B는 2시간이 걸려 차이는 1시간이에요.",
  },
  {
    id: "m1u3e192",
    lessonId: L,
    type: "num",
    prompt: "P파는 1초에 <b>12 km</b>, S파는 1초에 <b>9 km</b>씩 퍼져요. 진원에서 180 km 떨어진 곳의 초기 미동 시간을 쓰세요. (단위: 초)",
    answer: "5",
    numKind: "int",
    unitLabel: "초",
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>180 km까지 P파가 걸리는 시간은 180÷12=15초이고, S파가 걸리는 시간은 180÷9=20초예요. 초기 미동 시간은 S파 도착 시각에서 P파 도착 시각을 뺀 값이므로 20−15=<b>5초</b>예요.<span class='xh'>헷갈림 격파</span>15초나 20초만 쓰면 한 파의 도착 시각을 답한 것이고, 35초는 두 시각을 더한 값이에요. 속력 차 3을 그대로 시간 차로 쓴다면 단위도 근거도 맞지 않아요. P파가 더 빠르므로 먼저 도착하는지 확인해요. 각 도착 시간을 원래 거리식에 넣으면 둘 다 180 km가 나와요.",
    core: "180 km에서 P파 15초, S파 20초이므로 초기 미동 시간은 5초예요.",
  },
  {
    id: "m1u3e193",
    lessonId: L,
    type: "multi",
    prompt: "한 장에 750원인 사진을 인화할 때, 인화 장수 <i class='mv'>x</i>와 총액 <i class='mv'>y</i>에 대한 설명으로 <b>옳은 것을 모두</b> 고르세요.",
    options: [
      "4장을 인화하면 총액은 3000원이다",
      "장수가 2배가 되면 총액도 2배가 된다",
      "0장을 인화하면 총액은 0원이다",
      "그래프는 원점을 지나지 않는다",
      "총액을 장수로 나누면 항상 600이다",
    ],
    answer: [0, 1, 2],
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>총액은 750×장수이므로 <i class='mv'>y</i>=750<i class='mv'>x</i>예요. 4장이면 750×4=<b>3000원</b>이고, 장수가 2배면 총액도 2배가 돼요. 0장일 때는 0원이므로 그래프는 원점을 지나요. 따라서 앞의 세 설명이 옳아요.<span class='xh'>틀린 설명 격파</span>'그래프는 원점을 지나지 않는다'는 <i class='mv'>x</i>=0일 때 <i class='mv'>y</i>=0인 사실과 반대예요. 또 총액을 장수로 나눈 값은 언제나 단가인 750이지 600이 아니에요. 계산값뿐 아니라 식과 그래프의 모양도 함께 검산해요. 2장 1500원, 4장 3000원처럼 같은 배수 규칙도 확인할 수 있어요.",
    core: "총액=750×장수이므로 2배 규칙과 원점 통과가 모두 성립해요.",
  },
  {
    id: "m1u3e194",
    lessonId: L,
    type: "mcq",
    prompt: "P파는 초당 10 km, S파는 초당 6 km로 퍼져요. 150 km 떨어진 곳에서 P파 감지 <b>2초 뒤</b> 경보가 전송되었다면, 경보 뒤 S파 도착까지 남은 시간은?",
    options: ["10초", "25초", "8초", "12초", "2초"],
    answer: 2,
    diff: 3,
    explain: "<span class='xh'>정답 풀이</span>150 km까지 P파는 150÷10=15초, S파는 150÷6=25초가 걸려 초기 미동 시간은 25−15=10초예요. 그러나 경보가 P파 감지 2초 뒤에 전송되었으므로 경보 뒤에 실제로 남은 시간은 10−2=<b>8초</b>예요.<span class='xh'>오답 하나씩 격파</span>'10초'는 경보 전송의 지연을 빼지 않은 초기 미동 시간 그대로이고, '25초'는 S파의 전체 도착 시간이에요. '12초'는 지연 2초를 빼지 않고 거꾸로 더한 값이고, '2초'는 경보 처리에 걸린 시간만 답했어요. 기준 시점을 P파 도착과 경보 전송 중 어느 것으로 잡는지 끝까지 구분해야 해요.",
    core: "초기 미동 10초에서 경보 지연 2초를 빼면 8초가 남아요.",
  },
  {
    id: "m1u3e195",
    lessonId: L,
    type: "num",
    prompt: "펌프가 1초에 <b>2.5 L</b>씩 일정하게 물을 보내요. 450 L를 보내는 데 걸리는 시간을 쓰세요. (단위: 분)",
    answer: "3",
    numKind: "int",
    unitLabel: "분",
    diff: 3,
    explain: "<span class='xh'>정답 풀이</span>먼저 초 단위 시간을 구하면 450÷2.5=180초예요. 1분은 60초이므로 180÷60=<b>3분</b>이에요. 또는 1분에 보내는 양이 2.5×60=150 L이므로 450÷150=3분으로 바로 계산할 수도 있어요.<span class='xh'>헷갈림 격파</span>180은 초 단위 답이라 문제에서 요구한 분 단위로 바꾸지 않은 값이에요. 1125는 450×2.5처럼 전체량과 초당 양을 곱한 결과이고, 7.5는 2.5×3으로 답 3분을 미리 사용한 순환 계산이에요. 450÷60은 물의 양과 시간을 직접 나누어 단위가 맞지 않아요. 마지막에 3분=180초, 2.5×180=450 L로 검산해요.",
    core: "450÷2.5=180초=3분이에요.",
  },
  {
    id: "m1u3e196",
    lessonId: L,
    type: "mcq",
    prompt: `배달차가 일정한 속력으로 가는 거리와 <b>${DELIVERY.targetDistance} km 목표 지점</b>을 함께 나타낸 그래프예요. 두 그래프의 값이 같아지는 시각은?`,
    figure: mExamChangeGraphFig(DELIVERY_SPEC),
    options: ["1시간", `${deliveryTime}시간`, "2시간", "4시간", `${DELIVERY.targetDistance}시간`],
    answer: 1,
    diff: 3,
    explain: `<span class='xh'>정답 풀이</span>배달차는 1시간에 ${DELIVERY.speed} km씩 가므로 거리 <i class='mv'>y</i>=${DELIVERY.speed}<i class='mv'>x</i>예요. 목표 지점은 ${DELIVERY.targetDistance} km이므로 ${DELIVERY.speed}<i class='mv'>x</i>=${DELIVERY.targetDistance}, <i class='mv'>x</i>=<b>${deliveryTime}시간</b>이에요. 그래프에서도 배달차 선과 목표선이 (${deliveryTime}, ${DELIVERY.targetDistance})에서 만나요.<span class='xh'>오답 하나씩 격파</span>'1시간'과 '2시간'에는 각각 ${DELIVERY.speed} km, ${DELIVERY.speed * 2} km라 아직 도착 전이에요. '4시간'에는 ${DELIVERY.speed * 4} km라 목표를 지났고, '${DELIVERY.targetDistance}시간'은 거리값을 시간으로 잘못 읽었어요. 축 단위를 확인해 교점을 읽어요. 세로축의 ${DELIVERY.targetDistance} km에서 목표선을 따라 교점까지 간 뒤 가로축으로 내려가도 ${deliveryTime}시간을 읽을 수 있어요.`,
    core: `${DELIVERY.speed}×시간=${DELIVERY.targetDistance}이므로 목표 도착은 ${deliveryTime}시간이에요.`,
  },
  {
    id: "m1u3e197",
    lessonId: L,
    type: "mcq",
    prompt: "두 인쇄소의 주문 장수 <i class='mv'>x</i>와 총액 <i class='mv'>y</i>가 다음과 같아요. A: (0장, 0원), (2장, 1400원), (4장, 2800원). B: (0장, 500원), (2장, 1900원), (4장, 3300원). 옳은 설명은?",
    options: [
      "A만 정비례 관계이고 식은 <i class='mv'>y</i>=700<i class='mv'>x</i>이다",
      "B만 정비례 관계이고 식은 <i class='mv'>y</i>=700<i class='mv'>x</i>이다",
      "A와 B가 모두 정비례 관계이다",
      "A의 한 장 가격은 1400원이다",
      "B는 0장을 주문하면 총액이 0원이다",
    ],
    answer: 0,
    diff: 3,
    explain: "<span class='xh'>정답 풀이</span>A는 총액÷장수가 1400÷2=2800÷4=700으로 일정하고 0장일 때 0원이므로 <i class='mv'>y</i>=700<i class='mv'>x</i>인 정비례 관계예요. B는 장수가 늘 때 1장당 700원씩 늘지만 0장에도 500원이어서 정비례가 아니에요.<span class='xh'>오답 하나씩 격파</span>'B만 정비례'와 '둘 다 정비례'는 0장일 때의 값을 놓쳤어요. 'A의 한 장 가격은 1400원'은 2장 총액을 한 장 값으로 착각했고, 'B는 0장에 0원'은 표의 500원과 달라요. 단순히 일정하게 증가하는지만 보지 말고 0일 때 0인지도 확인해요.",
    core: "A는 y=700x이지만 B는 0장에도 500원이어서 정비례가 아니에요.",
  },
  {
    id: "m1u3e198",
    lessonId: L,
    type: "num",
    prompt: "P파는 초당 <b>15 km</b>, S파는 초당 <b>10 km</b>로 퍼져요. 초기 미동 시간이 7초인 관측소와 진원 사이의 거리를 쓰세요. (단위: km)",
    answer: "210",
    numKind: "int",
    unitLabel: "km",
    diff: 3,
    explain: "<span class='xh'>정답 풀이</span>두 속력의 공통 이동 거리 30 km를 기준으로 생각해요. P파는 30÷15=2초, S파는 30÷10=3초가 걸리므로 30 km마다 도착 시각 차가 1초 생겨요. 초기 미동 시간이 7초이려면 거리는 30 km의 7배인 <b>210 km</b>예요.<span class='xh'>헷갈림 격파</span>속력 차 5에 7을 곱한 35는 거리 차를 잘못 사용한 값이에요. 120 km에서는 P파 8초, S파 12초로 차가 4초뿐이에요. 검산하면 210÷15=14초, 210÷10=21초이고 21−14=7초라 조건에 맞아요.",
    core: "30 km마다 시간 차가 1초이므로 7초 차이는 210 km에서 생겨요.",
  },
  {
    id: "m1u3e199",
    lessonId: L,
    type: "mcq",
    prompt: "프린터 A는 1분에 18쪽, 프린터 B는 1분에 12쪽씩 일정하게 인쇄해요. 같은 때 시작하여 5분 동안 인쇄한 쪽수의 비 A:B는?",
    options: ["2:3", "5:6", "18:5", "3:2", "30:1"],
    answer: 3,
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>5분 동안 A는 18×5=90쪽, B는 12×5=60쪽을 인쇄해요. 따라서 비는 90:60이고, 두 수를 30으로 나누면 <b>3:2</b>예요. 두 양에 같은 시간 5를 곱했으므로 분당 인쇄량의 비 18:12와도 같아요.<span class='xh'>오답 하나씩 격파</span>'2:3'은 A와 B의 순서를 바꾼 비이고, '5:6'은 시간과 두 비율을 섞었어요. '18:5'는 A의 분당 양과 시간을 비교했고, '30:1'은 90과 60의 차 30을 비로 잘못 나타냈어요. 비의 순서를 문제의 A:B와 맞추고 공통 인수로 간단히 해요.",
    core: "같은 시간 동안의 출력 비는 90:60=3:2예요.",
  },
  {
    id: "m1u3e200",
    lessonId: L,
    type: "mcq",
    prompt: "전동 킥보드가 시속 <b>7.5 km</b>로 일정하게 0.4시간 움직였어요. 계산과 상황 검산을 모두 옳게 한 것은?",
    options: [
      "7.5+0.4=7.9이므로 7.9 km이다",
      "7.5÷0.4=18.75이므로 18.75 km이다",
      "0.4÷7.5이므로 약 0.05 km이다",
      "7.5×4=30이므로 30 km이다",
      "7.5×0.4=3이므로 3 km이고, 1시간 거리보다 짧아 알맞다",
    ],
    answer: 4,
    diff: 2,
    explain: "<span class='xh'>정답 풀이</span>일정한 속력에서 거리는 속력×시간이므로 7.5×0.4=<b>3 km</b>예요. 0.4시간은 1시간보다 짧으니, 1시간 거리 7.5 km보다 결과가 작은 것도 상황에 알맞아요.<span class='xh'>오답 하나씩 격파</span>'7.5+0.4'는 단위가 다른 두 양을 더했고, '7.5÷0.4'와 '0.4÷7.5'는 거리 공식의 계산 방향을 거꾸로 했어요. '7.5×4=30'은 0.4의 소수점을 빠뜨려 4시간 거리로 계산한 값이에요. 식의 종류, 소수 계산, 결과의 크기를 차례로 검산하면 오류를 찾을 수 있어요.",
    core: "7.5×0.4=3 km이며 1시간 거리보다 작아 상황에도 알맞아요.",
  },
];
