// 중2 수학 Ⅳ. 삼각형과 사각형의 성질: 단원 종합 평가 풀, 레슨 10 평행선과 넓이: 모양이 달라도 넓이는 그대로 (m2u4e181~e200) · 책 179~187쪽
// 유형 쿼터: mcq 10(합답형 1) + multi 2 = 12 · num 6 · word 2, diff 8/8/4.
// 함정 계보(교과서 대조): 등적 기본 오개념 정면·넓이 같은 쌍 찾기·전체−부분 빼기·▱ 절반과 4등분·경계 펴기 근거·"높이만 같으면 넓이 같다" 함정.
// 수치 앵커 회피: num 답 26·32·48·30·52·53(레슨 12·15·9·21·18·7·20·34와 교과서 8·5·7 회피, 기사용 66·176·54·11·28 등 회피).
// word 정답: 밑변(e199)·높이(e200).
// 표기: em대시 금지, 뺄셈·차는 −(U+2212, num answer만 ASCII), 기하 기호는 gsym·유니코드 리터럴(mfmt 미사용).
import type { ExamItem } from "./types";
import { gsym } from "../../ui/geoKit";
import { m2ExamEqAreaFig } from "../../ui/examFiguresMath";
const L = "m2u4l10";

export const POOL_M2U4L10: ExamItem[] = [
  {
    id: "m2u4e181", lessonId: L, type: "mcq",
    prompt: `그림에서 두 직선 l과 m은 평행하고, 점 A와 D는 직선 l 위에 있어요. ${gsym("ABC", "tri")}와 ${gsym("DBC", "tri")}의 넓이를 비교하면 어떻게 되나요?`,
    figure: m2ExamEqAreaFig({ mode: "twin", shade: "ABC" }),
    options: [
      "두 삼각형의 넓이는 같아요",
      "△ABC의 넓이가 더 커요",
      "△DBC의 넓이가 더 커요",
      "어느 쪽이 큰지 그림만으로는 알 수 없어요",
      "△DBC의 넓이는 △ABC의 넓이의 2배예요",
    ],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>넓이를 정하는 건 모양이 아니라 밑변과 높이예요.<br>① 두 삼각형은 밑변 BC를 공유해요<br>② 꼭짓점 A와 D는 모두 직선 l 위에 있고, l∥m이라 두 평행선 사이의 거리는 어디서나 일정하니 높이도 같아요<br>③ 밑변도 높이도 같으니 <b>넓이는 같아요</b>.<span class='xh'>오답 하나씩 격파</span>△DBC가 옆으로 길게 누워 있어서 더 커 보이거나, 뾰족해서 작아 보인다고 느끼면 눈의 착각에 속은 거예요. 기울어진 변이 길어져도 밑변과 높이가 그대로면 넓이는 변하지 않아요. '알 수 없다'는 평행선이 높이를 보장한다는 사실을 놓친 답이고, 2배라는 근거는 어디에도 없어요.",
    core: "밑변 공통+평행선 위 꼭짓점=넓이 그대로!",
  },
  {
    id: "m2u4e182", lessonId: L, type: "num",
    prompt: `그림에서 l∥m이고 두 삼각형은 밑변 BC를 공유해요. ${gsym("ABC", "tri")}의 넓이가 26 cm²일 때, 색칠한 ${gsym("DBC", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "twin", shade: "DBC", areaLabel: { in: "ABC", label: "26 cm²" } }),
    answer: "26", numKind: "int", unitLabel: "cm²", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>등적 변형의 가장 기본 상황이에요.<br>① 밑변 BC 공통<br>② 꼭짓점 A, D가 같은 평행선 l 위에 있으니 높이 동일<br>③ 그래서 △DBC의 넓이도 그대로 <b>26 cm²</b>예요.<span class='xh'>계산 실수 격파</span>13을 넣어 보면 밑변도 높이도 그대로인데 넓이만 절반이 된 셈이라 근거가 없고, 52를 적었다면 두 삼각형을 합쳐 버린 거예요. 이 문제에는 계산이 아예 없어요. 밑변과 높이가 같다는 두 가지만 확인되면 넓이는 숫자 하나 건드리지 않고 그대로 옮겨져요. 모양이 달라지면 넓이도 달라질 것 같은 직감을 꺾는 것이 이 단원의 첫걸음이에요.",
    core: "밑변 같고 높이 같으면 넓이는 그대로 26!",
  },
  {
    id: "m2u4e183", lessonId: L, type: "mcq",
    prompt: "두 삼각형의 넓이가 반드시 같아지는 경우로 알맞은 것은 무엇인가요?",
    options: [
      "밑변의 길이가 같고 높이도 같을 때",
      "높이만 같고 밑변의 길이는 다를 때",
      "둘레의 길이가 같을 때",
      "두 삼각형이 같은 직선 위에 놓여 있을 때",
      "한 변의 길이만 서로 같을 때",
    ],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>삼각형의 넓이는 밑변과 높이 두 가지가 함께 정해요.<br>① 넓이는 ½×밑변×높이<br>② 두 값이 모두 같으면 계산 결과도 같을 수밖에 없어요<br>③ 그래서 <b>밑변의 길이가 같고 높이도 같을 때</b>가 답이에요.<span class='xh'>오답 하나씩 격파</span>'높이만 같고 밑변은 다를 때'는 이 단원 최대 함정이에요. 평행선 사이에 있어도 밑변이 다르면 넓이는 달라져요. 둘레가 같은 두 삼각형은 하나는 뾰족하고 하나는 퍼진 모양일 수 있어서 넓이가 제각각이고, 같은 직선 위에 있다는 것은 밑변도 높이도 보장하지 못해요. 한 변만 같은 경우도 나머지 조건이 없으니 넓이를 묶어 주지 못하죠.",
    core: "넓이의 조건은 밑변과 높이, 둘 다 같아야!",
  },
  {
    id: "m2u4e184", lessonId: L, type: "num",
    prompt: `그림처럼 넓이가 64 cm²인 평행사변형 ABCD에 대각선 ${gsym("AC", "seg")}를 그었어요. 색칠한 ${gsym("ABC", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "para", diag: "AC", shade: "ABC" }),
    answer: "32", numKind: "int", unitLabel: "cm²", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>평행사변형의 대각선 하나는 넓이를 정확히 반으로 나눠요.<br>① AB=CD, BC=DA(평행사변형의 대변), AC는 공통<br>② 세 변이 각각 같으니 △ABC≡△CDA(SSS 합동)<br>③ 합동이면 넓이도 같으니 64÷2=<b>32 cm²</b>예요.<span class='xh'>계산 실수 격파</span>16이 나왔다면 4로 나눈 거예요. 4등분은 대각선 두 개를 모두 그었을 때 이야기이고, 지금은 대각선이 하나뿐이라 두 조각만 생겨요. 128은 절반을 구해야 할 자리에서 2배를 해 버린 값이죠. 반으로 나뉜다는 결론이 어림이 아니라 SSS 합동에서 나온다는 것까지 챙기면 흔들리지 않아요.",
    core: "대각선 한 개=합동 두 조각, 넓이 절반!",
  },
  {
    id: "m2u4e185", lessonId: L, type: "multi",
    prompt: `그림처럼 ${gsym("AD", "seg")}∥${gsym("BC", "seg")}인 사다리꼴 ABCD의 두 대각선이 점 O에서 만나요. 넓이가 항상 같은 삼각형 쌍을 모두 고르세요.`,
    figure: m2ExamEqAreaFig({ mode: "trap" }),
    options: [
      "△ABC와 △DBC",
      "△ABD와 △ACD",
      "△ABO와 △DCO",
      "△OAD와 △OBC",
      "△ABO와 △OBC",
    ],
    answer: [0, 1, 2], diff: 2,
    explain: "<span class='xh'>정답 풀이</span>평행한 두 변을 밑변으로 잡는 것이 열쇠예요.<br>① △ABC와 △DBC: 밑변 BC 공통, 꼭짓점 A·D가 평행선 AD 위라 높이 같음(같음)<br>② △ABD와 △ACD: 밑변 AD 공통, 꼭짓점 B·C가 BC 위라 같음<br>③ △ABO=△ABC−△OBC, △DCO=△DBC−△OBC, 같은 것에서 같은 것을 뺐으니 <b>같음</b>.<span class='xh'>오답 하나씩 격파</span>△OAD와 △OBC는 밑변부터 AD와 BC로 길이가 다르고 높이도 달라서, 윗변이 짧은 사다리꼴일수록 △OAD가 훨씬 작아요. △ABO와 △OBC는 꼭짓점 B에서 본 밑변이 AO와 OC인데, 사다리꼴에서는 대각선이 서로를 이등분하지 않아 AO와 OC의 길이가 달라요.",
    core: "빼기 기술: 공통 조각을 빼면 남는 쌍도 같다!",
  },
  {
    id: "m2u4e186", lessonId: L, type: "mcq",
    prompt: `그림처럼 ${gsym("AD", "seg")}∥${gsym("BC", "seg")}인 사다리꼴 ABCD에 두 대각선을 그었어요. ${gsym("ABC", "tri")}와 넓이가 항상 같은 삼각형은?`,
    figure: m2ExamEqAreaFig({ mode: "trap" }),
    options: [
      `${gsym("DBC", "tri")}`,
      `${gsym("ABD", "tri")}`,
      `${gsym("ACD", "tri")}`,
      `${gsym("OBC", "tri")}`,
      "넓이가 같은 삼각형이 없다",
    ],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>밑변과 높이를 확인해요.<br>① △ABC와 △DBC는 밑변 BC를 공유<br>② 꼭짓점 A와 D는 BC에 평행한 직선 AD 위에 있으니 높이가 같아요<br>③ 그래서 넓이가 항상 같은 짝은 <b>△DBC</b>예요.<span class='xh'>오답 하나씩 격파</span>△ABD와 △ACD는 밑변이 AD인 삼각형들이라, BC를 밑변으로 하는 △ABC와는 밑변 길이부터 달라요(이 둘은 자기들끼리 넓이가 같은 다른 짝이에요). △OBC는 △ABC에서 △ABO를 떼어 낸 조각이라 항상 더 작아요. '없다'는 평행선이 높이를 보장해 준다는 사실을 놓친 답이에요.",
    core: "같은 밑변 BC, 평행선 위의 A와 D, 그래서 등적!",
  },
  {
    id: "m2u4e187", lessonId: L, type: "num",
    prompt: `그림처럼 ${gsym("AD", "seg")}∥${gsym("BC", "seg")}인 사다리꼴 ABCD의 두 대각선이 점 O에서 만나요. ${gsym("DBC", "tri")}의 넓이가 71 cm², ${gsym("OBC", "tri")}의 넓이가 23 cm²일 때, 색칠한 ${gsym("DOC", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "trap", shade: "DOC" }),
    answer: "48", numKind: "int", unitLabel: "cm²", diff: 2,
    explain: "<span class='xh'>정답 풀이</span>전체에서 부분을 빼요.<br>① △DBC는 △DOC와 △OBC로 나뉘어요<br>② △DOC=△DBC−△OBC=71−23=<b>48 cm²</b><span class='xh'>계산 실수 격파</span>94가 나왔다면 71+23으로 더해 버린 거예요. △OBC는 △DBC의 바깥 조각이 아니라 안쪽 조각이라 빼야 해요. 뺄 조각을 △ABO로 잘못 잡는 실수도 있는데, 그림에서 색칠된 △DOC가 어느 큰 삼각형에서 어느 조각을 뗀 나머지인지 경계를 먼저 눈으로 확인하면 안전해요. 참고로 △ABO의 넓이도 48 cm²예요. △ABC=△DBC에서 같은 △OBC를 뺀 짝이거든요.",
    core: "△DOC = △DBC − △OBC, 안쪽 조각은 빼기!",
  },
  {
    id: "m2u4e188", lessonId: L, type: "mcq",
    prompt: "평행사변형 ABCD에 두 대각선을 모두 그으면 삼각형 네 개가 생겨요. 그중 하나인 △ABO의 넓이는 평행사변형 ABCD의 넓이의 얼마인가요? (점 O는 두 대각선의 교점이에요.)",
    figure: m2ExamEqAreaFig({ mode: "para", diag: "both" }),
    options: ["4분의 1", "2분의 1", "3분의 1", "4분의 3", "평행사변형의 모양에 따라 달라요"],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>평행사변형의 두 대각선은 서로를 이등분해요.<br>① O가 각 대각선의 중점이라 네 삼각형은 밑변과 높이가 짝끼리 같아요<br>② 그래서 네 조각의 넓이가 모두 같고, 한 조각은 전체의 <b>4분의 1</b>이에요.<span class='xh'>오답 하나씩 격파</span>2분의 1은 대각선을 하나만 그었을 때 생기는 두 조각 이야기예요. 지금은 두 대각선이 네 조각을 만들었죠. 3분의 1이나 4분의 3은 조각 수와 맞지 않는 값이고요. '모양에 따라 다르다'가 가장 그럴듯한 함정인데, 아무리 기울어진 평행사변형이라도 대각선이 서로를 이등분한다는 성질은 변하지 않아서 네 조각은 언제나 똑같이 나뉘어요.",
    core: "대각선 두 개 = 넓이가 같은 네 조각, 각각 ¼!",
  },
  {
    id: "m2u4e189", lessonId: L, type: "mcq",
    prompt: `그림처럼 사각형 ABCD의 꼭짓점 D를 지나고 대각선 ${gsym("AC", "seg")}에 평행한 직선이 변 BC의 연장선과 만나는 점을 E라 하면, 사각형 ABCD와 ${gsym("ABE", "tri")}의 넓이가 같아져요. 그 근거로 알맞은 것은?`,
    figure: m2ExamEqAreaFig({ mode: "bent" }),
    options: [
      `${gsym("ACD", "tri")}와 ${gsym("ACE", "tri")}의 넓이가 같기 때문`,
      `${gsym("ACD", "tri")}와 ${gsym("ACE", "tri")}가 합동이기 때문`,
      `${gsym("ABC", "tri")}와 ${gsym("ACD", "tri")}의 넓이가 같기 때문`,
      "점 E가 변 BC의 중점이기 때문",
      `${gsym("AE", "seg")}가 사각형의 넓이를 이등분하기 때문`,
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>사각형 ABCD를 △ABC와 △ACD로 나눠 생각해요.<br>① △ACD와 △ACE는 밑변 AC를 공유<br>② D와 E가 AC에 평행한 직선 위에 있으니 높이가 같아 <b>넓이가 같아요</b><br>③ 그래서 □ABCD=△ABC+△ACD=△ABC+△ACE=△ABE<span class='xh'>오답 하나씩 격파</span>두 삼각형은 넓이만 같을 뿐 모양이 달라서 합동은 아니에요. 등적 변형은 합동보다 훨씬 헐거운 관계죠. △ABC와 △ACD의 넓이가 같다는 건 주어진 적 없는 정보이고, E는 평행선이 정해 주는 점이지 BC의 중점이라는 보장이 없어요. AE가 넓이를 이등분한다는 것도 근거 없는 말이에요.",
    core: "밑변 AC 공유 + D·E가 평행선 위 = △ACD를 △ACE로 교체!",
  },
  {
    id: "m2u4e190", lessonId: L, type: "num",
    prompt: `그림처럼 평행사변형 ABCD에 두 대각선을 그었더니 넓이가 같은 삼각형 네 개로 나뉘었어요. 평행사변형 ABCD의 넓이가 120 cm²일 때, 색칠한 ${gsym("ABO", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "para", diag: "both", shade: "ABO" }),
    answer: "30", numKind: "int", unitLabel: "cm²", diff: 2,
    explain: "<span class='xh'>정답 풀이</span>두 대각선이 만드는 네 삼각형은 넓이가 모두 같아요.<br>① O는 두 대각선 각각의 중점(평행사변형의 성질)<br>② △ABO=△OBC=△OCD=△AOD<br>③ △ABO=120÷4=<b>30 cm²</b><span class='xh'>계산 실수 격파</span>60이 나왔다면 2로 나눈 것인데, 그건 대각선 하나가 만드는 절반 조각(△ABC)의 넓이예요. 색칠된 조각은 대각선 두 개가 만든 네 조각 중 하나라 4로 나눠야 해요. 240이나 480처럼 커졌다면 나눗셈 자리에서 곱셈을 한 거예요. 조각 수를 그림에서 직접 센 다음 나누는 습관이 실수를 막아 줘요.",
    core: "네 조각 등분, 120÷4=30!",
  },
  {
    id: "m2u4e191", lessonId: L, type: "mcq",
    prompt: `다음은 꺾인 경계를 가진 사각형 ABCD를 넓이가 같은 삼각형 하나로 바꾸는 과정이에요.<br><br>① 대각선 ${gsym("AC", "seg")}를 긋는다.<br>② 점 D를 지나고 ( ㉠ )에 평행한 직선을 긋는다.<br>③ 이 직선이 변 BC의 연장선과 만나는 점을 E라 한다.<br>④ 그러면 사각형 ABCD와 ${gsym("ABE", "tri")}의 넓이가 같다.<br><br>㉠에 알맞은 것은?`,
    figure: m2ExamEqAreaFig({ mode: "bent" }),
    options: [
      `${gsym("AC", "seg")}`,
      `${gsym("AB", "seg")}`,
      `${gsym("BC", "seg")}`,
      `${gsym("AD", "seg")}`,
      `${gsym("BD", "seg")}`,
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>바꿔치기할 조각은 △ACD예요. 이 삼각형의 밑변이 <b>AC</b>이므로, D를 지나 AC에 평행한 직선 위로 꼭짓점을 옮겨야 밑변 공통, 높이 같음이 성립해 △ACD=△ACE가 돼요. 그래서 ㉠은 AC예요.<span class='xh'>오답 하나씩 격파</span>AB나 BC에 평행한 직선을 그으면 △ACD와 밑변을 공유하는 구도가 만들어지지 않아서 넓이 보존이 깨져요. AD는 옮기려는 꼭짓점 D 자신이 속한 변이라 평행선을 그어도 의미가 없고, BD는 다른 대각선이라 △ACD의 밑변과 무관해요. '옮길 꼭짓점의 맞은편 밑변에 평행하게'가 이 작도의 원칙이에요.",
    core: "㉠은 바꿔치기할 조각의 밑변, 대각선 AC!",
  },
  {
    id: "m2u4e192", lessonId: L, type: "mcq",
    prompt: `그림에서 l∥m이고 ${gsym("BC", "seg")}는 직선 m 위에 고정되어 있어요. 꼭짓점이 직선 l 위의 점 A에서 점 D로 미끄러져 이동해도 변하지 <b>않는</b> 것은?`,
    figure: m2ExamEqAreaFig({ mode: "twin", segAD: true }),
    options: [
      "삼각형의 넓이",
      "삼각형의 둘레",
      "∠ABC의 크기",
      "삼각형의 모양",
      "꼭짓점에서 점 B까지의 거리",
    ],
    answer: 0, diff: 3,
    explain: "<span class='xh'>정답 풀이</span>밑변 BC는 고정, 꼭짓점은 평행선 l 위에서만 움직여요. 평행선 사이의 거리는 어디서나 일정하니 높이가 변하지 않고, 밑변도 그대로라 <b>넓이</b>는 아무리 미끄러져도 똑같아요.<span class='xh'>오답 하나씩 격파</span>둘레는 꼭짓점이 옆으로 갈수록 기울어진 두 변이 길어져서 커져요. ∠ABC도 꼭짓점이 이동하면 벌어지거나 좁아지고, 모양 자체가 길쭉해지니 '모양이 그대로'도 틀려요. 꼭짓점에서 B까지의 거리는 두 변 중 하나의 길이라 역시 변하죠. 넓이만 밑변과 높이라는 두 값으로 결정되기 때문에 유일하게 살아남는 불변량이에요.",
    core: "평행선 위를 미끄러지면 모양은 변해도 넓이는 불변!",
  },
  {
    id: "m2u4e193", lessonId: L, type: "num",
    prompt: `그림처럼 사각형 ABCD의 꼭짓점 D를 지나 대각선 ${gsym("AC", "seg")}에 평행한 직선이 변 BC의 연장선과 만나는 점을 E라 했더니 ${gsym("ABE", "tri")}의 넓이가 81 cm²가 되었어요. ${gsym("ABC", "tri")}의 넓이가 29 cm²일 때, ${gsym("ACD", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "bent" }),
    answer: "52", numKind: "int", unitLabel: "cm²", diff: 3,
    explain: "<span class='xh'>정답 풀이</span>등적 변형을 거꾸로 읽어요.<br>① △ABE는 △ABC와 △ACE로 나뉘니 △ACE=81−29=52 cm²<br>② △ACD와 △ACE는 밑변 AC 공통, D와 E가 AC의 평행선 위에 있어 넓이가 같아요<br>③ △ACD=△ACE=<b>52 cm²</b><span class='xh'>계산 실수 격파</span>110이 나왔다면 81+29로 더한 거예요. △ABC는 △ABE의 일부라서 빼야 남은 조각이 나와요. 81을 그대로 쓰면 전체 삼각형과 조각을 구분하지 못한 것이고, 29는 다른 조각을 옮겨 적은 값이죠. '전체−한 조각=다른 조각' 다음에 평행선 등적으로 조각을 바꿔치기하는 두 단계 구조를 순서대로 밟으세요.",
    core: "81−29로 △ACE부터, 평행선이 △ACD로 되돌려 준다!",
  },
  {
    id: "m2u4e194", lessonId: L, type: "mcq",
    prompt: `${gsym("AD", "seg")}∥${gsym("BC", "seg")}인 사다리꼴 ABCD의 두 대각선이 점 O에서 만날 때, ${gsym("ABO", "tri")}와 ${gsym("DCO", "tri")}의 넓이가 같음을 다음과 같이 설명했어요.<br><br>△ABO=△ABC−△( ㉠ ), △DCO=△DBC−△( ㉠ )인데,<br>△ABC=△DBC이므로 △ABO=△DCO이다.<br><br>㉠에 공통으로 들어갈 삼각형은?`,
    figure: m2ExamEqAreaFig({ mode: "trap" }),
    options: [
      `${gsym("OBC", "tri")}`,
      `${gsym("AOD", "tri")}`,
      `${gsym("ABD", "tri")}`,
      `${gsym("ACD", "tri")}`,
      `${gsym("ABO", "tri")}`,
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>그림에서 경계를 확인해요.<br>① △ABC는 대각선 BD에 의해 △ABO와 △OBC로 나뉘어요<br>② △DBC도 대각선 AC에 의해 △DCO와 △OBC로 나뉘죠<br>③ 두 식 모두 빼는 조각이 <b>△OBC</b>이고, 등적인 △ABC와 △DBC에서 같은 조각을 빼니 나머지끼리도 같아요.<span class='xh'>오답 하나씩 격파</span>△AOD는 윗변 쪽 조각이라 △ABC나 △DBC의 일부가 아니에요. △ABD와 △ACD는 밑변이 AD인 큰 삼각형들이라 이 빼기 구조에 등장하지 않고, △ABO는 지금 구하려는 대상 자체라 빼는 조각이 될 수 없어요. 공통으로 빼는 조각은 두 큰 삼각형이 겹쳐 공유하는 아래쪽 △OBC 하나뿐이에요.",
    core: "두 큰 삼각형의 공통 조각 △OBC를 빼는 논법!",
  },
  {
    id: "m2u4e195", lessonId: L, type: "multi",
    prompt: "평행선과 도형의 넓이에 대한 설명으로 옳은 것을 모두 고르세요.",
    options: [
      "밑변이 공통이고 꼭짓점이 밑변과 평행한 직선 위에 있는 두 삼각형은 넓이가 같아요",
      "평행사변형의 두 대각선은 넓이가 같은 네 개의 삼각형을 만들어요",
      "넓이가 같은 두 삼각형은 둘레도 항상 같아요",
      "사각형과 넓이가 같은 삼각형을 평행선을 이용해 작도할 수 있어요",
      "넓이가 같은 두 삼각형은 항상 합동이에요",
    ],
    answer: [0, 1, 3], diff: 3,
    explain: "<span class='xh'>정답 풀이</span>참 셋을 확인해요.<br>① 밑변 공통+평행선 위 꼭짓점: 높이가 같아 등적, 이 단원의 뼈대예요<br>② 두 대각선이 서로를 이등분하니 네 조각의 넓이가 전부 같아요<br>③ 꺾인 경계 펴기처럼, 대각선에 평행한 직선으로 꼭짓점을 옮기면 사각형을 등적인 삼각형으로 바꿀 수 있어요.<span class='xh'>오답 하나씩 격파</span>등적 변형은 모양을 바꾸는 기술이라, 넓이가 같아도 길쭉한 삼각형과 뭉툭한 삼각형은 둘레가 달라요. 합동은 더 강한 조건이죠. 모양까지 완전히 포개져야 하니, 넓이만 같은 두 삼각형을 합동이라 부를 수 없어요. '넓이 같음'은 합동보다 훨씬 헐거운 관계라는 걸 기억하세요.",
    core: "등적은 넓이만 보존, 둘레·모양·합동과는 별개!",
  },
  {
    id: "m2u4e196", lessonId: L, type: "num",
    prompt: `${gsym("AD", "seg")}∥${gsym("BC", "seg")}인 사다리꼴 ABCD의 두 대각선이 점 O에서 만나요. ${gsym("ABO", "tri")}의 넓이가 18 cm², ${gsym("OBC", "tri")}의 넓이가 35 cm²일 때, ${gsym("DBC", "tri")}의 넓이는 몇 cm²인가요? 숫자만 입력하세요.`,
    figure: m2ExamEqAreaFig({ mode: "trap", shade: "DOC" }),
    answer: "53", numKind: "int", unitLabel: "cm²", diff: 3,
    explain: "<span class='xh'>정답 풀이</span>등적인 조각을 다리 삼아 건너가요.<br>① AD∥BC에서 △ABC=△DBC(밑변 BC 공통), 같은 △OBC를 빼면 △DCO=△ABO=18 cm²<br>② △DBC=△DCO+△OBC=18+35=<b>53 cm²</b><span class='xh'>계산 실수 격파</span>35−18=17처럼 빼기로 가면 △DCO를 이미 아는 값에서 또 덜어 낸 셈이라 구조가 어긋나요. △DBC는 색칠된 △DCO와 아래 조각 △OBC를 합친 전체라 더해야 해요. 18을 △DCO로 바꿔치기하는 첫 단계가 이 문제의 심장인데, 그 근거가 '사다리꼴 대각선의 등적 짝'이라는 걸 놓치면 시작부터 막혀요. 검산 삼아 △ABC=18+35=53도 확인되니 △ABC=△DBC와 맞아떨어져요.",
    core: "△ABO를 △DCO로 옮겨 심고 △OBC와 합치면 끝!",
  },
  {
    id: "m2u4e197", lessonId: L, type: "mcq",
    prompt: "평행선과 넓이에 대한 설명으로 옳은 것을 <b>보기</b>에서 모두 고른 것은?",
    bogi: [
      "둘레의 길이가 같은 두 삼각형은 넓이도 항상 같다.",
      "l∥m일 때, 직선 m 위의 밑변을 공유하고 꼭짓점이 직선 l 위에 있는 두 삼각형은 넓이가 같다.",
      "평행사변형의 한 대각선은 그 평행사변형의 넓이를 이등분한다.",
      "넓이가 같도록 모양을 바꾸어도 둘레의 길이는 달라질 수 있다.",
    ],
    options: ["ㄱ, ㄴ", "ㄴ, ㄷ", "ㄷ, ㄹ", "ㄴ, ㄷ, ㄹ", "ㄱ, ㄴ, ㄷ, ㄹ"],
    answer: 3, shuffle: false, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>옳은 것은 <b>ㄴ, ㄷ, ㄹ</b>이에요.<span class='xh'>보기 하나씩 판정</span>ㄱ은 거짓이에요. 둘레가 같아도 길쭉한 삼각형은 납작해서 넓이가 작고, 고른 삼각형은 넓이가 커요. 둘레는 넓이를 정하지 못해요. ㄴ은 참이에요. 밑변 공통에 평행선이 높이를 보장하는 등적 변형의 기본형이죠. ㄷ도 참이에요. 대각선이 만드는 두 삼각형은 대변끼리 같고 대각선이 공통이라 SSS 합동이니 넓이가 반씩이에요. ㄹ도 참이에요. 등적 변형은 넓이만 지키는 기술이라 꼭짓점을 평행선 위에서 밀수록 둘레는 얼마든지 길어져요.",
    core: "넓이의 재료는 밑변과 높이, 둘레는 별개!",
  },
  {
    id: "m2u4e198", lessonId: L, type: "mcq",
    prompt: `${gsym("ABC", "tri")}에서 밑변 ${gsym("BC", "seg")}의 중점을 M이라 하고 ${gsym("AM", "seg")}을 그었어요. ${gsym("ABM", "tri")}과 ${gsym("AMC", "tri")}의 넓이를 비교하면?`,
    options: [
      "두 삼각형의 넓이는 서로 같다",
      "△ABM이 항상 더 크다",
      "△AMC가 항상 더 크다",
      "삼각형의 모양에 따라 다르다",
      "AM의 길이를 알아야 비교할 수 있다",
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>밑변과 높이로 비교해요.<br>① M이 중점이니 BM=MC (밑변의 길이가 같음)<br>② 두 삼각형 모두 꼭짓점이 A라서, A에서 직선 BC까지의 거리인 높이도 공통<br>③ 밑변 같고 높이 같으니 <b>넓이가 같아요</b>. 꼭짓점 A와 밑변의 중점을 이은 선분은 삼각형의 넓이를 반으로 나누는 셈이죠.<span class='xh'>오답 하나씩 격파</span>어느 한쪽이 항상 크다는 답은 눈에 보이는 기울어진 모양에 속은 거예요. 삐딱한 삼각형이라도 밑변 절반과 공통 높이라는 두 재료가 똑같아요. '모양에 따라 다르다'와 'AM의 길이가 필요하다'는 넓이 계산에 AM이 아예 등장하지 않는다는 걸 놓친 답이에요. 넓이는 밑변과 높이만 보면 돼요.",
    core: "중점으로 밑변 반반 + 높이 공통 = 넓이도 반반!",
  },
  {
    id: "m2u4e199", lessonId: L, type: "word",
    prompt: "삼각형의 넓이를 구할 때 기준으로 삼는 변을 ___이라고 해요. 등적 변형에서는 두 삼각형이 이 변을 공유할 때 높이만 비교하면 돼요.",
    answer: "밑변",
    bank: ["밑변", "높이", "빗변", "대변", "대각선", "수선", "중점", "둘레"],
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>넓이 계산의 기준이 되는 변이 <b>밑변</b>이에요. 평행선과 넓이 단원에서는 두 삼각형이 밑변을 공유하고 꼭짓점이 밑변과 평행한 직선 위에 있으면 높이까지 같아져 넓이가 같다는 사실을 계속 써먹었죠.<span class='xh'>낱말 하나씩 격파</span>높이는 밑변에서 꼭짓점까지의 수직 거리라 변이 아니에요. 빗변은 직각삼각형에서 직각의 대변을 부르는 전용 이름이고, 대변은 마주 보는 변이라는 상대적인 관계, 대각선은 사각형에서 꼭짓점을 잇는 선분이에요. 수선은 수직으로 내린 선, 중점은 선분의 한가운데 점, 둘레는 변의 길이를 모두 더한 값이라 전부 '기준이 되는 변'이라는 설명과 맞지 않아요.",
    core: "넓이의 기준 변 = 밑변, 짝꿍은 높이!",
  },
  {
    id: "m2u4e200", lessonId: L, type: "word",
    prompt: "삼각형의 넓이는 ½×밑변×___로 구해요. 평행선 사이에서는 이 값이 어디서나 일정해서 등적 변형이 가능해요.",
    answer: "높이",
    bank: ["높이", "밑변", "넓이", "둘레", "대각선", "반지름", "꼭지각", "빗변"],
    diff: 1,
    explain: "<span class='xh'>정답 풀이</span>넓이 공식의 남은 자리는 <b>높이</b>, 곧 밑변에서 마주 보는 꼭짓점까지의 수직 거리예요. 평행한 두 직선 사이의 거리는 어디서나 일정하니, 꼭짓점이 평행선 위 어디로 미끄러져도 높이가 그대로라 넓이가 보존돼요. 이것이 등적 변형의 원리죠.<span class='xh'>낱말 하나씩 격파</span>밑변은 이미 식의 앞자리에 있으니 같은 재료를 두 번 넣을 수 없어요. 넓이는 이 계산의 결과라 재료 자리에 올 수 없고, 둘레는 넓이와 무관한 값이에요. 대각선은 사각형 이야기이고, 반지름은 원의 부품이에요. 꼭지각은 이등변삼각형의 각, 빗변은 직각삼각형의 변이라 넓이 공식의 빈칸과 어울리지 않아요.",
    core: "½×밑변×높이, 평행선은 높이를 지켜 준다!",
  },
];
