// 중2 수학 Ⅴ. 도형의 닮음과 피타고라스 정리: 단원 종합 평가 풀, 레슨 5 숨은 닮음 찾기: 겹친 삼각형 (m2u5e074~e091) · 책 202~203쪽
// 유형 쿼터: mcq 9 + multi 2 = 11 · num 5 · word 2, diff 7/7/4.
// 함정 계보(교과서 대조): 뒤집힌 닮음 대응 오류, 나비 비 뒤집기, 수선 곱=제곱, 그림자 비 방향.
// 수치 앵커 회피: 레슨 4·8·6→8·3·9·4→12·9·12·4→3·6²=9×BD→4·막대1m·그림자2m·탑24m→12m·정삼각형15cm·60° 회피(브리프 준수).
// word 정답: 맞꼭지각(e090)·수선(e091).
// 표기: em대시 금지, 뺄셈·차는 −(U+2212), 기하 기호는 gsym·유니코드 리터럴(mfmt 미사용).
import type { ExamItem } from "./types";
import { gsym } from "../../ui/geoKit";
import { m2ExamTriSplitFig, m2ExamXCrossFig, m2ExamRightAltFig } from "../../ui/examFiguresMath";
const L = "m2u5l5";

export const POOL_M2U5L5: ExamItem[] = [
  {
    id: "m2u5e074", lessonId: L, type: "mcq",
    prompt: `그림에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있고 ∠ADE=∠ACB예요. ${gsym("AB", "seg")}=16 cm, ${gsym("AD", "seg")}=9 cm, ${gsym("AE", "seg")}=8 cm일 때, ${gsym("AC", "seg")}의 길이는?`,
    figure: m2ExamTriSplitFig({ B: 62, C: 54, t: 0.56, mode: "swapped", labels: { AD: "9", AE: "8" }, marks: [{ at: "ADE", label: "●" }, { at: "ACB", label: "●" }] }),
    options: [
      "18 cm",
      "14 cm",
      "16 cm",
      "12 cm",
      "24 cm",
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>∠A는 두 삼각형이 함께 가진 공통각이고, ∠ADE=∠ACB예요. 그래서 △ADE와 △ACB가 닮음이에요(대응: A↔A, D↔C, E↔B).<br>① 대응변의 비: AD:AC=AE:AB<br>② 9:AC=8:16=1:2<br>③ AC=9×2=<b>18 cm</b><span class='xh'>오답 하나씩 격파</span>14 cm를 대입하면 9:14가 8:16=1:2와 달라 대응변의 비가 어긋나요. ∠ADE=∠ACB라 D는 C에, E는 B에 대응한다는 짝을 놓치면 이렇게 틀린 값에 닿기 쉬워요. 16 cm는 AB를 그대로 옮긴 값이고, 12 cm와 24 cm도 비례식 9:AC=1:2를 만족하지 않아요. 겹친 두 삼각형은 어느 변이 어느 변에 대응하는지부터 정확히 맞추는 게 핵심이에요.",
    core: "겹친 삼각형은 대응부터, 뒤집힌 닮음은 D↔C·E↔B!",
  },
  {
    id: "m2u5e075", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("AB", "seg")}∥${gsym("DC", "seg")}이고 두 선분 ${gsym("AC", "seg")}와 ${gsym("BD", "seg")}가 점 O에서 만나요. ${gsym("OA", "seg")}=8 cm, ${gsym("OC", "seg")}=12 cm, ${gsym("OB", "seg")}=6 cm일 때, ${gsym("OD", "seg")}의 길이는?`,
    figure: m2ExamXCrossFig({ rTop: [8, 12], rSide: [6, 9], labels: { OA: "8", OC: "12", OB: "6", OD: "x" }, paraMarks: true }),
    options: [
      "4 cm",
      "9 cm",
      "8 cm",
      "12 cm",
      "18 cm",
    ],
    answer: 1, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>AB∥DC이므로 엇각이 같고, 맞꼭지각 ∠AOB=∠COD도 같아요. 그래서 △OAB∽△OCD예요.<br>① 대응변의 비: OA:OC=OB:OD<br>② 8:12=6:OD, 즉 2:3=6:OD<br>③ 2×OD=18, OD=<b>9 cm</b><span class='xh'>오답 하나씩 격파</span>4 cm는 비를 OA:OC=OD:OB로 뒤집어 세운 값이에요, OA와 OC가 대응하면 OB와 OD가 대응하므로 6이 OD 자리와 짝을 이루면 안 돼요. 8 cm와 12 cm는 각각 OA, OC를 그대로 옮긴 값이고, 18 cm는 2×OD=18에서 OD를 구하지 않고 18을 그대로 답한 값이에요. 대응변끼리 같은 순서로 비례식을 세우는 게 중요해요.",
    core: "AB∥DC면 △OAB∽△OCD, 맞꼭지각+엇각으로 나비 닮음!",
  },
  {
    id: "m2u5e076", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("ABC", "tri")}는 ∠A=90°인 직각삼각형이고, 점 A에서 빗변 ${gsym("BC", "seg")}에 내린 수선의 발이 D예요. ${gsym("BD", "seg")}=16 cm, ${gsym("DC", "seg")}=25 cm일 때, ${gsym("AD", "seg")}의 길이는?`,
    figure: m2ExamRightAltFig({ bd: 16, dc: 25, labels: { BD: "16", DC: "25", AD: "x" } }),
    options: [
      "41 cm",
      "9 cm",
      "20 cm",
      "30 cm",
      "24 cm",
    ],
    answer: 2, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>∠A=90°이고 AD가 빗변에 내린 수선이면 ∠ADB=∠CDA=90°이고, ∠B=∠CAD(각각 ∠BAD의 여각)라서 △ABD∽△CAD예요.<br>① 대응변의 비: BD:AD=AD:DC<br>② AD×AD=BD×DC=16×25=400<br>③ 제곱하여 400이 되는 양수는 20이므로 AD=<b>20 cm</b><span class='xh'>오답 하나씩 격파</span>41 cm는 BD와 DC를 더한 값이라 빗변 BC의 길이지 수선이 아니에요. 9 cm는 25에서 16을 뺀 값으로 근거가 없고요. 30 cm와 24 cm는 각각 제곱하면 900, 576이라 400과 달라서 AD×AD=16×25를 만족하지 못해요. 수선은 나뉜 두 부분의 곱이 곧 그 수선을 제곱한 값이 되는 관계를 기억해야 해요.",
    core: "빗변의 수선은 △ABD∽△CAD, 수선의 제곱 = 두 부분의 곱!",
  },
  {
    id: "m2u5e077", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("ABC", "tri")}는 ∠A=90°인 직각삼각형이고, 점 A에서 빗변 ${gsym("BC", "seg")}에 수선 ${gsym("AD", "seg")}를 내렸어요. 이때 서로 닮은 세 삼각형의 대응 순서를 바르게 나타낸 것은?`,
    figure: m2ExamRightAltFig({ bd: 12, dc: 16, rightAtA: true }),
    options: [
      `${gsym("ABC", "tri")}∽${gsym("DBA", "tri")}∽${gsym("DAC", "tri")}`,
      `${gsym("ABC", "tri")}∽${gsym("DAB", "tri")}∽${gsym("DAC", "tri")}`,
      `${gsym("ABC", "tri")}∽${gsym("ADB", "tri")}∽${gsym("ADC", "tri")}`,
      `${gsym("ABC", "tri")}∽${gsym("DBA", "tri")}∽${gsym("DCA", "tri")}`,
      `${gsym("ABC", "tri")}∽${gsym("BDA", "tri")}∽${gsym("DAC", "tri")}`,
    ],
    answer: 0, diff: 3,
    explain: "<span class='xh'>정답 풀이</span>∠A=90°이고 AD가 빗변에 내린 수선이면, 큰 직각삼각형과 두 작은 직각삼각형이 모두 닮음이에요. 대응은 '직각↔직각, 공통각↔공통각' 순으로 맞춰요.<br>① △DBA: ∠B가 공통, 직각이 D에 있으니 A↔D, B↔B, C↔A<br>② △DAC: ∠C가 공통, 직각이 D에 있으니 A↔D, B↔A, C↔C<br>③ 그래서 <b>△ABC∽△DBA∽△DAC</b>예요.<span class='xh'>오답 하나씩 격파</span>'△DAB'와 '△BDA'는 직각인 꼭짓점 D가 대응 순서의 첫 자리(△ABC의 A 자리)에 오지 않아 순서가 어긋나요. '△ADB', '△ADC'도 A와 D의 자리가 바뀌어 직각끼리 짝지어지지 않고요. '△DCA'는 마지막 두 글자 C, A의 순서가 뒤바뀌어 공통각 ∠C가 엉뚱한 자리에 놓여요. 닮음 기호는 대응하는 꼭짓점을 같은 순서로 적어야 해요.",
    core: "수선이 만든 세 닮은 직각삼각형, 직각과 공통각을 같은 자리에!",
  },
  {
    id: "m2u5e078", lessonId: L, type: "mcq",
    prompt: `같은 시각에 길이가 2 m인 막대를 똑바로 세웠더니 그림자가 5 m였어요. 바로 그때 어떤 건물의 그림자 길이가 35 m였다면, 이 건물의 높이는 몇 m일까요?`,
    options: [
      "87.5 m",
      "70 m",
      "17.5 m",
      "12 m",
      "14 m",
    ],
    answer: 4, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>같은 시각에는 햇빛이 이루는 각이 같아서, 막대와 그림자로 이루는 삼각형과 건물과 그림자로 이루는 삼각형이 서로 닮음이에요.<br>① (높이):(그림자)의 비가 같아요<br>② 2:5=(건물 높이):35<br>③ 5×(높이)=70, 높이=<b>14 m</b><span class='xh'>오답 하나씩 격파</span>87.5 m는 비를 5:2로 뒤집어 35×5÷2로 계산한 값인데, 그림자 5보다 막대 2가 짧으므로 높이도 그림자보다 짧아야 해요. 70 m는 35에 2를 곱하기만 하고 5로 나누지 않은 값이고, 17.5 m는 35를 2로 나눈 값이라 막대 길이 5와 2를 뒤섞은 거예요. 12 m는 비례식 2:5=높이:35를 만족하지 않아요. '높이:그림자' 순서를 두 삼각형에서 똑같이 맞추는 게 핵심이에요.",
    core: "같은 시각 그림자는 닮음, 높이:그림자 비를 그대로 옮겨요!",
  },
  {
    id: "m2u5e079", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("ABC", "tri")}는 ∠A=90°인 직각삼각형이고 점 A에서 빗변 ${gsym("BC", "seg")}에 수선 ${gsym("AD", "seg")}를 내렸어요. 다음 중 <b>옳지 않은</b> 비례식은?`,
    figure: m2ExamRightAltFig({ bd: 4, dc: 9, rightAtA: true }),
    options: [
      `${gsym("BD", "seg")}:${gsym("AD", "seg")}=${gsym("AD", "seg")}:${gsym("DC", "seg")}`,
      `${gsym("AB", "seg")}:${gsym("BD", "seg")}=${gsym("BC", "seg")}:${gsym("AB", "seg")}`,
      `${gsym("AC", "seg")}:${gsym("DC", "seg")}=${gsym("BC", "seg")}:${gsym("AC", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("BD", "seg")}=${gsym("AB", "seg")}:${gsym("BC", "seg")}`,
      `${gsym("DC", "seg")}:${gsym("AC", "seg")}=${gsym("AC", "seg")}:${gsym("BC", "seg")}`,
    ],
    answer: 3, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>∠A=90°이고 AD가 빗변에 내린 수선이면 △ABC∽△DBA∽△DAC예요. 서로 닮은 세 직각삼각형의 대응변에서 세 가지 곱셈 관계가 나와요.<br>① AD×AD=BD×DC이므로 BD:AD=AD:DC<br>② AB×AB=BD×BC이므로 AB:BD=BC:AB<br>③ AC×AC=DC×BC이므로 AC:DC=BC:AC<br>그런데 AD:BD=AB:BC는 어느 닮음에서도 나오지 않는 짝이라 옳지 않아요.<span class='xh'>오답 하나씩 격파</span>BD:AD=AD:DC, AB:BD=BC:AB, DC:AC=AC:BC는 각각 AD, AB, AC를 제곱한 값이 두 변의 곱과 같다는 관계를 비례식으로 옮긴 참인 식이에요. 반면 AD:BD는 DC:AD와, AB:BC는 BD:AB와 짝을 이루므로 AD:BD=AB:BC처럼 둘을 이어 붙이면 대응이 어긋나 성립하지 않아요.",
    core: "수선이 만든 세 닮음의 곱셈식, 대응 순서까지 맞아야 참!",
  },
  {
    id: "m2u5e080", lessonId: L, type: "mcq",
    prompt: `한 변의 길이가 9 cm인 정삼각형 ${gsym("ABC", "tri")}가 있어요. 변 ${gsym("BC", "seg")} 위의 점 D는 ${gsym("BD", "seg")}=3 cm를 만족하고, 변 ${gsym("AC", "seg")} 위의 점 E에 대하여 ∠ADE=60°예요. 이때 ${gsym("AE", "seg")}의 길이는?`,
    options: [
      "2 cm",
      "7 cm",
      "6 cm",
      "4.5 cm",
      "3 cm",
    ],
    answer: 1, diff: 3,
    explain: "<span class='xh'>정답 풀이</span>정삼각형이라 ∠B=∠C=60°이고 ∠ADE=60°예요. 점 D에서 직선 BC 위의 각을 보면 ∠ADB+60°+∠EDC=180°이고, △ABD에서 ∠BAD+∠ADB=120°라서 ∠EDC=∠BAD가 돼요.<br>① 그래서 △ABD∽△DCE (∠B=∠C, ∠BAD=∠CDE)<br>② AB:DC=BD:CE, 즉 9:6=3:CE<br>③ CE=2, AE=AC−CE=9−2=<b>7 cm</b><span class='xh'>오답 하나씩 격파</span>2 cm는 CE까지만 구하고 AE로 바꾸지 않은 값이에요, AE=AC−CE=9−2를 마저 해야 해요. 6 cm는 DC를 그대로 옮긴 값이고, 3 cm는 BD를 그대로 답한 거예요. 4.5 cm는 비를 9:6=CE:3으로 뒤집어 세운 값인데, 대응은 BD와 CE가 짝이라 9:6=3:CE가 맞아요. 정삼각형의 세 60° 각이 닮음을 숨겨 두었다는 걸 알아채는 게 열쇠예요.",
    core: "정삼각형 속 세 60° 각이 △ABD∽△DCE를 숨겨요!",
  },
  {
    id: "m2u5e081", lessonId: L, type: "mcq",
    prompt: `겹쳐 있는 두 삼각형에서 숨은 닮음을 찾는 과정을 순서대로 늘어놓으려고 해요. 바르게 나열한 것은?`,
    bogi: [
      "두 삼각형이 함께 나눠 가진 공통각을 찾는다.",
      "주어진 조건에서 크기가 같은 또 다른 한 쌍의 각을 찾는다.",
      "두 쌍의 대응각이 같으므로 두 삼각형이 닮음(AA)이라고 결론짓는다.",
    ],
    options: [
      "ㄷ → ㄱ → ㄴ",
      "ㄷ → ㄴ → ㄱ",
      "ㄱ → ㄴ → ㄷ",
      "ㄱ → ㄷ → ㄴ",
      "ㄴ → ㄷ → ㄱ",
    ],
    answer: 2, shuffle: false, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>겹쳐 있는 두 삼각형에서 숨은 닮음을 찾을 때는 각을 단서로 삼아요.<br>ㄱ: 두 삼각형이 함께 나눠 가진 공통각을 먼저 찾아요.<br>ㄴ: 주어진 조건에서 크기가 같은 또 한 쌍의 각을 찾아요.<br>ㄷ: 두 쌍의 대응각이 같으니 AA 닮음이라고 결론지어요.<br>그래서 순서는 ㄱ → ㄴ → ㄷ예요.<span class='xh'>오답 하나씩 격파</span>나머지 네 순서는 모두 결론인 ㄷ이 맨 앞이나 중간에 와요. 아직 같은 각을 두 쌍 확인하지도 않았는데 닮음이라고 단정하는 셈이라, 근거보다 결론이 앞서는 순서는 전부 논리가 뒤집혀요. 각 두 쌍이라는 근거를 모두 모은 다음에 AA 닮음이라는 결론으로 마무리하는 ㄱ → ㄴ → ㄷ만 옳은 순서예요.",
    core: "숨은 닮음은 공통각 찾고, 또 한 각 찾고, AA로 마무리!",
  },
  {
    id: "m2u5e082", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("AB", "seg")}∥${gsym("DC", "seg")}이고 두 선분 ${gsym("AC", "seg")}와 ${gsym("BD", "seg")}가 점 O에서 만나요. 다음 중 옳은 설명은?`,
    figure: m2ExamXCrossFig({ rTop: [8, 6], rSide: [8, 6], paraMarks: true }),
    options: [
      `${gsym("OAB", "tri")}와 ${gsym("OCD", "tri")}는 서로 닮음이에요`,
      `${gsym("OAB", "tri")}와 ${gsym("OCD", "tri")}는 항상 서로 합동이에요`,
      `∠OAB와 ∠OCD의 크기는 서로 달라요`,
      `${gsym("OA", "seg")}:${gsym("OC", "seg")}와 ${gsym("OB", "seg")}:${gsym("OD", "seg")}의 값은 서로 달라요`,
      `${gsym("OAB", "tri")}와 ${gsym("OCD", "tri")}의 넓이는 항상 같아요`,
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>AB∥DC이므로 엇각 ∠OAB=∠OCD, ∠OBA=∠ODC가 성립하고, 맞꼭지각 ∠AOB=∠COD도 같아요.<br>① 두 쌍의 대응각이 각각 같아요<br>② 그러므로 △OAB∽△OCD (AA 닮음)이에요<br><span class='xh'>오답 하나씩 격파</span>'항상 합동'은 두 삼각형의 크기(OA와 OC 등)가 다르면 닮았을 뿐 합동은 아니라서 틀려요. '∠OAB와 ∠OCD가 다르다'는 두 각이 평행선의 엇각이라 오히려 같으므로 반대예요. 'OA:OC와 OB:OD가 다르다'도 닮음이면 이 두 비가 같아야 하므로 틀렸어요. '넓이가 항상 같다'는 닮음비가 1이 아닌 이상 넓이도 달라서 성립하지 않아요.",
    core: "AB∥DC면 엇각과 맞꼭지각으로 △OAB∽△OCD!",
  },
  {
    id: "m2u5e083", lessonId: L, type: "multi",
    prompt: `그림에서 ${gsym("ADE", "tri")}와 ${gsym("ACB", "tri")}가 닮음일 때(∠A는 공통, ∠ADE=∠ACB), 다음 중 옳은 비례식을 <b>모두</b> 고르세요.`,
    figure: m2ExamTriSplitFig({ B: 58, C: 60, t: 0.5, mode: "swapped", marks: [{ at: "ADE", label: "●" }, { at: "ACB", label: "●" }] }),
    options: [
      `${gsym("AD", "seg")}:${gsym("AC", "seg")}=${gsym("AE", "seg")}:${gsym("AB", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("AB", "seg")}=${gsym("AE", "seg")}:${gsym("AC", "seg")}`,
      `${gsym("DE", "seg")}:${gsym("CB", "seg")}=${gsym("AD", "seg")}:${gsym("AC", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("DE", "seg")}=${gsym("AB", "seg")}:${gsym("CB", "seg")}`,
      `${gsym("AE", "seg")}:${gsym("AB", "seg")}=${gsym("DE", "seg")}:${gsym("CB", "seg")}`,
    ],
    answer: [0, 2, 4], diff: 3,
    explain: "<span class='xh'>정답 풀이</span>△ADE∽△ACB에서 대응은 A↔A, D↔C, E↔B예요. 그래서 대응변의 비는 AD:AC=AE:AB=DE:CB로 모두 같아요.<br>① AD:AC=AE:AB는 이 기본 비 그대로라 옳아요.<br>② DE:CB=AD:AC도 같은 비의 다른 짝이라 옳아요.<br>③ AE:AB=DE:CB 역시 옳아요.<span class='xh'>오답 하나씩 격파</span>'AD:AB=AE:AC'는 D를 B에, E를 C에 대응시킨 잘못된 짝이에요, 뒤집힌 닮음에서는 D↔C, E↔B라 AD의 짝은 AC예요. 'AD:DE=AB:CB'도 AD의 짝은 AC, DE의 짝은 CB이므로 AD:DE=AC:CB여야 하는데 AB를 끼워 넣어 어긋났어요. 대응 꼭짓점을 먼저 정확히 맞춘 뒤 비를 세우는 게 핵심이에요.",
    core: "뒤집힌 닮음은 D↔C·E↔B, 짝부터 맞추고 비 세우기!",
  },
  {
    id: "m2u5e084", lessonId: L, type: "multi",
    prompt: `다음 중 두 삼각형이 반드시 서로 닮음이 되는 것을 <b>모두</b> 고르세요.`,
    options: [
      "직각삼각형에서 직각인 꼭짓점으로부터 빗변에 내린 수선이 나눈 두 삼각형",
      "두 선분의 양 끝을 이은 두 변이 서로 평행할 때, 두 선분의 교점에서 생기는 위아래 두 삼각형",
      "같은 시각에 잰 막대와 그 그림자로 이루는 삼각형, 그리고 건물과 그 그림자로 이루는 삼각형",
      "넓이가 서로 같은 두 삼각형",
      "한 변의 길이가 서로 같은 두 직각삼각형",
    ],
    answer: [0, 1, 2], diff: 3,
    explain: "<span class='xh'>정답 풀이</span>숨은 닮음은 대응각이 두 쌍 같은지로 판단해요.<br>① 직각삼각형의 수선이 나눈 두 삼각형은 원래 삼각형과, 서로와도 모두 닮음이에요(직각 공유, 한 각 공유).<br>② 양 끝 변이 평행한 나비 모양의 위아래 삼각형은 엇각과 맞꼭지각으로 AA 닮음이에요.<br>③ 같은 시각의 막대와 건물은 햇빛의 각이 같아 그림자 삼각형끼리 닮음이에요.<span class='xh'>오답 하나씩 격파</span>'넓이가 같은 두 삼각형'은 모양이 전혀 달라도 넓이만 같을 수 있어서 닮음이 아니에요, 밑변과 높이를 서로 바꿔도 넓이는 같으니까요. '한 변의 길이가 같은 두 직각삼각형'도 직각 하나와 변 하나만으로는 나머지 각이 제각각이라 닮음을 보장하지 못해요. 닮음은 길이가 아니라 대응각(또는 대응변의 비)으로 정해진다는 점이 핵심이에요.",
    core: "숨은 닮음은 대응각 두 쌍, 넓이·한 변 같음은 근거가 안 돼요!",
  },
  {
    id: "m2u5e085", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `그림에서 ∠A는 공통이고 ∠ADE=∠ACB예요. ${gsym("AD", "seg")}=6 cm, ${gsym("AC", "seg")}=15 cm, ${gsym("AB", "seg")}=10 cm일 때, ${gsym("AE", "seg")}의 길이는 몇 cm인지 구하세요.`,
    figure: m2ExamTriSplitFig({ B: 60, C: 56, t: 0.55, mode: "swapped", marks: [{ at: "ADE", label: "●" }, { at: "ACB", label: "●" }] }),
    answer: "4", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>∠A 공통, ∠ADE=∠ACB이므로 △ADE∽△ACB예요(대응 A↔A, D↔C, E↔B).<br>① 대응변의 비: AD:AC=AE:AB<br>② 6:15=AE:10<br>③ 15×AE=60, AE=<b>4 cm</b><span class='xh'>계산 실수 격파</span>대응을 AD:AB=AE:AC로 잘못 짝지으면 6:10=AE:15에서 AE=9가 나오는데, ∠ADE=∠ACB라 D는 C에, E는 B에 대응하므로 AD의 짝은 AC, AE의 짝은 AB예요. 비례식은 6:15=AE:10처럼 대응 순서대로 세우고, 15×AE=6×10=60에서 AE=4로 마무리하면 돼요.",
    core: "뒤집힌 닮음 AD:AC=AE:AB, 짝을 맞춰 비례식!",
  },
  {
    id: "m2u5e086", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `그림에서 ${gsym("AB", "seg")}∥${gsym("DC", "seg")}이고 두 선분 ${gsym("AC", "seg")}, ${gsym("BD", "seg")}가 점 O에서 만나요. ${gsym("OA", "seg")}=9 cm, ${gsym("OC", "seg")}=15 cm, ${gsym("AB", "seg")}=6 cm일 때, ${gsym("DC", "seg")}의 길이는 몇 cm인지 구하세요.`,
    figure: m2ExamXCrossFig({ rTop: [9, 15], rSide: [9, 15], labels: { OA: "9", OC: "15", AB: "6", DC: "x" }, paraMarks: true }),
    answer: "10", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>AB∥DC이므로 엇각과 맞꼭지각으로 △OAB∽△OCD예요.<br>① 대응변의 비: AB:DC=OA:OC<br>② 6:DC=9:15=3:5<br>③ 3×DC=30, DC=<b>10 cm</b><span class='xh'>계산 실수 격파</span>비를 뒤집어 6:DC=15:9로 세우면 DC=3.6이 나오는데, AB와 짝을 이루는 것은 OA, DC와 짝을 이루는 것은 OC이므로 6:DC=9:15가 맞아요. 9:15는 3:5로 약분해 두면 계산이 편하고, AB(작은 삼각형 변)보다 DC(큰 삼각형 변)가 길어야 한다는 점으로 답의 방향도 점검할 수 있어요.",
    core: "AB∥DC면 AB:DC=OA:OC, 대응 순서대로 비례식!",
  },
  {
    id: "m2u5e087", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `그림에서 ${gsym("ABC", "tri")}는 ∠A=90°인 직각삼각형이고 점 A에서 빗변 ${gsym("BC", "seg")}에 내린 수선의 발이 D예요. ${gsym("BD", "seg")}=9 cm, ${gsym("DC", "seg")}=25 cm일 때, ${gsym("AD", "seg")}의 길이는 몇 cm인지 구하세요.`,
    figure: m2ExamRightAltFig({ bd: 9, dc: 25, labels: { BD: "9", DC: "25", AD: "x" } }),
    answer: "15", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>∠A=90°이고 AD가 빗변에 내린 수선이면 △ABD∽△CAD라서 BD:AD=AD:DC예요.<br>① AD×AD=BD×DC<br>② AD×AD=9×25=225<br>③ 제곱하여 225가 되는 양수는 15이므로 AD=<b>15 cm</b><span class='xh'>계산 실수 격파</span>9와 25를 더해 34로 답하면 그건 수선이 아니라 빗변 BC의 길이예요. 또 225에서 멈추면 AD가 아니라 AD를 제곱한 값이니, 제곱하여 225가 되는 수 15까지 구해야 해요. 15×15=225로 검산하면 확실해요.",
    core: "빗변의 수선은 제곱하면 두 부분의 곱, 곧 9×25=225!",
  },
  {
    id: "m2u5e088", lessonId: L, type: "num", numKind: "int", unitLabel: "m",
    prompt: `같은 시각에 길이가 4 m인 막대를 똑바로 세웠더니 그림자가 6 m였어요. 바로 그때 어떤 나무의 그림자 길이가 33 m였다면, 이 나무의 높이는 몇 m인지 구하세요.`,
    answer: "22", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>같은 시각에는 햇빛의 각이 같아서 막대와 나무가 만드는 그림자 삼각형이 서로 닮음이에요.<br>① (높이):(그림자)의 비가 같아요<br>② 4:6=(나무 높이):33<br>③ 6×(높이)=132, 높이=<b>22 m</b><span class='xh'>계산 실수 격파</span>비를 6:4로 뒤집어 33×6÷4로 계산하면 49.5가 나오는데, 그림자 6보다 막대 4가 짧으니 나무 높이도 그림자보다 짧아야 해요. 4:6은 2:3으로 약분해 두면 33×2÷3=22로 바로 나와요. '높이:그림자' 순서를 두 삼각형에서 똑같이 맞추는 게 핵심이에요.",
    core: "같은 시각 그림자는 닮음, 높이:그림자 비로 나무 높이 계산!",
  },
  {
    id: "m2u5e089", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `그림에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있고 ∠ADE=∠B예요. ${gsym("AD", "seg")}=5 cm, ${gsym("AB", "seg")}=15 cm, ${gsym("DE", "seg")}=7 cm일 때, ${gsym("BC", "seg")}의 길이는 몇 cm인지 구하세요.`,
    figure: m2ExamTriSplitFig({ B: 62, C: 50, t: 0.333, mode: "para", paraMarks: false, labels: { AD: "5", AB: "15", DE: "7" }, marks: [{ at: "ADE", label: "●" }, { at: "ABC", label: "●" }] }),
    answer: "21", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>∠A는 공통이고 ∠ADE=∠B(=∠ABC)이므로 △ADE∽△ABC예요(대응 A↔A, D↔B, E↔C).<br>① 대응변의 비: AD:AB=DE:BC<br>② 5:15=7:BC, 즉 1:3=7:BC<br>③ BC=7×3=<b>21 cm</b><span class='xh'>계산 실수 격파</span>AD:AB를 15:5로 뒤집어 3:1=7:BC로 세우면 BC가 7보다 작아지는데, BC는 큰 삼각형 ABC의 밑변이라 작은 삼각형의 DE=7보다 길어야 해요. 5:15는 1:3으로 약분해 두면 7×3=21로 바로 나와요. 대응변 DE와 BC를 정확히 짝지어 같은 순서로 비례식을 세우는 게 핵심이에요.",
    core: "∠ADE=∠B면 △ADE∽△ABC, DE:BC로 밑변 구하기!",
  },
  {
    id: "m2u5e090", lessonId: L, type: "word",
    prompt: `다음 <b>빈칸</b>에 들어갈 알맞은 말을 고르세요.<br><br>두 직선이 한 점에서 만날 때, 서로 마주 보는 두 각을 ___이라고 해요.`,
    bank: ["맞꼭지각", "동위각", "엇각", "평각", "직각", "외각", "대각", "둔각"],
    answer: "맞꼭지각", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>두 직선이 한 점에서 만나면 네 개의 각이 생기고, 그중 꼭짓점을 사이에 두고 서로 마주 보는 두 각을 <b>맞꼭지각</b>이라고 해요. 맞꼭지각의 크기는 항상 서로 같아서, 겹친 삼각형에서 숨은 닮음을 찾을 때 중요한 단서가 돼요.<span class='xh'>낱말 하나씩 격파</span>'동위각'과 '엇각'은 한 직선이 평행한 두 직선을 가로지를 때 생기는 각이라 상황이 달라요. '평각'은 180°인 각, '직각'은 90°인 각을 가리키는 말이에요. '외각'은 다각형의 한 변을 연장했을 때 생기는 각, '대각'은 사각형에서 마주 보는 각, '둔각'은 90°보다 크고 180°보다 작은 각이라 모두 두 직선의 교점에서 마주 보는 두 각을 뜻하지 않아요.",
    core: "두 직선의 교점에서 마주 보는 두 각은 맞꼭지각, 크기가 같아요!",
  },
  {
    id: "m2u5e091", lessonId: L, type: "word",
    prompt: `다음 <b>빈칸</b>에 들어갈 알맞은 말을 고르세요.<br><br>삼각형의 한 꼭짓점에서 마주 보는 변에 수직으로 그은 선분을 ___이라고 해요.`,
    bank: ["수선", "중선", "대각선", "접선", "현", "반지름", "평행선", "엇각"],
    answer: "수선", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>삼각형의 한 꼭짓점에서 마주 보는 변에 수직으로 그은 선분을 <b>수선</b>이라고 해요. 직각삼각형에서 직각인 꼭짓점으로부터 빗변에 수선을 내리면 원래 삼각형과 닮은 두 작은 직각삼각형이 생겨, 겹친 닮음의 대표적인 예가 돼요.<span class='xh'>낱말 하나씩 격파</span>'중선'은 꼭짓점에서 마주 보는 변의 <b>중점</b>에 그은 선분이라 수직이 아니에요. '대각선'은 다각형의 두 꼭짓점을 잇는 선분이고요. '접선', '현', '반지름'은 원에서 쓰는 말이라 삼각형의 수선과는 상관이 없어요. '평행선'은 만나지 않는 두 직선, '엇각'은 각의 한 종류라 선분을 가리키는 이 빈칸에 맞지 않아요.",
    core: "꼭짓점에서 대변에 수직으로 그은 선분은 수선!",
  },
];
