// 중2 수학 Ⅴ. 도형의 닮음과 피타고라스 정리: 단원 종합 평가 풀, 레슨 6 삼각형과 평행선: 잘라도 같은 비 (m2u5e092~e109) · 책 204~205쪽
// 유형 쿼터: mcq 9 + multi 2 = 11 · num 5 · word 2, diff 7/7/4.
// 함정 계보(교과서 대조): 전체:부분 혼동(DE:BC=AD:AB), 비 뒤집기, 평행 판정 반례, 거꾸로 방향.
// 수치 앵커 회피: 레슨 (6,3,8→4)·(4,10,6→15)·3:1·(5,15,4→12)·1:2·(8,4,5→10)·6:3=10:5·2:1·BC12·DE3·6·8·9 회피(브리프 준수).
// word 정답: 동위각(e108)·엇각(e109).
// 표기: em대시 금지, 뺄셈·차는 −(U+2212), 기하 기호는 gsym·유니코드 리터럴(mfmt 미사용).
import type { ExamItem } from "./types";
import { gsym } from "../../ui/geoKit";
import { m2ExamTriSplitFig, m2ExamXCrossFig } from "../../ui/examFiguresMath";
const L = "m2u5l6";

export const POOL_M2U5L6: ExamItem[] = [
  {
    id: "m2u5e092", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 ${gsym("AD", "seg")}=9 cm, ${gsym("DB", "seg")}=6 cm, ${gsym("AE", "seg")}=12 cm일 때, ${gsym("EC", "seg")}의 길이는?`,
    figure: m2ExamTriSplitFig({ B: 68, C: 50, t: 0.6, mode: "para", labels: { AD: "9", DB: "6", AE: "12", EC: "x" } }),
    options: [
      "8 cm",
      "18 cm",
      "6 cm",
      "10 cm",
      "4 cm",
    ],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 평행선이 두 변을 같은 비로 나눠요.<br>① AD:DB=AE:EC<br>② 9:6=12:EC, 즉 3:2=12:EC<br>③ 3×EC=24, EC=<b>8 cm</b><span class='xh'>오답 하나씩 격파</span>18 cm는 비를 뒤집어 9:6=EC:12로 세운 값인데, AD와 짝을 이루는 것은 AE, DB와 짝을 이루는 것은 EC라 9:6=12:EC가 맞아요. 6 cm는 DB를 그대로 옮긴 값이고, 10 cm와 4 cm는 3:2=12:EC를 만족하지 않아요. 평행선이 나눈 두 변의 대응하는 부분끼리 같은 순서로 비례식을 세우는 게 핵심이에요.",
    core: "DE∥BC면 AD:DB=AE:EC, 평행선은 두 변을 같은 비로!",
  },
  {
    id: "m2u5e093", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 ${gsym("AD", "seg")}=4 cm, ${gsym("AB", "seg")}=14 cm, ${gsym("DE", "seg")}=6 cm일 때, ${gsym("BC", "seg")}의 길이는?`,
    figure: m2ExamTriSplitFig({ B: 58, C: 46, t: 0.286, mode: "para", labels: { AD: "4", AB: "14", DE: "6", BC: "x" } }),
    options: [
      "15 cm",
      "21 cm",
      "18 cm",
      "9 cm",
      "24 cm",
    ],
    answer: 1, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 큰 삼각형과 작은 삼각형이 닮아, '전체 변'끼리 비교해요.<br>① AD:AB=DE:BC<br>② 4:14=6:BC, 즉 2:7=6:BC<br>③ 2×BC=42, BC=<b>21 cm</b><span class='xh'>오답 하나씩 격파</span>15 cm는 AD:DB=4:10을 써서 DE:BC=2:5로 잘못 세운 값이에요, DE와 BC는 두 삼각형의 '밑변'이라 부분(DB)이 아니라 전체 변(AB)과 짝지어야 해요. 18 cm와 24 cm, 9 cm는 2:7=6:BC를 만족하지 않아요. DE:BC는 AD:AB(전체:전체)와 같다는 점이 이 문제의 핵심이에요.",
    core: "DE:BC는 AD:AB(전체:전체), 부분 DB와 헷갈리지 마요!",
  },
  {
    id: "m2u5e094", lessonId: L, type: "mcq",
    prompt: `${gsym("ABC", "tri")}에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. ${gsym("AD", "seg")}=6, ${gsym("DB", "seg")}=4, ${gsym("AE", "seg")}=9, ${gsym("EC", "seg")}=6일 때, ${gsym("DE", "seg")}와 ${gsym("BC", "seg")}에 대한 설명으로 옳은 것은?`,
    options: [
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}≠${gsym("AE", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}는 ${gsym("BC", "seg")}와 평행하지 않다`,
      `${gsym("DE", "seg")}는 ${gsym("BC", "seg")}의 길이의 절반이다`,
      `${gsym("AD", "seg")}=${gsym("AE", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("DB", "seg")}=${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
    ],
    answer: 0, diff: 1,
    explain: "<span class='xh'>정답 풀이</span>삼각형의 두 변 위의 점이 각 변을 <b>같은 비</b>로 나누면, 두 점을 이은 선분은 나머지 변과 평행해요.<br>① AD:DB=6:4=3:2<br>② AE:EC=9:6=3:2<br>③ 두 비가 3:2로 같으므로 DE∥BC예요.<span class='xh'>오답 하나씩 격파</span>'AD:DB≠AE:EC'라는 말은 실제로 두 비가 3:2로 같으므로 사실과 달라요. 'DE가 BC의 절반'이라는 건 주어진 값으로 확인할 수 없는 근거 없는 주장이에요. 'AD=AE'는 6과 9로 서로 다르고, 'DB=EC'도 4와 6으로 달라서, 두 변을 나눈 비가 같은지를 봐야지 길이가 같은지를 보는 게 아니에요.",
    core: "두 변을 같은 비로 나누면 이은 선분은 밑변과 평행!",
  },
  {
    id: "m2u5e095", lessonId: L, type: "mcq",
    prompt: `${gsym("ABC", "tri")}에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있고 ${gsym("AD", "seg")}=4, ${gsym("DB", "seg")}=5, ${gsym("AE", "seg")}=5, ${gsym("EC", "seg")}=6이에요. ${gsym("DE", "seg")}와 ${gsym("BC", "seg")}에 대한 설명으로 옳은 것은?`,
    options: [
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}≠${gsym("AE", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}는 ${gsym("BC", "seg")}와 평행하지 않다`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}이지만 ${gsym("DE", "seg")}는 ${gsym("BC", "seg")}와 평행하지 않다`,
      `${gsym("AE", "seg")}가 ${gsym("AD", "seg")}보다 기니까 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `네 값이 모두 다르므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
    ],
    answer: 1, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC인지 확인하려면 두 변을 나눈 비 AD:DB와 AE:EC가 같은지 봐요.<br>① AD:DB=4:5<br>② AE:EC=5:6<br>③ 4×6=24, 5×5=25로 곱이 달라 두 비가 서로 다르므로 DE∥BC가 아니에요.<span class='xh'>오답 하나씩 격파</span>'AD:DB=AE:EC이므로 평행'은 두 비가 실제로는 다르니 전제부터 틀렸어요. 'AD:DB=AE:EC인데 평행이 아니다'는 비가 같으면 반드시 평행이 되므로 앞뒤가 맞지 않아요. 'AE가 AD보다 길다'거나 '네 값이 모두 다르다'는 평행 여부와 상관없는 이야기라 근거가 될 수 없어요. 비가 같은지 다른지가 유일한 판단 기준이에요.",
    core: "두 변을 나눈 비가 다르면 DE는 BC와 평행하지 않아요!",
  },
  {
    id: "m2u5e096", lessonId: L, type: "mcq",
    prompt: `${gsym("ABC", "tri")}에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있고 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}예요. ${gsym("AD", "seg")}:${gsym("DB", "seg")}=2:5일 때, ${gsym("DE", "seg")}:${gsym("BC", "seg")}는?`,
    options: [
      "2:5",
      "2:7",
      "5:7",
      "7:2",
      "5:2",
    ],
    answer: 1, diff: 3,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 DE:BC는 작은 삼각형과 큰 삼각형의 '밑변의 비'이고, 이는 AD:AB(전체 변의 비)와 같아요.<br>① AD:DB=2:5이므로 AB=AD+DB의 비로 보면 AD:AB=2:(2+5)=2:7<br>② DE:BC=AD:AB=2:7<br>따라서 DE:BC=<b>2:7</b>이에요.<span class='xh'>오답 하나씩 격파</span>2:5는 AD:DB(부분과 부분의 비)를 그대로 DE:BC에 옮긴 대표적인 실수예요, DE와 BC는 부분이 아니라 두 삼각형의 밑변 '전체'라 AD:AB와 짝지어야 해요. 5:7과 5:2, 7:2는 비의 앞뒤나 숫자를 뒤섞은 값이라 맞지 않아요. '부분:부분'과 '전체:전체'를 구분하는 게 이 문제의 핵심이에요.",
    core: "DE:BC=AD:AB(전체:전체), AD:DB(부분:부분)와 달라요!",
  },
  {
    id: "m2u5e097", lessonId: L, type: "mcq",
    prompt: `삼각형에서 한 변 위의 점 D와 다른 변 위의 점 E에 대하여 ${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}가 성립할 때, 이에 대한 설명으로 옳은 것은?`,
    options: [
      `두 변을 같은 비로 나누었으므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `비가 같아도 ${gsym("DE", "seg")}와 ${gsym("BC", "seg")}가 평행한지는 알 수 없다`,
      `${gsym("DE", "seg")}∥${gsym("BC", "seg")}이려면 ${gsym("AD", "seg")}=${gsym("AE", "seg")}도 반드시 필요하다`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}는 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}일 때만 성립하고, 거꾸로 방향은 성립하지 않는다`,
      `이 조건만으로는 삼각형이 정해지지 않아 평행을 판단할 수 없다`,
    ],
    answer: 0, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>'두 변을 같은 비로 나누면 이은 선분이 평행하다'는 성질은 거꾸로 방향도 참이에요. 즉 AD:DB=AE:EC이면 두 점 D, E가 두 변을 같은 비로 나눈 것이므로, 이은 선분 DE는 나머지 변 BC와 <b>평행</b>해요.<span class='xh'>오답 하나씩 격파</span>'비가 같아도 평행한지 알 수 없다'는 이 성질을 부정하는 말이라 틀려요. 'AD=AE도 필요하다'는 길이가 같을 필요는 없고 비만 같으면 되므로 지나친 조건이에요. '평행일 때만 성립하고 거꾸로는 안 된다'는 실제로는 거꾸로 방향(비가 같으면 평행)도 성립하므로 틀렸어요. '삼각형이 정해지지 않아 판단 못 한다'도 비만 같으면 평행이 확정되므로 근거가 없어요.",
    core: "비가 같으면 평행, 거꾸로 방향도 참이에요!",
  },
  {
    id: "m2u5e098", lessonId: L, type: "mcq",
    prompt: `그림은 삼각형 모양의 지붕 뼈대예요. 바닥 ${gsym("BC", "seg")}와 평행하게 가로대 ${gsym("DE", "seg")}를 대었더니 ${gsym("AD", "seg")}:${gsym("AB", "seg")}=2:3이 되었어요. 바닥 ${gsym("BC", "seg")}의 길이가 27 m일 때, 가로대 ${gsym("DE", "seg")}의 길이는?`,
    figure: m2ExamTriSplitFig({ B: 66, C: 44, t: 0.667, mode: "para", labels: { DE: "x", BC: "27" } }),
    options: [
      "40.5 m",
      "13.5 m",
      "18 m",
      "20 m",
      "9 m",
    ],
    answer: 2, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>가로대 DE가 바닥 BC와 평행하므로 △ADE∽△ABC예요.<br>① DE:BC=AD:AB<br>② DE:27=2:3<br>③ 3×DE=54, DE=<b>18 m</b><span class='xh'>오답 하나씩 격파</span>40.5 m는 비를 3:2로 뒤집어 27×3÷2로 계산한 값인데, DE는 위쪽의 짧은 가로대라 바닥 27 m보다 짧아야 해요. 13.5 m는 27을 그냥 절반으로 나눈 값이라 2:3이라는 비를 쓰지 않았고요. 20 m와 9 m는 DE:27=2:3을 만족하지 않아요. 평행한 가로대와 바닥은 전체 삼각형의 닮음비 2:3을 그대로 따른다는 게 핵심이에요.",
    core: "바닥과 평행한 가로대는 닮음비 그대로, DE:BC=AD:AB!",
  },
  {
    id: "m2u5e099", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("AB", "seg")}∥${gsym("DC", "seg")}이고 두 선분 ${gsym("AC", "seg")}, ${gsym("BD", "seg")}가 점 O에서 만나요. ${gsym("OA", "seg")}=8, ${gsym("OC", "seg")}=12, ${gsym("OB", "seg")}=14일 때, ${gsym("OD", "seg")}의 길이 <i class='mv'>x</i>는?`,
    figure: m2ExamXCrossFig({ rTop: [8, 12], rSide: [14, 21], labels: { OA: "8", OC: "12", OB: "14", OD: "x" }, paraMarks: true }),
    options: [
      "18",
      "28",
      "9",
      "21",
      "16",
    ],
    answer: 3, diff: 2,
    explain: "<span class='xh'>정답 풀이</span>AB∥DC이므로 엇각 ∠OAB=∠OCD가 같고, 맞꼭지각 ∠AOB=∠COD도 같아 △OAB∽△OCD예요.<br>① 대응변의 비: OA:OC=OB:OD<br>② 8:12=14:OD, 즉 2:3=14:OD<br>③ 2×OD=42, OD=<b>21</b><span class='xh'>오답 하나씩 격파</span>비를 뒤집어 8:12=OD:14로 세우면 약 9가 나오는데, OB(14)와 짝을 이루는 것은 OD이므로 2:3=14:OD가 맞아요. 28은 14에 2를 곱하기만 한 값, 16과 18은 2:3=14:OD를 만족하지 않는 값이에요. 평행선이 만든 엇각으로 두 삼각형이 닮았다는 것을 먼저 알아채는 게 핵심이에요.",
    core: "AB∥DC의 엇각으로 △OAB∽△OCD, OA:OC=OB:OD!",
  },
  {
    id: "m2u5e100", lessonId: L, type: "mcq",
    prompt: `그림에서 ${gsym("AD", "seg")}=6, ${gsym("DB", "seg")}=4, ${gsym("AE", "seg")}=4, ${gsym("EC", "seg")}=6이에요. 이 그림에 대한 설명으로 옳은 것은?`,
    figure: m2ExamTriSplitFig({ B: 60, C: 52, t: 0.6, s: 0.4, mode: "free", labels: { AD: "6", DB: "4", AE: "4", EC: "6" } }),
    options: [
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("AD", "seg")}=${gsym("EC", "seg")}이고 ${gsym("DB", "seg")}=${gsym("AE", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("AD", "seg")}:${gsym("AE", "seg")}=${gsym("DB", "seg")}:${gsym("EC", "seg")}이므로 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이다`,
      `${gsym("DE", "seg")}와 ${gsym("BC", "seg")}는 항상 평행하다`,
      `두 변을 나눈 두 비가 서로 달라서 ${gsym("DE", "seg")}는 ${gsym("BC", "seg")}와 평행하지 않다`,
    ],
    answer: 4, diff: 3,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC인지는 두 변을 나눈 비 AD:DB와 AE:EC가 같은지로 판단해요.<br>① AD:DB=6:4=3:2<br>② AE:EC=4:6=2:3<br>③ 3:2와 2:3은 서로 다르므로(3×3=9, 2×2=4로 곱이 다름) DE는 BC와 평행하지 않아요. 그림에서도 DE가 BC와 나란하지 않게 그려져 있어요.<span class='xh'>오답 하나씩 격파</span>'AD:DB=AE:EC이므로 평행'은 두 비가 실제로 다르니 전제가 틀렸어요. 'AD=EC, DB=AE이므로 평행'은 길이가 우연히 같을 뿐, 평행의 기준은 두 변을 나눈 '비'가 같은지예요. 'AD:AE=DB:EC이므로 평행'도 6:4와 4:6이 서로 달라 성립하지 않고, 애초에 이건 평행 판정의 올바른 형태도 아니에요. '항상 평행'은 근거 없는 단정이에요.",
    core: "두 변을 나눈 비 AD:DB와 AE:EC가 달라 DE는 BC와 평행 아님!",
  },
  {
    id: "m2u5e101", lessonId: L, type: "multi",
    prompt: `그림에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}일 때, 다음 중 옳은 비례식을 <b>모두</b> 고르세요.`,
    figure: m2ExamTriSplitFig({ B: 63, C: 49, t: 0.5, mode: "para" }),
    options: [
      `${gsym("AD", "seg")}:${gsym("AB", "seg")}=${gsym("AE", "seg")}:${gsym("AC", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("AE", "seg")}:${gsym("EC", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("DB", "seg")}=${gsym("DE", "seg")}:${gsym("BC", "seg")}`,
      `${gsym("AE", "seg")}:${gsym("AC", "seg")}=${gsym("DE", "seg")}:${gsym("BC", "seg")}`,
      `${gsym("AD", "seg")}:${gsym("AB", "seg")}=${gsym("DB", "seg")}:${gsym("EC", "seg")}`,
    ],
    answer: [0, 1, 3], diff: 3,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 두 종류의 참인 비가 있어요.<br>① '전체:전체' 방향: AD:AB=AE:AC=DE:BC<br>② '부분:부분' 방향: AD:DB=AE:EC<br>그래서 AD:AB=AE:AC, AD:DB=AE:EC, AE:AC=DE:BC가 모두 옳아요.<span class='xh'>오답 하나씩 격파</span>'AD:DB=DE:BC'는 왼쪽이 부분과 부분의 비, 오른쪽이 두 밑변(작은 변과 큰 변)의 비라 종류가 달라 같아지지 않아요, DE:BC는 AD:AB(전체)와 짝지어야 해요. 'AD:AB=DB:EC'도 왼쪽은 전체에 대한 부분의 비인데 오른쪽 DB:EC는 서로 대응하지 않는 부분끼리 묶은 것이라 성립하지 않아요. '전체:전체'와 '부분:부분'을 섞지 않는 게 핵심이에요.",
    core: "DE∥BC의 참인 비는 전체:전체와 부분:부분, 섞으면 틀려요!",
  },
  {
    id: "m2u5e102", lessonId: L, type: "multi",
    prompt: `${gsym("ABC", "tri")}에서 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. 다음 중 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}인 것을 <b>모두</b> 고르세요.`,
    options: [
      `${gsym("AD", "seg")}=3, ${gsym("DB", "seg")}=2, ${gsym("AE", "seg")}=6, ${gsym("EC", "seg")}=4`,
      `${gsym("AD", "seg")}=4, ${gsym("DB", "seg")}=6, ${gsym("AE", "seg")}=6, ${gsym("EC", "seg")}=9`,
      `${gsym("AD", "seg")}=5, ${gsym("DB", "seg")}=3, ${gsym("AE", "seg")}=4, ${gsym("EC", "seg")}=3`,
      `${gsym("AD", "seg")}=8, ${gsym("DB", "seg")}=6, ${gsym("AE", "seg")}=12, ${gsym("EC", "seg")}=9`,
      `${gsym("AD", "seg")}=2, ${gsym("DB", "seg")}=5, ${gsym("AE", "seg")}=3, ${gsym("EC", "seg")}=4`,
    ],
    answer: [0, 1, 3], diff: 3,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC가 되려면 AD:DB=AE:EC여야 해요. 각 세트에서 두 비를 곱셈으로 검산해요.<br>① 3:2와 6:4는 3×4=12=2×6이라 같아서 평행<br>② 4:6과 6:9는 4×9=36=6×6이라 같아서 평행<br>③ 8:6과 12:9는 8×9=72=6×12라 같아서 평행<span class='xh'>오답 하나씩 격파</span>AD=5, DB=3, AE=4, EC=3인 세트는 5:3과 4:3에서 5×3=15, 3×4=12로 곱이 달라 평행이 아니에요. AD=2, DB=5, AE=3, EC=4인 세트도 2:5와 3:4에서 2×4=8, 5×3=15로 달라 평행이 아니고요. 두 비의 앞뒤를 곱해 값이 같은지 확인하면 실수 없이 판정할 수 있어요.",
    core: "AD:DB=AE:EC인 세트만 DE∥BC, 곱셈으로 검산!",
  },
  {
    id: "m2u5e103", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `${gsym("ABC", "tri")}에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. ${gsym("AD", "seg")}=10 cm, ${gsym("DB", "seg")}=4 cm, ${gsym("AE", "seg")}=15 cm일 때, ${gsym("EC", "seg")}의 길이는 몇 cm인지 구하세요.`,
    answer: "6", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 평행선이 두 변을 같은 비로 나눠요.<br>① AD:DB=AE:EC<br>② 10:4=15:EC, 즉 5:2=15:EC<br>③ 5×EC=30, EC=<b>6 cm</b><span class='xh'>계산 실수 격파</span>비를 뒤집어 10:4=EC:15로 세우면 EC=37.5가 나오는데, AD와 짝을 이루는 것은 AE, DB와 짝을 이루는 것은 EC이므로 10:4=15:EC가 맞아요. 10:4는 5:2로 약분해 두면 5×EC=2×15=30에서 EC=6으로 마무리하면 돼요. 답을 넣어 15:6=5:2가 되는지 되짚으면 검산까지 끝나요.",
    core: "DE∥BC면 AD:DB=AE:EC, 대응 순서대로 비례식!",
  },
  {
    id: "m2u5e104", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `${gsym("ABC", "tri")}에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. ${gsym("AD", "seg")}=6 cm, ${gsym("AB", "seg")}=15 cm, ${gsym("DE", "seg")}=8 cm일 때, ${gsym("BC", "seg")}의 길이는 몇 cm인지 구하세요.`,
    answer: "20", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 △ADE∽△ABC라 전체 변끼리 비교해요.<br>① AD:AB=DE:BC<br>② 6:15=8:BC, 즉 2:5=8:BC<br>③ 2×BC=40, BC=<b>20 cm</b><span class='xh'>계산 실수 격파</span>AD:DB로 잘못 보고 6:9=8:BC로 세우면 BC=12가 나오는데, DE와 BC는 두 삼각형의 밑변이라 부분 DB가 아니라 전체 변 AB(=15)와 짝지어야 해요. 6:15는 2:5로 약분하면 2×BC=40에서 BC=20으로 바로 나와요. BC가 DE의 2.5배인 20 cm로 나온 것도 전체 변 비 2:5와 맞아떨어져요.",
    core: "DE:BC는 전체 변 AD:AB와 짝, 부분과 헷갈리지 마요!",
  },
  {
    id: "m2u5e105", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `${gsym("ABC", "tri")}에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. ${gsym("AD", "seg")}=12 cm, ${gsym("DB", "seg")}=8 cm, ${gsym("EC", "seg")}=6 cm일 때, ${gsym("AE", "seg")}의 길이는 몇 cm인지 구하세요.`,
    answer: "9", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 평행선이 두 변을 같은 비로 나눠요.<br>① AD:DB=AE:EC<br>② 12:8=AE:6, 즉 3:2=AE:6<br>③ 2×AE=18, AE=<b>9 cm</b><span class='xh'>계산 실수 격파</span>비를 뒤집어 12:8=6:AE로 세우면 AE=4가 나오는데, AD와 짝을 이루는 것은 AE, DB와 짝을 이루는 것은 EC이므로 12:8=AE:6이 맞아요. 12:8은 3:2로 약분해 두면 3:2=AE:6에서 AE=9로 바로 나와요. AE=9와 EC=6의 비가 3:2로 AD:DB와 같은지 되짚으면 검산도 한 번에 끝나요.",
    core: "DE∥BC면 AD:DB=AE:EC, 짝을 맞춰 비례식!",
  },
  {
    id: "m2u5e106", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `${gsym("ABC", "tri")}에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 ${gsym("AD", "seg")}:${gsym("AB", "seg")}=5:8이에요. ${gsym("BC", "seg")}=24 cm일 때, ${gsym("DE", "seg")}의 길이는 몇 cm인지 구하세요.`,
    answer: "15", diff: 2,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 △ADE∽△ABC라 DE:BC=AD:AB예요.<br>① DE:BC=AD:AB=5:8<br>② DE:24=5:8<br>③ 8×DE=120, DE=<b>15 cm</b><span class='xh'>계산 실수 격파</span>비를 8:5로 뒤집어 24×8÷5로 계산하면 38.4가 나오는데, DE는 작은 삼각형의 밑변이라 큰 삼각형의 밑변 24 cm보다 짧아야 해요. DE:24=5:8에서 8×DE=5×24=120, DE=15로 마무리하면 돼요. 닮음비 5:8의 앞(작은 것)이 DE, 뒤(큰 것)가 BC에 대응해요.",
    core: "DE:BC=AD:AB=5:8, 작은 밑변 DE를 비례식으로!",
  },
  {
    id: "m2u5e107", lessonId: L, type: "num", numKind: "int", unitLabel: "cm",
    prompt: `${gsym("ABC", "tri")}에서 ${gsym("DE", "seg")}∥${gsym("BC", "seg")}이고 점 D는 ${gsym("AB", "seg")} 위에, 점 E는 ${gsym("AC", "seg")} 위에 있어요. ${gsym("AD", "seg")}=4 cm, ${gsym("DB", "seg")}=10 cm, ${gsym("AE", "seg")}=4 cm일 때, ${gsym("EC", "seg")}의 길이는 몇 cm인지 구하세요.`,
    answer: "10", diff: 2,
    explain: "<span class='xh'>정답 풀이</span>DE∥BC이면 평행선이 두 변을 같은 비로 나눠요.<br>① AD:DB=AE:EC<br>② 4:10=4:EC, 즉 2:5=4:EC<br>③ 2×EC=20, EC=<b>10 cm</b><span class='xh'>계산 실수 격파</span>비를 뒤집어 4:10=EC:4로 세우면 EC=1.6이 나오는데, AD와 짝을 이루는 것은 AE, DB와 짝을 이루는 것은 EC이므로 4:10=4:EC가 맞아요. 4:10을 2:5로 약분한 뒤 2×EC=5×4=20에서 EC=10으로 마무리하면 돼요. 마침 AD와 AE가 4로 같아 EC와 DB도 10으로 같아지는 것을 검산으로도 확인할 수 있어요.",
    core: "DE∥BC면 AD:DB=AE:EC, 약분한 뒤 비례식으로!",
  },
  {
    id: "m2u5e108", lessonId: L, type: "word",
    prompt: `다음 <b>빈칸</b>에 들어갈 알맞은 말을 고르세요.<br><br>평행한 두 직선이 다른 한 직선과 만날 때, 같은 쪽 같은 위치에 있어서 크기가 서로 같은 두 각을 ___이라고 해요.`,
    bank: ["동위각", "엇각", "맞꼭지각", "평각", "내각", "외각", "중심각", "대각"],
    answer: "동위각", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>평행한 두 직선이 다른 한 직선과 만나면 여러 각이 생기는데, 두 직선을 기준으로 <b>같은 쪽 같은 위치</b>에 있는 두 각을 <b>동위각</b>이라고 해요. 두 직선이 평행하면 동위각의 크기는 서로 같아서, 삼각형과 평행선 문제에서 닮음을 찾는 근거가 돼요.<span class='xh'>낱말 하나씩 격파</span>'엇각'은 두 직선 사이에서 서로 엇갈린 쪽에 있는 각이라 위치가 달라요. '맞꼭지각'은 두 직선이 한 점에서 만날 때 마주 보는 각이고요. '평각'은 180°인 각, '내각'과 '외각'은 다각형에서 쓰는 말, '중심각'은 원에서 쓰는 말, '대각'은 사각형에서 마주 보는 각이라 모두 이 빈칸에 맞지 않아요.",
    core: "평행선에서 같은 위치의 두 각은 동위각, 크기가 같아요!",
  },
  {
    id: "m2u5e109", lessonId: L, type: "word",
    prompt: `다음 <b>빈칸</b>에 들어갈 알맞은 말을 고르세요.<br><br>두 직선이 다른 한 직선과 만날 때 두 직선 사이에서 서로 엇갈린 쪽에 놓인 두 각을 ___이라고 하고, 두 직선이 평행하면 이 두 각의 크기는 서로 같아요.`,
    bank: ["엇각", "동위각", "맞꼭지각", "평각", "꼭지각", "밑각", "외각", "대각"],
    answer: "엇각", diff: 1,
    explain: "<span class='xh'>정답 풀이</span>두 직선이 다른 한 직선과 만날 때, 두 직선 사이에서 <b>서로 엇갈린 쪽</b>에 놓인 두 각을 <b>엇각</b>이라고 해요. 두 직선이 평행하면 엇각의 크기는 서로 같아져서, 겹친 삼각형이나 평행선 문제에서 각이 같음을 보이는 근거가 돼요.<span class='xh'>낱말 하나씩 격파</span>'동위각'은 엇갈린 쪽이 아니라 같은 쪽 같은 위치에 있는 각이에요. '맞꼭지각'은 두 직선이 한 점에서 만날 때 마주 보는 각이고요. '평각'은 180°인 각, '꼭지각'과 '밑각'은 이등변삼각형에서 쓰는 말이에요. '외각'은 다각형의 변을 연장했을 때 생기는 각, '대각'은 사각형에서 마주 보는 각이라 서로 엇갈린 쪽의 두 각을 뜻하지 않아요.",
    core: "평행선 사이 엇갈린 쪽의 두 각은 엇각, 크기가 같아요!",
  },
];
